fix notify applied logtail block
matrixorigin/matrixone pull request #10001
Opened 2023-06-12 14:15 UTC by zhangxu19830126

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #9992 

## What this PR does / why we need it:
Use a buffered channel of size 1 to avoid waiter no longer waiting for state and notify being blocked due to ctx cancel

2023-06-12 14:51 UTC, reusee approved these changes

2023-06-12 17:39 UTC, fengttt requested changes

2023-06-13 00:27 UTC, zhangxu19830126 commented on pkg/txn/client/timestamp_waiter.go
> +				c: make(chan struct{}, 1),
yes, return pool will reset channel, and will closed before gc

2023-06-13 02:50 UTC, nnsgmsone approved these changes

2023-06-13 03:36 UTC, zhangxu19830126 commented on pkg/txn/client/timestamp_waiter.go
> +				c: make(chan struct{}, 1),
> And is this OK when you return waiter to sync pool? I mean, you know the channel is empty?

For a wait, either wait until a timeout or wait until a definite timestamp. waiter is closed by simply clearing the channel

2023-06-13 03:57 UTC, fengttt approved these changes

2023-06-13 03:57 UTC, merged