Fix Sum(Decimal) Bug
matrixorigin/matrixone pull request #10222
Opened 2023-06-25 08:37 UTC by zengyan1

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #10148 

## What this PR does / why we need it:

2023-06-26 02:43 UTC, aunjgr approved these changes

2023-06-26 16:13 UTC, fengttt commented on pkg/sql/colexec/agg/stddevpop.go
> +		return nil, moerr.NewOutOfRangeNoCtx("Decimal64", "Stddevpop")
Why not return nil, err?

Whatever eval generate, should be good or better for upper layer.

2023-06-26 16:14 UTC, fengttt requested changes
if an err is already created, most of times we should just keep popping it up instread create another one.

The old err has more accurate stack.    And every New...Error will print out one line in log, we do not want such a duplicate.

2023-06-27 18:18 UTC, fengttt approved these changes

2023-06-28 03:13 UTC, m-schen approved these changes

2023-06-28 07:37 UTC, nnsgmsone approved these changes

2023-06-28 07:39 UTC, heni02 approved these changes

2023-06-28 19:19 UTC, merged