morpc: fix dead lock in ut
matrixorigin/matrixone pull request #10374
Opened 2023-07-03 06:50 UTC by zhangxu19830126

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:
Fix maybe deadlock in ut

2023-07-03 07:52 UTC, reusee approved these changes

2023-07-03 08:44 UTC, fengttt requested changes

2023-07-03 08:44 UTC, fengttt commented on pkg/common/morpc/backend.go
>  	rb.mu.Lock()
still, better wrap this in a function/closure and call defer

2023-07-04 02:07 UTC, reusee approved these changes

2023-07-04 17:24 UTC, fengttt approved these changes

2023-07-05 04:29 UTC, merged