[Subtask]: make shuffle dispatch run concurrently
matrixorigin/matrixone pull request #10439
Opened 2023-07-05 10:46 UTC by badboynt1

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #10424

## What this PR does / why we need it:
split shuffle dispatch into two operators, dispatch and new operator shuffle.
so shuffle can run concurrently. 
improve the performance of tpch.

2023-07-06 02:56 UTC, m-schen approved these changes
lgtm.

2023-07-06 08:18 UTC, badboynt1 commented
tested on eks with 3cn
https://github.com/matrixorigin/mo-auto-test/actions/runs/5472506027

2023-07-06 09:19 UTC, nnsgmsone requested changes
我认为没有必要修改接口来实现这个功能，原有的接口足够完成这个功能，没必要破坏现有的逻辑

2023-07-06 11:17 UTC, badboynt1 commented
> 我认为没有必要修改接口来实现这个功能，原有的接口足够完成这个功能，没必要破坏现有的逻辑

这个我没能明白什么意思，根据群里的讨论，明松和沁璇也没有理解。 能否说的再详细一点？

2023-07-12 11:44 UTC, m-schen commented on pkg/sql/colexec/shuffle/shuffle.go
> +			newBat.Append(context.TODO(), proc.Mp(), bat)
虽然应该不会出现有某一个batch的某一个vector是常量的情况，不过batch.Append方法有bug。无法处理左边是常量的情况。
可以参考order.go算子里头append的写法。

2023-07-18 04:11 UTC, badboynt1 commented
tested on eks 3cn: https://github.com/matrixorigin/mo-auto-test/actions/runs/5582839440/jobs/10202908652

2023-07-18 08:07 UTC, nnsgmsone approved these changes

2023-07-18 08:31 UTC, merged