fix data race for the proc of txnTable
matrixorigin/matrixone pull request #10454
Opened 2023-07-06 03:44 UTC by jensenojs

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #10383

## What this PR does / why we need it:

2023-07-07 06:28 UTC, triump2020 requested changes

2023-07-07 06:28 UTC, triump2020 commented on pkg/vm/engine/disttae/tools.go
`txnTable` can not be used as a argument to `newBlockReaders` function, since `newBlockReaders` function would be called remotely in engine.go.

2023-07-07 07:09 UTC, jensenojs commented on pkg/vm/engine/disttae/tools.go
changed it

2023-07-10 06:15 UTC, nnsgmsone approved these changes

2023-07-18 09:13 UTC, jensenojs commented
其实出现对proc的写的场景就是有些奇怪的，后面要看看为什么

2023-07-19 06:41 UTC, nnsgmsone approved these changes

2023-07-19 07:02 UTC, triump2020 approved these changes

2023-07-19 07:56 UTC, merged