add new system tables for store stages
matrixorigin/matrixone pull request #10617
Opened 2023-07-12 12:02 UTC by YANGGMM

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #8544 

## What this PR does / why we need it:
add new system tables for store stages

2023-07-12 12:06 UTC, m-schen approved these changes

2023-07-13 04:35 UTC, aunjgr approved these changes

2023-07-13 06:09 UTC, heni02 approved these changes

2023-07-16 07:10 UTC, fengttt requested changes
How upgrade works?    You need to write an upgrade function.

2023-07-17 09:42 UTC, YANGGMM commented
> How upgrade works? You need to write an upgrade function.

ok

2023-07-18 01:53 UTC, closed without merging