mo-service: fix file service creation
matrixorigin/matrixone pull request #10700
Opened 2023-07-16 14:50 UTC by reusee

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:
handle rename before create default file services

2023-07-16 16:27 UTC, fengttt requested changes
Should you hack this or fix the merge run config?   see this one

https://github.com/matrixorigin/matrixone/commit/f0069c1c42ae9e1afe2f4bcb866490ce5f0c373f

2023-07-16 17:53 UTC, reusee commented
> Should you hack this or fix the merge run config? see this one
> 
> [f0069c1](https://github.com/matrixorigin/matrixone/commit/f0069c1c42ae9e1afe2f4bcb866490ce5f0c373f)

This PR is not a hack. The S3 fs has been renamed to SHARED. Old configs using S3 as fs names still work. S3 will be renamed to SHARED in the codes. But the renaming is after the default fs creation, leading to duplicated SHARED. This PR moves the renaming before default creation.

2023-07-17 02:00 UTC, zhangxu19830126 approved these changes

2023-07-17 04:30 UTC, fengttt approved these changes

2023-07-17 07:49 UTC, merged