fix bvt test caused by stmt aggr
matrixorigin/matrixone pull request #10823
Opened 2023-07-23 04:37 UTC by gavinyue

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2023-07-23 06:52 UTC, fengttt requested changes
which issue does this PR fixes?  

the query is masked by an issue.   unless you turn it on, it does not test anything.

And why is this 96/97 thing?    Looks like a bad test.

2023-07-24 01:20 UTC, gavinyue commented
> which issue does this PR fixes?
> 
> the query is masked by an issue. unless you turn it on, it does not test anything.
> 
> And why is this 96/97 thing? Looks like a bad test.

yes, the weird test.  So the number has been reduced multiple times from 100 + to 99 to 97...

Basically, it should include the the SQLs that is not generated by the test directly.  So the number has been decrease multiple times when we removed SQLs. 

Easy to make a fix, but I need to double check to understand why we need this test.

2023-07-24 19:54 UTC, fengttt approved these changes

2023-07-24 20:24 UTC, merged

2023-07-27 06:27 UTC, xzxiong commented
this is fix https://github.com/matrixorigin/matrixone/issues/10793