support recursive cte
matrixorigin/matrixone pull request #10860
Opened 2023-07-25 08:09 UTC by iamlinjunhong

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #9780 

## What this PR does / why we need it:

2023-07-25 11:39 UTC, XuPeng-SH commented on pkg/container/batch/batch.go
Batch is a basic data structure, which will affect the compatibility of data. If it is modified, it needs to be adapted for compatibility.

2023-07-25 11:40 UTC, XuPeng-SH requested changes
changes are needed for compatibility

2023-07-25 12:38 UTC, zhangxu19830126 requested changes
All changes after version 0.8 need to be kept compatible. E.g. iota and pb definitions

2023-07-26 01:21 UTC, heni02 approved these changes

2023-07-26 03:54 UTC, aunjgr commented
> All changes after version 0.8 need to be kept compatible. E.g. iota and pb definitions

We can't freeze pb definitions for the time being. Pb of both plan and pipeline is changing.

2023-07-26 04:14 UTC, zhangxu19830126 approved these changes

2023-07-26 04:51 UTC, aunjgr approved these changes
I'm OK with this PR. Some modifications on SINK/SINK_SCAN will be done by @zengyan1

2023-07-26 07:21 UTC, m-schen approved these changes
colexec and function directory lgtm.

2023-07-26 08:25 UTC, nnsgmsone commented on pkg/sql/compile/types.go
> +	stepRegs map[int32][][2]int32
为什么需要一个nodeid参数呢。。

2023-07-26 08:47 UTC, aunjgr approved these changes

2023-07-26 09:16 UTC, XuPeng-SH approved these changes

2023-07-26 10:48 UTC, iamlinjunhong commented on pkg/sql/compile/types.go
> +	stepRegs map[int32][][2]int32
因为递归的 sink scan 需要接收 initial pipeline 的数据和自己的数据，如果没有 nodeid ，initial pipeline 的sink 去 getStepRegs 时会拿到三个发送的地方。正确的应该是两个

2023-07-27 03:14 UTC, merged