Remove precommit write
matrixorigin/matrixone pull request #10957
Opened 2023-08-01 16:26 UTC by triump2020

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2023-08-13 09:28 UTC, zhangxu19830126 requested changes

2023-08-13 09:28 UTC, zhangxu19830126 commented on pkg/txn/client/operator.go
> +	var payload []*txn.TxnRequest
donot use pointer. use value type

2023-08-13 09:28 UTC, zhangxu19830126 commented on pkg/vm/engine/disttae/txn.go
> +	"github.com/matrixorigin/matrixone/pkg/pb/txn"
format imports

2023-08-13 09:28 UTC, zhangxu19830126 commented on pkg/txn/client/types.go
> +	Commit(ctx context.Context) ([]*txn.TxnRequest, error)
use value type slice

2023-08-13 09:28 UTC, zhangxu19830126 commented on pkg/vm/engine/disttae/tools.go
> +func genWriteReqs(ctx context.Context, writes []Entry) ([]*txn.TxnRequest, error) {
use value type slice

2023-08-13 09:28 UTC, zhangxu19830126 commented on pkg/vm/engine/disttae/txn.go
> +func (txn *Transaction) Commit(ctx context.Context) ([]*txn.TxnRequest, error) {
use value type slice

2023-08-14 01:52 UTC, daviszhen approved these changes

2023-08-14 04:06 UTC, nnsgmsone approved these changes

2023-08-14 08:48 UTC, qingxinhome approved these changes

2023-08-16 03:43 UTC, XuPeng-SH approved these changes

2023-08-16 04:13 UTC, merged