support enum type
matrixorigin/matrixone pull request #11004
Opened 2023-08-03 07:06 UTC by YANGGMM

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #6613 

## What this PR does / why we need it:
support enum type

2023-08-03 07:10 UTC, xzxiong approved these changes

2023-08-03 07:10 UTC, xzxiong commented on pkg/util/export/etl/tae.go
> -		return 0, moerr.NewInternalError(ctx, "the value type %d is not support now", *vec.GetType())
lgtm

2023-08-04 02:59 UTC, daviszhen approved these changes

2023-08-04 03:37 UTC, XuPeng-SH requested changes
This PR has a compatibility issue.

2023-08-04 05:28 UTC, reusee approved these changes

2023-08-04 06:19 UTC, ouyuanning approved these changes

2023-08-07 07:56 UTC, qingxinhome approved these changes

2023-08-07 08:05 UTC, nnsgmsone approved these changes

2023-08-07 08:07 UTC, heni02 approved these changes

2023-08-07 08:08 UTC, triump2020 approved these changes

2023-08-08 03:01 UTC, m-schen approved these changes
后续如果要支持enum类型的函数的话可能需要在函数框架改点代码。

2023-08-08 03:50 UTC, aunjgr approved these changes

2023-08-08 05:55 UTC, YANGGMM commented on pkg/sql/plan/function/type_check.go
> +				{toType: types.T_enum, preferLevel: 2},
OK, thanks

2023-08-08 05:55 UTC, YANGGMM commented on pkg/vectorize/enum/enum.go
> +func ParseEnum(elems []string, name string) (uint16, error) {
OK, thanks

2023-08-08 05:55 UTC, YANGGMM commented on pkg/vectorize/enum/enum.go
> +func ParseEnum(elems []string, name string) (uint16, error) {
之前不是跟函数有关的调用方法都放在那个目录下面

2023-08-08 06:03 UTC, YANGGMM commented
> 后续如果要支持enum类型的函数的话可能需要在函数框架改点代码。

好的，如果有需求的话会继续修改，谢谢

2023-08-11 02:20 UTC, LeftHandCold approved these changes

2023-08-11 05:56 UTC, XuPeng-SH approved these changes

2023-08-11 09:21 UTC, merged