Implement IN filter on table scan
matrixorigin/matrixone pull request #11032
Opened 2023-08-04 07:17 UTC by aunjgr

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #10615

## What this PR does / why we need it:

2023-08-08 07:26 UTC, m-schen requested changes

2023-08-08 07:26 UTC, m-schen commented on pkg/sql/colexec/evalExpression.go
> +			if vecData, ok := rightArg.Expr.(*plan.Expr_Bin); ok {
这个不需要做特化，碰到Expr_Bin的时候转成FixedVectorExpressionExecutor就行了。
不需要再去感知fid是不是In或者not in了。

2023-08-08 08:44 UTC, aunjgr commented on pkg/sql/colexec/evalExpression.go
> +			if vecData, ok := rightArg.Expr.(*plan.Expr_Bin); ok {
之后BinData里可能放其他东西，比如bitmap，bloom filter，任何序列化的东西都可以，不一定都是vector。所以要根据函数本身来决定。

2023-08-09 04:13 UTC, m-schen approved these changes

2023-08-09 06:42 UTC, badboynt1 approved these changes

2023-08-09 12:32 UTC, ouyuanning approved these changes

2023-08-10 03:25 UTC, nnsgmsone approved these changes

2023-08-10 03:37 UTC, XuPeng-SH approved these changes

2023-08-10 04:14 UTC, merged