fix concurrency pipeline in recursive cte
matrixorigin/matrixone pull request #11053
Opened 2023-08-05 07:56 UTC by iamlinjunhong

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #10934 

## What this PR does / why we need it:

2023-08-05 08:01 UTC, m-schen requested changes

2023-08-05 08:01 UTC, m-schen commented on pkg/sql/compile/scopeRemoteRun.go
> +			RecSink:             t.RecSink,
还需要改 convertToPipelineInstruction 方法里 从 dispatch.Argument变成pipeline.Instruction的部分。

2023-08-05 08:02 UTC, XuPeng-SH approved these changes

2023-08-05 08:04 UTC, iamlinjunhong commented on pkg/sql/compile/scopeRemoteRun.go
> +			RecSink:             t.RecSink,
done

2023-08-05 08:05 UTC, m-schen approved these changes

2023-08-07 03:09 UTC, nnsgmsone approved these changes

2023-08-07 03:42 UTC, merged