Add approx_count
matrixorigin/matrixone pull request #11104
Opened 2023-08-08 12:42 UTC by zengyan1

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #10685 

## What this PR does / why we need it:

2023-08-09 05:16 UTC, aunjgr requested changes
Need some bvt cases

2023-08-09 10:55 UTC, m-schen approved these changes
function lgtm.

2023-08-09 11:24 UTC, heni02 approved these changes

2023-08-09 13:03 UTC, iamlinjunhong approved these changes

2023-08-10 04:38 UTC, aunjgr requested changes

2023-08-10 04:38 UTC, aunjgr commented on pkg/sql/plan/query_builder.go
> +						exprs[0].Typ.Width = int32(len(exprs[0].Expr.(*plan.Expr_C).C.Value.(*plan.Const_Sval).Sval))
you have a more readable way to do this

2023-08-10 04:38 UTC, aunjgr commented on pkg/sql/plan/query_builder.go
> +						agg.F.Args[0].Typ = builder.qry.Nodes[node.Children[0]].TableDef.Cols[agg.F.Args[0].Expr.(*plan.Expr_Col).Col.RelPos].Typ
should avoid type assertion as much as possible, for both safety and readability

2023-08-10 04:38 UTC, aunjgr commented on pkg/sql/plan/query_builder.go
> +						agg.F.Args[0].Typ = builder.qry.Nodes[node.Children[0]].TableDef.Cols[agg.F.Args[0].Expr.(*plan.Expr_Col).Col.RelPos].Typ
and the `RelPos` here is wrong

2023-08-10 04:55 UTC, aunjgr approved these changes

2023-08-10 10:19 UTC, merged