[feature] forward read and write between cns
matrixorigin/matrixone pull request #11210
Opened 2023-08-14 09:07 UTC by volgariver6

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #9704

## What this PR does / why we need it:

2023-08-14 09:45 UTC, reusee requested changes

2023-08-14 09:45 UTC, reusee commented on proto/fileservice.proto
> +  int64 Sz = 3;
Please name it Size

2023-08-17 19:53 UTC, reusee requested changes

2023-08-17 19:53 UTC, reusee commented on pkg/fileservice/cache.go
> -type CacheKey struct {
please use type CacheKey = pb.CacheKey

2023-08-17 19:53 UTC, reusee commented on pkg/fileservice/mem_cache.go
> +			Sz:     entry.Size,
please name the field Size.

2023-08-17 19:53 UTC, reusee commented on pkg/fileservice/config.go
> +	ctx context.Context, cfg Config, perfCounterSets []*perfcounter.CounterSet, factory KeyRouterFactory,
the factory parameter should be in the CacheConfig struct.

2023-08-17 19:53 UTC, reusee commented on pkg/fileservice/config.go
> +	ctx context.Context, cfg Config, perfCounters []*perfcounter.CounterSet, factory KeyRouterFactory,
should move factory param to Config.CacheConfig

2023-08-17 19:53 UTC, reusee commented on pkg/fileservice/config.go
> +	ctx context.Context, cfg Config, perfCounters []*perfcounter.CounterSet, factory KeyRouterFactory,
should move factory param to Config.CacheConfig

2023-08-17 19:53 UTC, reusee commented on pkg/fileservice/s3_fs.go
> +	factory KeyRouterFactory,
should move the factory param to CacheConfig.

2023-08-17 19:53 UTC, reusee commented on pkg/fileservice/s3_fs.go
> +	factory KeyRouterFactory,
should move the factory param to CacheConfig

2023-08-18 00:07 UTC, zhangxu19830126 approved these changes

2023-08-19 03:20 UTC, fengttt requested changes
Can we have a better commit message?

When will do this forward.   What is the relationship with proxy, transactions, locks, and node failures etc.   What is the target use case (to benefit), and if it is performance, how much gain.

If you decided to fill these info in the issue, I think that is fine too.

2023-08-19 04:31 UTC, volgariver6 commented
> Can we have a better commit message?
> 
> When will do this forward. What is the relationship with proxy, transactions, locks, and node failures etc. What is the target use case (to benefit), and if it is performance, how much gain.
> 
> If you decided to fill these info in the issue, I think that is fine too.

PR 还有点问题，正在测试，等测试完成我再完善相关信息

2023-08-19 06:56 UTC, reusee requested changes

2023-08-19 06:56 UTC, reusee commented on pkg/fileservice/remote_cache.go
> +	if r.keyRouter == nil {
This block should be in a sync.Once.Do, since Read may be called concurrently.

2023-08-19 06:56 UTC, reusee commented on pkg/fileservice/remote_cache.go
> +					if idx < len(vector.Entries) {
length of vector.Entries will never change, why this check?

2023-08-19 06:56 UTC, reusee commented on pkg/fileservice/remote_cache.go
> +						if cacheData.Hit {
I think this should be `if cacheData.Hit { entry.done = true; entry.CachedData = cacheData.Data }``. Caches only set the CachedData field, not the Data field. See the memory cache codes

2023-08-21 07:23 UTC, volgariver6 commented
wait for @reusee to submit a PR to support read cache data from remote in fileservice.

2023-08-23 05:05 UTC, reusee approved these changes

2023-08-24 07:52 UTC, volgariver6 commented
TPMC on EKS:

Before:

```
2023-08-24 05:52:48 INFO  jTPCC:758 - Term-00,
2023-08-24 05:52:48 INFO  jTPCC:759 - Term-00,
2023-08-24 05:52:48 INFO  jTPCC:760 - Term-00, Measured tpmC (NewOrders) = 2140.48
2023-08-24 05:52:48 INFO  jTPCC:761 - Term-00, Measured tpmTOTAL = 5260.22
2023-08-24 05:52:48 INFO  jTPCC:762 - Term-00, Measured tpmE (ErrorCount) = 562.73
2023-08-24 05:52:48 INFO  jTPCC:763 - Term-00, Session Start     = 2023-08-24 05:47:47
2023-08-24 05:52:48 INFO  jTPCC:764 - Term-00, Session End       = 2023-08-24 05:52:48
2023-08-24 05:52:48 INFO  jTPCC:765 - Term-00, Transaction Count = 26331
2023-08-24 05:52:48 INFO  jTPCC:766 - Term-00, Transaction Error = 2817
2023-08-24 05:52:48 INFO  jTPCC:767 - Term-00, Transaction NewOrders = 10715
2023-08-24 05:52:48 INFO  jTPCC:790 - Term-00, Session finished!
```

After:

```
2023-08-24 06:59:38 INFO  jTPCC:758 - Term-00,
2023-08-24 06:59:38 INFO  jTPCC:759 - Term-00,
2023-08-24 06:59:38 INFO  jTPCC:760 - Term-00, Measured tpmC (NewOrders) = 2560.31
2023-08-24 06:59:38 INFO  jTPCC:761 - Term-00, Measured tpmTOTAL = 6315.92
2023-08-24 06:59:38 INFO  jTPCC:762 - Term-00, Measured tpmE (ErrorCount) = 703.16
2023-08-24 06:59:38 INFO  jTPCC:763 - Term-00, Session Start     = 2023-08-24 06:54:37
2023-08-24 06:59:38 INFO  jTPCC:764 - Term-00, Session End       = 2023-08-24 06:59:38
2023-08-24 06:59:38 INFO  jTPCC:765 - Term-00, Transaction Count = 31634
2023-08-24 06:59:38 INFO  jTPCC:766 - Term-00, Transaction Error = 3522
2023-08-24 06:59:38 INFO  jTPCC:767 - Term-00, Transaction NewOrders = 12824
2023-08-24 06:59:38 INFO  jTPCC:790 - Term-00, Session finished!
```

2023-08-24 07:55 UTC, daviszhen approved these changes

2023-08-28 02:28 UTC, qingxinhome approved these changes

2023-08-28 03:30 UTC, w-zr approved these changes

2023-09-02 04:04 UTC, fengttt approved these changes

2023-09-13 09:35 UTC, volgariver6 commented
design doc of remote cache in fileservice: https://github.com/matrixorigin/docs/pull/225

2023-09-18 10:37 UTC, sukki37 approved these changes

2023-09-19 02:39 UTC, m-schen approved these changes

2023-09-19 02:39 UTC, merged