Replace most of the cacheData with RCBytes
matrixorigin/matrixone pull request #11325
Opened 2023-08-19 07:28 UTC by nnsgmsone

## What type of PR is this?

- [ ] API-change
- [X] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #10945

## What this PR does / why we need it:
* This pr is the first pr to fix the memory problem, which replaces most of the cachedata with rcbytes
* Change rcbyte from globally shared to one per fileservice

## this PR undo
* metadata still doesn't use rcbytes at the moment, metadata's memory will currently be held by two lru's, the lifecycle is a bit messed up, no fixes at the moment
* Memory allocator and lru are currently still cut off and can't limit the memory size very well

2023-08-19 07:51 UTC, reusee requested changes

2023-08-19 07:51 UTC, reusee commented on pkg/fileservice/rc_bytes.go
> +	return (*[MaxArrayLen]byte)(unsafe.Pointer(ptr))[:size:size]
should use unsafe.Slice((*byte)(unsafe.Pointer(ptr)), size)

2023-08-19 07:51 UTC, reusee commented on pkg/fileservice/rc_bytes.go
> +	}
should be if ptr := unsafe.SliceData(b); ptr != nil { C.free(unsafe.Pointer(ptr)) }

2023-08-19 07:51 UTC, reusee commented on pkg/objectio/funcs.go
> +		CachePolicy: fileservice.SkipMemory,
why skip memory here?

2023-08-19 08:10 UTC, nnsgmsone commented on pkg/fileservice/rc_bytes.go
> +	return (*[MaxArrayLen]byte)(unsafe.Pointer(ptr))[:size:size]
这个应该就是对的用法。。岳声

2023-08-19 08:11 UTC, nnsgmsone commented on pkg/objectio/funcs.go
> +		CachePolicy: fileservice.SkipMemory,
metadata现在缓存了两份阿。。为啥需要两份呢。。。完全没必要的。。两个lru，所以这里跳过了

2023-08-19 08:12 UTC, nnsgmsone commented on pkg/fileservice/rc_bytes.go
> +	}
这个应该就是对的用法。。岳声

2023-08-19 09:21 UTC, LeftHandCold commented on pkg/objectio/funcs.go
> +		CachePolicy: fileservice.SkipMemory,
Here the "skipmemory" parameter should be passed in from the outside

2023-08-22 02:42 UTC, nnsgmsone commented on pkg/fileservice/mem_cache_test.go
> +	assert.Equal(t, int64(0), m.cache.Capacity()-m.cache.Available())
实现的了，唯一的差别是size是使用的rcbytes的size，这样才方便控制内存

2023-08-25 07:20 UTC, reusee requested changes

2023-08-25 07:20 UTC, reusee commented on pkg/fileservice/io_entry.go
> +		e.Data = nil
the caller needs the Data field, so should not be set to nil.

2023-09-19 00:51 UTC, closed without merging