Stats memcache hitrate
matrixorigin/matrixone pull request #11368
Opened 2023-08-21 09:57 UTC by gouhongshen

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #11235 

## What this PR does / why we need it:
adding stats for block read, so we can analyze the mem cache hit info.

2023-08-21 10:03 UTC, aptend approved these changes

2023-08-21 10:31 UTC, reusee approved these changes

2023-08-22 01:21 UTC, fengttt requested changes

2023-08-22 01:21 UTC, fengttt commented on pkg/perfcounter/context.go
> +	allExist := true
what is the expected cost of this loop?    How often we call this, and any expected number of loops?

2023-08-22 06:32 UTC, XuPeng-SH approved these changes

2023-08-22 07:04 UTC, LeftHandCold approved these changes

2023-08-22 07:16 UTC, zhangxu19830126 approved these changes

2023-08-22 12:24 UTC, triump2020 approved these changes

2023-08-23 01:41 UTC, fengttt approved these changes

2023-08-23 02:19 UTC, merged