Fix Gorm migrate issue
matrixorigin/matrixone pull request #11589
Opened 2023-08-31 12:11 UTC by qingxinhome

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #11527
issue #11522

## What this PR does / why we need it:
Solving the gorm migration problem of mo

2023-08-31 12:12 UTC, matrix-meow commented
@qingxinhome Thanks for your contributions!

## Review:

### Title
The title of the pull request is "Fix Gorm migrate issue". The title is concise and provides a clear indication of the purpose of the pull request.

### Body
The body of the pull request includes the following sections:
- "What type of PR is this?" - This section provides checkboxes to indicate the type of pull request. The checkbox for "BUG" is checked, indicating that this is a bug fix.
- "Which issue(s) this PR fixes" - This section lists the issues that this pull request fixes, specifically issue #11527 and issue #11522.
- "What this PR does / why we need it" - This section briefly explains that the pull request solves a Gorm migration problem.

The body of the pull request provides relevant information about the purpose and context of the changes.

### Changes
The changes made in the pull request include modifications to the `mysql_protocol.go`, `session.go`, and `visit_plan.go` files.

In `mysql_protocol.go`, the `authenticateUser` function is modified to include additional parameters: `dbName`, `authResponse`, `salt`, and `checkPassword`. The `authenticateDBName` function is added to authenticate the database name. The commented code block that checks the database name is not removed.

In `session.go`, the `AuthenticateUser` function is modified to include the `dbName` parameter and to authenticate the database name if it is provided. The `AuthenticateDBName` function is added to authenticate the database name.

In `visit_plan.go`, the `exploreNode` function is modified to apply the `rule` to the `OrderBy` expressions.

### Problems
1. Commented code block: In `mysql_protocol.go`, there is a commented code block that checks the database name. This code block should either be removed or uncommented if it is necessary.
2. Unused variables: In `session.go`, the `AuthenticateUser` function includes a variable `txnMeta` that is not used. This variable should be removed to avoid confusion.
3. Lack of comments: The changes made in `session.go` and `visit_plan.go` lack comments explaining the purpose and functionality of the added or modified code. Adding comments would improve the readability and maintainability of the code.

### Suggestions
1. Remove or uncomment the commented code block in `mysql_protocol.go` if it is necessary.
2. Remove the unused variable `txnMeta` in `session.go`.
3. Add comments to explain the purpose and functionality of the added or modified code in `session.go` and `visit_plan.go`.

### Optimization
No specific optimization suggestions are needed for this pull request.

2023-09-01 01:48 UTC, ouyuanning approved these changes

2023-09-01 02:02 UTC, daviszhen requested changes

2023-09-01 02:02 UTC, daviszhen commented on pkg/frontend/mysql_protocol.go
> +	//if dbName := mp.GetDatabaseName(); dbName != "" {
不要就删了吧

2023-09-01 02:02 UTC, daviszhen commented on pkg/frontend/session.go
> +func (ses *Session) AuthenticateDBName(dbName string) error {
这个也是不用的吧。也删了吧。

2023-09-01 02:02 UTC, daviszhen commented on pkg/frontend/mysql_protocol.go
> +func (mp *MysqlProtocolImpl) authenticateDBName(ctx context.Context, authResponse []byte) error {
这个也删了吧。

2023-09-01 02:18 UTC, qingxinhome commented on pkg/frontend/mysql_protocol.go
> +	//if dbName := mp.GetDatabaseName(); dbName != "" {
好的

2023-09-01 02:18 UTC, qingxinhome commented on pkg/frontend/session.go
> +func (ses *Session) AuthenticateDBName(dbName string) error {
好的

2023-09-01 02:18 UTC, qingxinhome commented on pkg/frontend/mysql_protocol.go
> +func (mp *MysqlProtocolImpl) authenticateDBName(ctx context.Context, authResponse []byte) error {
好的

2023-09-01 02:28 UTC, daviszhen approved these changes

2023-09-01 03:04 UTC, heni02 approved these changes

2023-09-01 03:09 UTC, aressu1985 approved these changes

2023-09-01 07:56 UTC, merged