Add LOAD INTO VALUES
matrixorigin/matrixone pull request #11633
Opened 2023-09-05 02:35 UTC by nnsgmsone

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [X] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #9955

## What this PR does / why we need it:
Provide a quick way to insert data, a rough example is as follows:
```sql
load data  inline format='csv', data='1\n2\n' into table t1;
```

2023-09-05 02:45 UTC, ouyuanning approved these changes

2023-09-05 02:58 UTC, iamlinjunhong approved these changes

2023-09-05 03:15 UTC, m-schen approved these changes

2023-09-05 03:59 UTC, aunjgr approved these changes

2023-09-05 08:11 UTC, fengttt requested changes
Need more tests.

Esp data with ' in it.    Make sure quote works.    Make sure `$XXX$` syntax works.
```
$XXX$ 
one line
another line
$XXX$ 
```

2023-09-05 09:20 UTC, fengttt commented
> 
···
load data  inline format='csv', data=$XXX$
1
2
$XXX$ 
into table t1;

2023-09-05 09:25 UTC, nnsgmsone commented
没有'吗。。不是下面这样吗?
```
load data  inline format='csv', data='$XXX$
1
2
$XXX$' 
into table t1;
```
@fengttt

2023-09-06 01:32 UTC, fengttt approved these changes

2023-09-06 01:54 UTC, merged