change runtime filter threshold of in predicate to 10240 from 1024
matrixorigin/matrixone pull request #11631
Opened 2023-09-05 01:13 UTC by badboynt1

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:
make runtime filter for q18 on tpch 1T work

2023-09-05 01:50 UTC, fengttt requested changes
Explain to me that this change will work for TPCH 1G to 1T to 1P.

2023-09-05 03:02 UTC, aunjgr approved these changes

2023-09-06 08:50 UTC, daviszhen requested changes

2023-09-06 08:50 UTC, daviszhen commented on pkg/sql/colexec/hashbuild/build.go
> +	v, ok := runtime.ProcessLevelRuntime().GetGlobalVariables("runtime_filter_limit_in")
需要在某个地方 SetGlobalVariables。这里面的全局变量跟session是没有直接关联的。
需要在某个地方，将两者关联起来

2023-09-06 09:44 UTC, badboynt1 commented on pkg/sql/colexec/hashbuild/build.go
> +	v, ok := runtime.ProcessLevelRuntime().GetGlobalVariables("runtime_filter_limit_in")
fixed

2023-09-06 10:17 UTC, daviszhen approved these changes

2023-09-06 10:30 UTC, m-schen approved these changes

2023-09-06 13:47 UTC, fengttt approved these changes

2023-09-06 16:25 UTC, merged