Gc partition state
matrixorigin/matrixone pull request #11689
Opened 2023-09-07 07:29 UTC by jiangxinmeng1

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #11613

## What this PR does / why we need it:

现在CN不会gc logtail，如果CN会一直订阅一张表，这张表的logtail会无限增长。本PR会GC CN 内存中的logtail：

1. GC partition state中的block及index

   每当有block被删除，CN会收到metadata相关的logtail。CN只是逻辑删除这些block，它们依然占用内存。这个PR里，等block被逻辑删除超过`1h`，就会物理删除它们。

2. 增加后台任务partitionStateGCTicker

   `partitionStateGCTicker`每`20min`扫描一次CN中所有的partition state，GC block及其索引。

3. 取block list的时候检查timestamp

    新的事务带着SnapshotTS向partition state取block list，SnapshotTS控制可见性。如果SnapshotTS小于gc过的TS，partition state中可能有些block，本该被这个事务看见，但已经被GC了。CN不能服务这样的事务，会返回错误`TxnStale`。

2023-09-07 08:36 UTC, zhangxu19830126 approved these changes

2023-09-11 02:45 UTC, reusee requested changes

2023-09-11 02:45 UTC, reusee commented on pkg/vm/engine/disttae/logtailreplay/partition.go
> +		p.Unlock()
Unlock should only be called when Lock returns nil.

2023-09-11 02:45 UTC, reusee commented on pkg/vm/engine/disttae/logtailreplay/partition.go
> +	}
should put `defer p.Unlock()` here.

2023-09-11 02:45 UTC, reusee commented on pkg/vm/engine/disttae/logtailreplay/partition_state.go
> +	minTS atomic.Pointer[types.TS]
this field should be types.TS and never be modified. The PartitionState is immutable.

2023-09-11 02:45 UTC, reusee commented on pkg/vm/engine/disttae/logtailreplay/partition_state.go
> +func (p *PartitionState) truncate(ids [2]uint64, ts types.TS) {
This method should be moved to Partition. And never modify a PartitionState, copy and modify instead. See Partition.ConsumeCheckpoints and Partition.Mutate for how to do modifications.

2023-09-11 06:56 UTC, reusee requested changes

2023-09-11 06:56 UTC, reusee commented on pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
> +func (p *PartitionState) NewBlocksIter(ts types.TS, tid uint64) (*blocksIter, error) {
if the tid param is not used, delete it.

2023-09-11 06:57 UTC, reusee approved these changes

2023-09-13 03:13 UTC, XuPeng-SH approved these changes

2023-09-14 11:25 UTC, merged