fix issue 11960
matrixorigin/matrixone pull request #12055
Opened 2023-10-10 12:06 UTC by Morranto

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #11960

## What this PR does / why we need it:

please check the issue 11960

2023-10-11 02:04 UTC, ouyuanning commented
you can add some bvt test

2023-10-11 02:05 UTC, ouyuanning requested changes
add some bvt test

2023-10-12 10:02 UTC, ouyuanning approved these changes

2023-10-12 13:44 UTC, heni02 approved these changes

2023-10-12 14:15 UTC, merged