feat: support dump multiple databases
matrixorigin/matrixone pull request #12177
Opened 2023-10-18 08:01 UTC by xmh1011

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #10094 

## What this PR does / why we need it:

2023-10-19 02:02 UTC, YANGGMM approved these changes

2023-10-19 02:14 UTC, zhangxu19830126 approved these changes

2023-10-19 15:59 UTC, xmh1011 commented
Why this pr can't be merged automatically?

2023-10-19 16:07 UTC, xmh1011 commented
@Mergifyio refresh

2023-10-25 06:17 UTC, daviszhen requested changes

2023-10-25 06:17 UTC, daviszhen commented on cmd/mo-dump/main.go
> -	if len(tables) == 0 { //dump all tables
把导出的逻辑单独做为一个函数。与`openDBConnection`单独分开。不用搬来搬去了。

2023-10-25 06:17 UTC, daviszhen commented on cmd/mo-dump/main.go
> +		}
见下面的评论。

2023-10-25 13:29 UTC, xmh1011 commented on cmd/mo-dump/main.go
> -	if len(tables) == 0 { //dump all tables
已经导出，请审阅 @daviszhen

2023-10-30 03:59 UTC, qingxinhome approved these changes

2023-10-31 08:52 UTC, daviszhen requested changes

2023-10-31 08:52 UTC, daviszhen commented on cmd/mo-dump/main.go
> +		conn, err = opt.openDBConnection(ctx, db)
导出的数据的过程，只需要一个dbConnection。不同dbConnection干的事情差不多。无非db和table 不同。

2023-10-31 08:52 UTC, daviszhen commented on cmd/mo-dump/main.go
> +		conn, err = opt.openDBConnection(ctx, db)
`conn`是个全局变量。直接复用就行了。

2023-11-06 04:48 UTC, xmh1011 commented on cmd/mo-dump/main.go
> +		conn, err = opt.openDBConnection(ctx, db)
@daviszhen

2023-11-07 12:10 UTC, daviszhen requested changes

2023-11-07 12:10 UTC, daviszhen commented on cmd/mo-dump/main.go
> +	conn, err = opt.openDBConnection(ctx, opt.dbs[0])
如果上面是"all"的话，conn又重新创建了。这地方要判断conn是否已经被创建过。有了就复用。

2023-11-08 05:02 UTC, xmh1011 commented on cmd/mo-dump/main.go
> +	conn, err = opt.openDBConnection(ctx, opt.dbs[0])
@daviszhen

2023-11-17 03:32 UTC, daviszhen approved these changes

2023-11-17 04:33 UTC, merged