feat: support dump multiple tables
matrixorigin/matrixone pull request #12182
Opened 2023-10-18 13:19 UTC by xmh1011

## What type of PR is this?

- [x] Feature

## Which issue(s) this PR fixes:

issue #10094 

## What this PR does / why we need it:

2023-10-19 02:02 UTC, YANGGMM approved these changes

2023-10-19 02:10 UTC, daviszhen requested changes

2023-10-19 02:10 UTC, daviszhen commented on cmd/mo-dump/main.go
> +		tables = make([]Table, len(tbls))
要处理tbls[i]为空串的情况。

2023-10-19 02:13 UTC, zhangxu19830126 approved these changes

2023-10-19 03:29 UTC, xmh1011 commented on cmd/mo-dump/main.go
> +		tables = make([]Table, len(tbls))
我已修改，请检查。

2023-10-19 16:05 UTC, xmh1011 commented on cmd/mo-dump/main.go
> +		tables = make([]Table, len(tbls))
@daviszhen

2023-10-25 06:13 UTC, daviszhen approved these changes

2023-10-25 09:35 UTC, merged