[Bug] : Fix CSV Export for Vector Type
matrixorigin/matrixone pull request #12253
Opened 2023-10-20 21:08 UTC by arjunsk

## What type of PR is this?

- [ ] API-change
- [X] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #  https://github.com/matrixorigin/matrixone/issues/11446

## What this PR does / why we need it:

This is a sub-task of https://github.com/matrixorigin/matrixone/issues/10633. With this PR, we should be able to export Vector Types in CSV.

- SQL
```sql
create table vec_table(a int, b vecf32(3), c vecf64(3));

load data infile '/Users/usr/ide/matrixone/test/distributed/resources/array/array_out.csv' into table vec_table ignore 1 lines;

select * from vec_table;
+------+-----------+-----------+
| a    | b         | c         |
+------+-----------+-----------+
|    1 | [1, 2, 3] | [4, 5, 6] |
+------+-----------+-----------+

```

- CSV file
```csv
a,b,c
1,"[1, 2, 3]","[4, 5, 6]"
```

2023-10-23 03:28 UTC, daviszhen requested changes
modump also needs exporting the vector type.
in `cmd/mo-dump`

2023-10-23 04:52 UTC, arjunsk commented
> modump also needs exporting the vector type. in `cmd/mo-dump`

Hi @daviszhen , I have made the necessary changes. The output of modump is updated in the description of the PR.

2023-10-23 07:15 UTC, nnsgmsone approved these changes

2023-10-23 07:20 UTC, XuPeng-SH approved these changes
lgtm

2023-10-23 09:23 UTC, aressu1985 approved these changes

2023-10-23 23:48 UTC, zhangxu19830126 approved these changes

2023-10-24 01:58 UTC, daviszhen approved these changes

2023-10-24 03:09 UTC, m-schen approved these changes

2023-10-24 04:31 UTC, merged