the refactor of collecting accounts' storage usage info
matrixorigin/matrixone pull request #12315
Opened 2023-10-24 11:11 UTC by gouhongshen

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #11480

## What this PR does / why we need it:
1.

2023-10-27 02:52 UTC, xzxiong commented on pkg/util/export/example/main.go
> -// If you want to run this code, you need some source data, that could copy from folder `mo-data/etl/sys/logs/...`, which generated by mo-service startup with config `etc/launch-tae-logservice`
这个文件不用动吧？修改似乎没有必要

2023-10-27 02:52 UTC, xzxiong approved these changes

2023-10-27 02:58 UTC, gouhongshen commented on pkg/util/export/example/main.go
> -// If you want to run this code, you need some source data, that could copy from folder `mo-data/etl/sys/logs/...`, which generated by mo-service startup with config `etc/launch-tae-logservice`
这个是 IDE 改动了的，我修改回来了

2023-10-27 03:13 UTC, aptend requested changes

2023-10-27 03:13 UTC, aptend commented on pkg/vm/engine/tae/catalog/segment.go
> +	s.RLock()
s.Lock()

2023-10-27 03:13 UTC, aptend commented on pkg/vm/engine/tae/catalog/segment.go
> +	if name == motrace.RawLogTbl && s.originSize == 0 && s.rows != 0 {
逻辑不对了，跳过 load 后不会再预估 object 大小

2023-10-27 03:30 UTC, zhangxu19830126 approved these changes

2023-10-27 03:30 UTC, gouhongshen commented on pkg/vm/engine/tae/catalog/segment.go
> +	s.RLock()
OK，有几个都改了

2023-10-27 05:03 UTC, gouhongshen commented on pkg/vm/engine/tae/catalog/segment.go
> +	if name == motrace.RawLogTbl && s.originSize == 0 && s.rows != 0 {
第一次 load 应该会做这件事

2023-10-27 08:21 UTC, qingxinhome approved these changes

2023-10-27 08:23 UTC, m-schen approved these changes

2023-10-27 08:37 UTC, gouhongshen commented on pkg/objectio/metav2.go
should be 26+2

2023-10-27 08:55 UTC, daviszhen requested changes

2023-10-27 08:55 UTC, daviszhen commented on pkg/frontend/show_account.go
> +		"cast(0 as double) as `size_in_mb` " +
列名不要改，保持`size`。之前跟产品约定好的。其它列名同样不要改。

2023-10-27 08:55 UTC, daviszhen commented on pkg/frontend/show_account.go
> +	//	"( select " +
不要就直接删掉。

2023-10-27 08:55 UTC, daviszhen commented on pkg/frontend/show_account.go
> +		if _, ses.proc.TxnOperator, err = ses.TxnCreate(); err != nil {
取新事物。不要用txnCreate。用`func (th *TxnHandler) GetTxn()`。这么用`ses.txnHandler.GetTxn`，参照其它地方的用法。

2023-10-27 08:55 UTC, daviszhen commented on pkg/frontend/show_account.go
> +	if ses.proc.TxnOperator == nil {
下面的163行到170行。用ses.txnHandler.GetTxn替换。参考其他地方用法。

2023-10-27 08:55 UTC, daviszhen commented on pkg/frontend/show_account.go
> +		//err = outputBatch.Vecs[finalIdxOfRowCount].UnionOne(bat.Vecs[idxOfRowCount], 0, mp)
删掉

2023-10-27 09:10 UTC, LeftHandCold approved these changes

2023-10-27 09:54 UTC, gouhongshen commented on pkg/frontend/show_account.go
> +		"cast(0 as double) as `size_in_mb` " +
好的

2023-10-27 10:45 UTC, gouhongshen commented on pkg/vm/engine/tae/catalog/segment.go
> +	if name == motrace.RawLogTbl && s.originSize == 0 && s.rows != 0 {
已更新

2023-10-27 10:46 UTC, gouhongshen commented on pkg/frontend/show_account.go
> +		"cast(0 as double) as `size_in_mb` " +
已更新

2023-10-27 10:46 UTC, gouhongshen commented on pkg/frontend/show_account.go
> +	//	"( select " +
已更新

2023-10-27 10:46 UTC, gouhongshen commented on pkg/frontend/show_account.go
> +		if _, ses.proc.TxnOperator, err = ses.TxnCreate(); err != nil {
已更新

2023-10-27 10:46 UTC, gouhongshen commented on pkg/frontend/show_account.go
> +	if ses.proc.TxnOperator == nil {
已更新

2023-10-27 10:46 UTC, gouhongshen commented on pkg/frontend/show_account.go
> +		//err = outputBatch.Vecs[finalIdxOfRowCount].UnionOne(bat.Vecs[idxOfRowCount], 0, mp)
已更新

2023-10-27 10:48 UTC, aptend approved these changes

2023-10-30 02:30 UTC, triump2020 approved these changes

2023-10-31 08:32 UTC, jiangxinmeng1 approved these changes

2023-10-31 10:27 UTC, XuPeng-SH approved these changes

2023-10-31 13:48 UTC, daviszhen approved these changes

2023-11-01 06:55 UTC, merged