[enhancement] proxy: reduce some log messages.
matrixorigin/matrixone pull request #12455
Opened 2023-11-01 04:44 UTC by volgariver6

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:
Too many error logs which are not error level, so do not log these logs.

2023-11-01 04:58 UTC, fengttt requested changes
Is this NotSafeToStartTransfer a real error?   If it is not, let's put it in the OK Group.   OK group is the least resource consuming group.

2023-11-02 02:21 UTC, zhangxu19830126 approved these changes

2023-11-02 02:35 UTC, volgariver6 commented
> Is this NotSafeToStartTransfer a real error? If it is not, let's put it in the OK Group. OK group is the least resource consuming group.

modified.

2023-11-02 02:53 UTC, fengttt approved these changes

2023-11-04 14:20 UTC, merged