[Perf]: Improve query plan for "delete from TABLE_NAME" without any conditions
matrixorigin/matrixone pull request #12744
Opened 2023-11-15 02:35 UTC by noorall

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #12515

## What this PR does / why we need it:
When executing the DELETE without condition, the join operation on auxiliary tables is removed, and table locks are used to reduce the cost of locking.

2023-11-15 02:42 UTC, ouyuanning reviewed
better to add some BVT case.
eg:
delete normal table with/without where
delete table with unique key, 2nd key, foreign key with/without where
delete multi tables with/without where

2023-11-15 02:47 UTC, ouyuanning commented on pkg/sql/plan/build_delete.go
> +	isDeleteWithoutFilters := stmt.Where == nil && len(tblInfo.tableDefs) == 1
should like:
isDeleteWithoutFilters := !tblInfo.isMulti && stmt.Where == nil && stmt.Limit == nil

2023-11-15 03:11 UTC, noorall commented
> better to add some BVT case. eg: delete normal table with/without where delete table with unique key, 2nd key, foreign key with/without where delete multi tables with/without where

added

2023-11-15 09:08 UTC, ouyuanning requested changes
have some bug for delete big data. need fixed

2023-11-16 00:19 UTC, ouyuanning commented on test/distributed/cases/dml/delete/delete.test
> +
增加几个用例吧
1、有外键的情况
2、有limit 子句的
3、200W数据的表
```
create table t1(a int primary key, b int unique key, c varchar(20) unique key);
insert into t1 select result, result, "a"||result from generate_series(1,2000000) g;
```

2023-11-17 06:16 UTC, noorall commented
@aressu1985 @heni02 Please review the test code.

2023-11-17 06:18 UTC, ouyuanning approved these changes

2023-11-20 02:02 UTC, aressu1985 approved these changes

2023-11-20 03:07 UTC, merged