fileservice: use direct io in disk cache read
matrixorigin/matrixone pull request #13028
Opened 2023-11-28 02:48 UTC by reusee

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #13010 

## What this PR does / why we need it:

2023-11-28 03:00 UTC, zhangxu19830126 approved these changes

2023-12-16 21:56 UTC, fengttt requested changes
This must be param/config controlled that we can turn on and off.

2023-12-16 21:57 UTC, fengttt commented
> This must be param/config controlled that we can turn on and off.

And it must have a perf number run if you want to turn it on by default.

2023-12-17 14:39 UTC, reusee commented
stall for too long, I will resend the PR later. closing.

2023-12-17 14:39 UTC, closed without merging