[perf] improve delete plan from table without where & limit
matrixorigin/matrixone pull request #13120
Opened 2023-11-30 03:59 UTC by noorall

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #12845

## What this PR does / why we need it:
When a table does not have a foreign key. So for delete from table, it can be optimized to truncate.

2023-12-04 03:48 UTC, nnsgmsone requested changes
这应该是个不合理的改法，应该一个优化器规则，几十行代码就可以处理这个问题

2023-12-04 07:11 UTC, aunjgr approved these changes

2023-12-07 01:43 UTC, nnsgmsone reviewed
做成优化器的规则如何呢。而不是物理计划的一个if else

2023-12-07 01:56 UTC, ouyuanning commented on pkg/sql/compile/compile.go
> +	case plan.Node_DELETE_BY_TRUNCATE:
好像不用增加node type也可以。
在compile的时候，在处理node_type是delete的时候，如果是can truncate是true，就用你现在这个地方就好了。

2023-12-07 03:31 UTC, noorall commented on pkg/sql/compile/compile.go
> +	case plan.Node_DELETE_BY_TRUNCATE:
已修改

2023-12-07 03:42 UTC, noorall commented
> 做成优化器的规则如何呢。而不是物理计划的一个if else

现在的ddl不是一个算子的形式，ddl的参数直接从plan中获取，这个if else应该没办法避免

2023-12-10 14:01 UTC, merged