handle cancel query takes very long
matrixorigin/matrixone pull request #13172
Opened 2023-12-01 23:53 UTC by qingxinhome

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #12324

## What this PR does / why we need it:
handle issue iof cancel query takes very long

2023-12-05 07:06 UTC, fengttt requested changes
First ask Zhang Xu to review this.   Need his approval.

Second, where should we add this code?   Do we know if there are any missing places?

2023-12-05 07:08 UTC, m-schen requested changes
只需要在数据的源头(各种scan)做这个检查就行了，不需要修改这些算子。

目前各种scan的判断是不对的，在查询开始后就无法关闭查询了，应该放在循环里头。
详见：
https://github.com/matrixorigin/matrixone/blob/main/pkg/sql/colexec/table_scan/table_scan.go#L46

应该还有其他scan算子，这部分逻辑需要一并修改。

2023-12-05 07:16 UTC, m-schen commented
> 只需要在数据的源头(各种scan)做这个检查就行了，不需要修改这些算子。
> 
> 目前各种scan的判断是不对的，在查询开始后就无法关闭查询了，应该放在循环里头。 （判断在38行，循环在46行开始） 详见： https://github.com/matrixorigin/matrixone/blob/main/pkg/sql/colexec/table_scan/table_scan.go#L46
> 
> 应该还有其他scan算子，这部分逻辑需要一并修改。

每次调用一次call的话似乎也不应该有问题，不过修改的算子应该尽量地少。
可能刚好卡死在某一次read上了，我不能肯定。
不过在源头解决这个问题是比较合理的，每个算子都加的话容易遗漏。

2023-12-05 20:30 UTC, fengttt commented
> > 只需要在数据的源头(各种scan)做这个检查就行了，不需要修改这些算子。
> > 目前各种scan的判断是不对的，在查询开始后就无法关闭查询了，应该放在循环里头。 （判断在38行，循环在46行开始） 详见： https://github.com/matrixorigin/matrixone/blob/main/pkg/sql/colexec/table_scan/table_scan.go#L46
> > 应该还有其他scan算子，这部分逻辑需要一并修改。
> 
> 每次调用一次call的话似乎也不应该有问题，不过修改的算子应该尽量地少。 针对该issue可能刚好卡死在某一次read或者某次排序上了，我不能肯定。
> 
> 不过在源头解决这个问题是比较合理的， （只修改scan 或者 只修改每个pipeline最起始的算子 scan + 各种带有merge功能的算子 ？） 每个算子都加的话容易遗漏。

Please consider the following, add a method to proc, CheckForCancel.  In the method,
we do select/context etc etc, and if it is cancelled, panic with a UserCancel error.

Call this CheckForCancel in the right place.   Usually a tight loop that processes lots of data.   Maybe in each expensive operator.   All kinds of scan and join maybe a good starting point.    

Scoperun should caught this panic and handle.

2023-12-06 19:44 UTC, fengttt approved these changes

2023-12-07 07:13 UTC, qingxinhome commented
> 只需要在数据的源头(各种scan)做这个检查就行了，不需要修改这些算子。
> 
> 目前各种scan的判断是不对的，在查询开始后就无法关闭查询了，应该放在循环里头。 （判断在38行，循环在46行开始） 详见： https://github.com/matrixorigin/matrixone/blob/main/pkg/sql/colexec/table_scan/table_scan.go#L46
> 
> 应该还有其他scan算子，这部分逻辑需要一并修改。

这个地方和远宁确认一下，Table_scan并不是阻塞类算子，它的Call方法里面的for循环只要取到一个block块就会结束循环，所以不用放在for循环内部检查 @m-schen

2023-12-07 08:33 UTC, m-schen commented
我想了一下，我之前的评论是不正确的。
只在某些算子，无论是什么算子增加该检测，都是治标不治本的。

因为目前的执行逻辑为：

例如某pipeline的算子为：a -> b -> c -> d 

框架首先调用d的执行方法，间接地按顺序执行c,b,a的代码。这样是一轮计算。在本轮计算结束后，感知查询的状态是否为stop, 如果是则停止该执行，返回结果。

这里的问题在于，无论哪个算子感知了上下文的结束，并打上stop的标签。都需要等到该轮查询完整地执行结束再停止查询。因此即使在a, b, c, d算子均加上感知结束的逻辑，也只是跳过该轮计算，而并非直接结束查询。
而我们无法保证当cancel query的时候，代码运行到了什么算子，如果该算子没有增加该检测，我们就无法规避它的本次完整计算，假设它是一个大量计算表达式 / 排序 等需要较多时间的算子，那么就会导致需要一定时间才能关闭本次查询。

我感觉要么得所有算子全加，要么得由执行框架在调用每个算子的call方法前检查上下文是否已经结束才能解决该问题。

2023-12-07 09:17 UTC, m-schen commented
> 我想了一下，我之前的评论是不正确的。 只在某些算子，无论是什么算子增加该检测，都是治标不治本的。
> 
> 因为目前的执行逻辑为：
> 
> 例如某pipeline的算子为：a -> b -> c -> d
> 
> 框架首先调用d的执行方法，间接地按顺序执行c,b,a的代码。这样是一轮计算。在本轮计算结束后，感知查询的状态是否为stop, 如果是则停止该执行，返回结果。
> 
> 这里的问题在于，无论哪个算子感知了上下文的结束，并打上stop的标签。都需要等到该轮查询完整地执行结束再停止查询。因此即使在a, b, c, d算子均加上感知结束的逻辑，也只是跳过该算子的本轮计算，而并非直接结束查询。 而我们无法保证当cancel query的时候，代码运行到了什么算子，如果该算子没有增加该检测，我们就无法规避它的本次完整计算，假设它是一个大量计算表达式 / 排序 等需要较多时间的算子，那么就会导致需要一定时间才能关闭本次查询。
> 
> 我感觉要么得所有算子全加，要么得由执行框架在调用每个算子的call方法前检查上下文是否已经结束，如果是则结束自身整条pipeline，才能解决该问题。

感觉要么就都加，细化到算子粒度的结束（因为投影算子、过滤算子等事实上也是计算的大头，耗时可能也比较久）。要么就加首尾算子，一轮计算为单位的结束。
粒度再变小的话对性能影响就很大了，不能再小了的。

2023-12-14 04:08 UTC, closed without merging