[Refactor] : use fuzzy filter to do primary/unique key constraint check with performance compare
matrixorigin/matrixone pull request #13433
Opened 2023-12-13 07:55 UTC by jensenojs

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #10655, #12846

BUG ISSUE 相关的主要是类似insert into select * from 导致的oom : MOC#1574, MOC#1082, MOC#1631

## What this PR does / why we need it:

doc link and pprof compare : https://github.com/matrixorigin/docs/pull/261

2023-12-13 10:58 UTC, jensenojs commented
之前的fuzzy filter没有支持runtime filter, 因此在某些场景下会比main慢得多, 现在先把最影响fuzzy filter性能的一些优化给做了, 追平main先, 后续再接着优化. 附上fuzzy和main的性能测试对比, 详细的数据对比得明天出

# data_insert的方式导入用户数据 (most important)

这个测试是最具有对比意义的

托豪朗哥的的忙, 陆续将用户数据中所有足够大的一些表的对比数据收集齐全了, 基本都拉平main或者略优于main, 双合001的例子比较特殊, 它insert values的batch_size在一万四上下, 此时的main无法使用pkfilter或者是runtime filter, 但是那张大表的主键类型是bigint, 实践发现它做常量折叠的开销远小于varchar类型的主键, 所以fuzzy会比main快, 严格来说这个测试不太算.其余数据差距不明显是因为次级索引进来之后主键去重的耗时不再成为主要瓶颈

|              | main       | fuzzy      |
| ------------ | ---------- | ---------- |
| shaunghe_001 | 78m38.365s | 49m42.235s |
| slooong_001  | 19.674s    | 19.904s    |
| slooong_003  | 16m17.041s | 15m44.330s |
| unre_001     | 4m43.005s  | 4m31.193s  |
| unre_004     | 12m44.468s | 13m59.820s |
| dmt_001      | 36.303s    | 37.487s    |
| etao_001     | 9m5.715s   | 8m48.266s  |

# 亿规模的导入

2023-12-15 05:57 UTC, ouyuanning requested changes

2023-12-15 05:57 UTC, ouyuanning commented on pkg/sql/colexec/fuzzyfilter/filter.go
> +				// fmt.Println("probe cnt = ", arg.probeCnt)
这里的rbat是不是都是nil？

2023-12-15 05:57 UTC, ouyuanning commented on proto/plan.proto
> +	string parent_tbl_name  = 9;
这个和parent_unique_cols好像没有被用到？

2023-12-15 05:57 UTC, ouyuanning commented on pkg/sql/plan/runtime_filter.go
> -	// Build runtime filters only for broadcast join
这个PR应该不涉及到这个文件，建议还原回去

2023-12-15 06:25 UTC, jensenojs commented on pkg/sql/colexec/fuzzyfilter/filter.go
> +				// fmt.Println("probe cnt = ", arg.probeCnt)
已修改

2023-12-15 06:36 UTC, jensenojs commented on proto/plan.proto
> +	string parent_tbl_name  = 9;
用到了的, unique index所创建的隐藏表需要通过它拿到原表数据中对应咧的ColDef, 需要ColDef的原因是对于Decimal type类型, 需要从Def中获取其精度信息

https://github.com/jensenojs/matrixone/blob/fuzzyFilter/pkg/sql/plan/build_dml_util.go#L950

2023-12-15 10:38 UTC, jensenojs commented on proto/plan.proto
> +	string parent_tbl_name  = 9;
经讨论, 把plan.tableDef中的属性值挪到plan.Node中

2023-12-16 05:28 UTC, ouyuanning approved these changes

2023-12-18 06:20 UTC, m-schen approved these changes

2023-12-18 06:28 UTC, badboynt1 approved these changes

2023-12-18 06:34 UTC, jensenojs commented
接下来要做的事情至少有这么几个 : 

# 两件不太小的事:

在主键去重上, 我们现在大体上有两个过滤手段, 一个是pkfilter, 一个是runtime filter, 前者是直接把要插入的值的表达式推给存储, 后者是在执行的过程中过滤, pkfilter应该更准一些, 但是像`insert into t select * from xxx`的SQL就没法用, 只能用runtime filter

对于insert into values这种SQL的values个数, main是超过1024的时候，就走runtime filter, 否则直接走pkfilter. , 现在的runtime filter 好像只支持in表达式且上限是一万, 所以在面向insert values 的batch size大于一万的时候, 实际上没有任何的filter手段, 虽然有probe阶段的并行, 但是仍需要读全表. 

1. 实践发现ConstantFold对于类型敏感, 具体是指在varchar为主键或者复合主键时开销大得离谱, 但是在BIGINT作为主键下的折叠却几乎没有开销, 这里需要研究一下是怎么回事...
2. runtime filter 本身也可以/应该用 bloom filter 来做

# 两件小事 : 
1. 现在的value scan的统计信息数据并没有打开(在ReCalNodeStats)中, 所以value scan的统计值拿给fuzzy 的时候一直是默认值, 现在是把下限调至十万来规避了这个问题, 不知道有issue跟踪这个没.
2. 现在的IN表达式还不支持复合主键, 等后续支持了fuzzyCheck在组装后台SQL相关的代码能重构掉一大片.

2023-12-18 11:14 UTC, zhangxu19830126 approved these changes

2023-12-19 01:27 UTC, nnsgmsone approved these changes

2023-12-19 02:45 UTC, XuPeng-SH approved these changes

2023-12-19 03:10 UTC, heni02 approved these changes

2023-12-19 08:49 UTC, merged