Relate frontend query and background session query
matrixorigin/matrixone pull request #13436
Opened 2023-12-13 08:08 UTC by xzxiong

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #13384

## What this PR does / why we need it:
changes:
1. reset backgroud session id as frontend query's statement id.
2. reset fronted query's txn-id if the txn-id is non-setted, by using background session txn-id
    - default skip the background transaction, which DO check privileges. 
3. fix stmt reset while do free
4. improve statement aggr logic, if all aggr stmts in the same txn, not reset the txn-id. @gavinyue

2023-12-13 08:10 UTC, xzxiong commented on pkg/frontend/authenticate.go
> +		//USE the mo_catalog
@daviszhen 看下这里，我挪了下位置。为了保证仅 “一个事务”。

2023-12-13 08:15 UTC, daviszhen requested changes

2023-12-13 08:15 UTC, daviszhen commented on pkg/frontend/mysql_cmd_executor.go
> +			_, txn, err = handler.GetTxn()
如果上面isValidOperator为true，用GetTxnOperator接口。

2023-12-13 08:15 UTC, daviszhen commented on pkg/util/trace/impl/motrace/report_statement.go
> -	s.FreeExecPlan()
确定要删吗?

2023-12-13 09:13 UTC, xzxiong commented on pkg/util/trace/impl/motrace/report_statement.go
> -	s.FreeExecPlan()
statement_info 对 ExecPlan是只读的，execPlan的生命周期是由 frontend 管理。

2023-12-13 09:21 UTC, xzxiong commented on pkg/util/trace/impl/motrace/report_statement.go
> -	s.FreeExecPlan()
另外，这个调用并没有去掉。代码移动了 [L343](https://github.com/matrixorigin/matrixone/pull/13436/files#diff-6bb6c3e48a06b6a752b1a028ea13f3f2973f20039dcbce2759e65cf30e50da2aR343)

2023-12-14 09:25 UTC, daviszhen approved these changes

2023-12-15 06:50 UTC, merged