Relate frontend query and background session query, v1.1
matrixorigin/matrixone pull request #13435
Opened 2023-12-13 08:04 UTC by xzxiong

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #13384

## What this PR does / why we need it:
changes:
1. reset backgroud session id as frontend query's statement id.
2. reset fronted query's txn-id if the txn-id is non-setted, by using background session txn-id
    - default skip the background transaction, which DO check privileges. 
3. fix stmt reset while do free
4. improve statement aggr logic, if all aggr stmts in the same txn, not reset the txn-id. @gavinyue

2023-12-13 08:16 UTC, daviszhen requested changes

2023-12-13 08:16 UTC, daviszhen commented on pkg/frontend/mysql_cmd_executor.go
> +			_, txn, err = handler.GetTxn()
同样的

2023-12-13 09:19 UTC, xzxiong commented on pkg/frontend/mysql_cmd_executor.go
> +			_, txn, err = handler.GetTxn()
已修改

2023-12-14 09:25 UTC, daviszhen approved these changes

2023-12-15 18:19 UTC, merged

2023-12-19 06:09 UTC, xzxiong commented
ref https://github.com/matrixorigin/MO-Cloud/issues/2001