fix group concat (#13700)
matrixorigin/matrixone pull request #13784
Opened 2023-12-25 10:05 UTC by Morranto

fix group concat

Approved by: @ouyuanning, @m-schen, @iamlinjunhong

(cherry picked from commit b3d0d6c2c72470c807e295f8439a7bdcdd3f28de)

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #13273  13272  

## What this PR does / why we need it:

fix group concat bug

2023-12-25 10:07 UTC, ouyuanning approved these changes

2023-12-25 10:16 UTC, m-schen approved these changes

2023-12-26 01:59 UTC, sukki37 approved these changes

2023-12-26 02:01 UTC, sukki37 requested changes
fix build problem

2023-12-26 10:22 UTC, sukki37 approved these changes

2023-12-26 11:18 UTC, merged