Some improvements to publish-subscribe
matrixorigin/matrixone pull request #14005
Opened 2024-01-04 06:47 UTC by ck89119

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue https://github.com/matrixorigin/matrixone/issues/9675

## What this PR does / why we need it:
Some improvements to publish-subscribe

2024-01-08 02:57 UTC, daviszhen requested changes

2024-01-08 02:57 UTC, daviszhen commented on pkg/frontend/show_subsriptions.go
> +				name:       "pub_name",
字段名称 要 产品和云平台 对清楚。避免上线后，云平台不能用。

2024-01-08 02:57 UTC, daviszhen commented on pkg/frontend/show_subsriptions.go
> +			oq := NewOutputQueue(ses.GetRequestContext(), ses, len(batch.Vecs), nil, nil)
换成 newFakeOutputQueue ，更简单。
其它类似。

2024-01-08 10:30 UTC, m-schen approved these changes

2024-01-08 10:55 UTC, iamlinjunhong approved these changes

2024-01-09 02:30 UTC, aressu1985 approved these changes

2024-01-09 10:06 UTC, reusee approved these changes

2024-01-09 10:09 UTC, nnsgmsone approved these changes

2024-01-09 11:44 UTC, daviszhen approved these changes

2024-01-10 02:44 UTC, ouyuanning approved these changes

2024-01-10 03:06 UTC, aunjgr approved these changes

2024-01-13 13:12 UTC, merged