GC Adapt Object
matrixorigin/matrixone pull request #14360
Opened 2024-01-25 01:47 UTC by LeftHandCold

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue https://github.com/matrixorigin/MO-Cloud/issues/1415 https://github.com/matrixorigin/MO-Cloud/issues/1424

## What this PR does / why we need it:
GC Adapt Object

2024-02-06 06:21 UTC, fengttt requested changes

2024-02-06 06:21 UTC, fengttt commented on pkg/vm/engine/tae/db/gc/entry.go
> +	if len(o.table.blocks) > 0 {
You mean here we do not add the block if o.table.blocks > 0?

2024-02-16 02:25 UTC, LeftHandCold commented on pkg/vm/engine/tae/db/gc/entry.go
> +	if len(o.table.blocks) > 0 {
这样处理是因为1.1增加了object list把block去掉了，但是现在gc的逻辑还是沿用之前消费block list的逻辑。为了在gc重构前简单快速的让其正常工作，所以把object当作block来消费，可以看作成一个object只有一个block的设计。

2024-02-19 03:59 UTC, XuPeng-SH approved these changes

2024-02-19 04:09 UTC, fengttt approved these changes

2024-02-19 08:47 UTC, merged