[Feature] support create table ... as select ...
matrixorigin/matrixone pull request #14599
Opened 2024-02-20 07:59 UTC by ck89119

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue https://github.com/matrixorigin/matrixone/issues/10362

## What this PR does / why we need it:
[Feature] support create table ... as select ...

2024-02-20 08:55 UTC, iamlinjunhong approved these changes

2024-02-20 08:55 UTC, nnsgmsone approved these changes

2024-02-20 08:56 UTC, aressu1985 approved these changes

2024-02-20 08:59 UTC, ouyuanning approved these changes

2024-02-20 09:41 UTC, zhangxu19830126 requested changes

2024-02-20 09:41 UTC, zhangxu19830126 commented on pkg/sql/compile/ddl.go
> +			getLogger().Info("createTable",
log error, not log info

2024-02-20 09:41 UTC, zhangxu19830126 commented on pkg/sql/compile/ddl.go
> +	if stmt, ok := c.stmt.(*tree.CreateTable); ok && stmt.IsAsSelect {
move this logic before create auto incr

2024-02-20 09:58 UTC, ck89119 commented on pkg/sql/compile/ddl.go
> +	if stmt, ok := c.stmt.(*tree.CreateTable); ok && stmt.IsAsSelect {
如果新表中有自增列，这段插入数据的逻辑如果放在新建自增列前面会报错

``` sql
mysql> CREATE table t2 (a bigint unsigned not null auto_increment primary key, c float) as select a, b from t1;
ERROR 1146 (HY000): no such table test.t2
```

2024-02-20 09:59 UTC, ck89119 commented on pkg/sql/compile/ddl.go
> +			getLogger().Info("createTable",
这边没有报错，我就是想把这段插入数据的sql打印出来

2024-02-26 03:24 UTC, zhangxu19830126 approved these changes

2024-02-26 05:13 UTC, merged