add some indexes for tables in mo_task
matrixorigin/matrixone pull request #14603
Opened 2024-02-20 09:52 UTC by w-zr

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #14288

## What this PR does / why we need it:

add some indexes for tables in mo_task when bootstrapping.

2024-02-22 06:23 UTC, heni02 approved these changes

2024-02-22 07:02 UTC, zhangxu19830126 requested changes
use upgrade framework to upgrade.

2024-02-26 08:23 UTC, zhangxu19830126 requested changes

2024-02-26 08:23 UTC, zhangxu19830126 commented on pkg/bootstrap/versions/v1_2_0/upgrade.go
> +	if len(result.Batches) != 0 {
use read rows

2024-02-26 09:27 UTC, zhangxu19830126 approved these changes

2024-02-26 10:37 UTC, sukki37 approved these changes

2024-03-07 04:47 UTC, merged