0222 add fk checks
matrixorigin/matrixone pull request #14660
Opened 2024-02-25 01:48 UTC by daviszhen

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #https://github.com/matrixorigin/MO-Cloud/issues/2284

## What this PR does / why we need it:

讨论见：https://github.com/matrixorigin/docs/pull/273

1. 增加外键前向引用。

    新增foreign_key_checs变量
    新增元数据表mo_foreign_keys
    调整drop database 在有外键引用时的行为。
    
    具体细节见文档。

2. 调整外键关系

    create/drop table;
    alter table;
    drop database;

    要对mo_foreign_keys做调整来会维护外键关系。

3. 性能影响

    drop database要额外查询一次mo_foreign_keys

2024-02-26 06:25 UTC, nnsgmsone approved these changes

2024-02-26 06:26 UTC, reusee approved these changes

2024-02-26 06:35 UTC, zhangxu19830126 requested changes

2024-02-26 06:35 UTC, zhangxu19830126 commented on pkg/bootstrap/service.go
> +
There needs to be a copy of the logic created in the upgrade framework

2024-02-26 06:55 UTC, XuPeng-SH approved these changes

2024-02-26 07:17 UTC, heni02 approved these changes

2024-02-26 07:44 UTC, daviszhen commented on pkg/bootstrap/service.go
> +
> There needs to be a copy of the logic created in the upgrade framework

与喜亮沟通后，要等他新升级框架修改好后，他统一迁移。他的pr今天提不上去。
现在加的是旧的升级逻辑。

2024-02-26 07:51 UTC, zhangxu19830126 approved these changes

2024-02-27 01:53 UTC, sukki37 approved these changes

2024-02-27 05:36 UTC, aunjgr approved these changes

2024-02-27 06:31 UTC, qingxinhome approved these changes

2024-02-27 06:32 UTC, badboynt1 approved these changes

2024-02-27 06:46 UTC, ouyuanning approved these changes

2024-03-05 04:25 UTC, merged