Feature/bitmap
matrixorigin/matrixone pull request #14912
Opened 2024-03-12 08:22 UTC by ck89119

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #12604 

## What this PR does / why we need it:
Add bitmap functions to accelerate count distinct operation

2024-03-12 10:18 UTC, m-schen requested changes

2024-03-12 10:18 UTC, m-schen commented on pkg/sql/colexec/agg/agg.go
> +		if bmps, ok := (any)(a.vs).([]*roaring.Bitmap); ok {
别改这部分的逻辑。

把bitmap直接放到private structure里头，不要修改vs的类型。
vs存的是聚合的最终结果。

请参考其它bytes类型的聚合函数的做法（如any_value(bytes)等)。

2024-03-12 10:18 UTC, m-schen commented on pkg/sql/plan/function/functionAgg/bitmap_or.go
> +type sAggBitmapOr struct{}
type sAggBitmapOr struct{
  *roaring.bitmap
}

2024-03-12 10:18 UTC, m-schen commented on pkg/sql/plan/function/functionAgg/bitmap_or.go
> +	return lastResult, nil
return s.marshalBinary()

2024-03-13 06:30 UTC, m-schen approved these changes

2024-03-13 07:04 UTC, aressu1985 approved these changes

2024-03-13 07:56 UTC, iamlinjunhong approved these changes

2024-03-15 06:00 UTC, merged