[Fix] tableName and dbName of col in resultset
matrixorigin/matrixone pull request #15010
Opened 2024-03-18 08:01 UTC by ck89119

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue https://github.com/matrixorigin/MO-Cloud/issues/2665

## What this PR does / why we need it:
Fix tableName and dbName of col in resultset

2024-03-18 08:14 UTC, daviszhen approved these changes

2024-03-18 08:44 UTC, ouyuanning approved these changes

2024-03-18 09:22 UTC, aunjgr requested changes
Looks strange. Why there is a table name in `plan.Type`? Do we have a better place for it?

2024-03-19 09:38 UTC, daviszhen approved these changes

2024-03-19 10:44 UTC, aunjgr approved these changes

2024-03-20 06:02 UTC, nnsgmsone approved these changes

2024-03-22 11:38 UTC, merged