[Fix] : replace point locks with table lock in some cases
matrixorigin/matrixone pull request #15578
Opened 2024-04-17 10:04 UTC by jensenojs

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #https://github.com/matrixorigin/MO-Cloud/issues/3039 https://github.com/matrixorigin/MO-Cloud/issues/3006

## What this PR does / why we need it:

sql like `insert into A select * from B`, will try to lock the value in `B`. When the number of these locks is too much, it will lead to bugs reflected in the issue. In the context of range locks being temporarily unavailable, use table lock to replace point lock

2024-04-17 10:09 UTC, jensenojs commented
- `allter`相关的测试 : https://github.com/matrixorigin/MO-Cloud/issues/3039#issuecomment-2060834585
- `insert into select`相关的测试 : https://github.com/matrixorigin/MO-Cloud/issues/3006#issuecomment-2060722664

`alter table add column`相关的测试还没有跑完.

目前还有一个场景会遇到这个pr所希望fix的bug
```
begin;
insert into values xxx
...
...
commit;
```

当这个`insert into values`所插入的数据过多的时候, 也会遇到`panic too large fixed slice `的问题,  需要讨论一下怎么解决

2024-04-17 10:38 UTC, ouyuanning requested changes

2024-04-17 10:38 UTC, ouyuanning commented on pkg/cnservice/types.go
> +	MaxLockCount int `toml:"max-lock-count"`
应该没必要加这个配置啊
![image](https://github.com/matrixorigin/matrixone/assets/45346669/20c47cde-bd65-4530-bf35-2254de3547c0)
在这里的后面加一下
```
plan.MaxLockCount = c.MaxFixedSliceSize
```

2024-04-17 10:49 UTC, jensenojs commented on pkg/cnservice/types.go
> +	MaxLockCount int `toml:"max-lock-count"`
ok

2024-04-18 06:30 UTC, jensenojs commented on pkg/sql/plan/build_dml_util.go
> +	ifLockTable := false
1. 抽取出了`ifNeedLockWholeTable`
2. `load`在有约束的时候, 能够识别
3. 原来只处理了`appendLockNode`涉及的Lock op, 在遇到类似`delete from sensor_data where id > 2`之类的SQL时确实会遇到问题, 现在已经修复

2024-04-18 08:30 UTC, ouyuanning commented
> 本地ci已经过了
> 
> * `allter`相关的测试 : [[User Bug]: 通过`alter table add index`或`create index`的方式给一个6000万行的表创建索引会报错：`ERROR 20101 (HY000): internal error: panic too large fixed slice 33554432, max is 16777216` MO-Cloud#3039 (comment)](https://github.com/matrixorigin/MO-Cloud/issues/3039#issuecomment-2060834585)
> * `insert into select`相关的测试 : [[MO BUG]: insert into select from table which 5900W rows reported internal error: panic too large fixed slice 33554432 MO-Cloud#3006 (comment)](https://github.com/matrixorigin/MO-Cloud/issues/3006#issuecomment-2060722664)
> 
> `alter table add column`相关的测试还没有跑完.
> 
> 目前还有一个场景会遇到这个pr所希望fix的bug
> 
> ```
> begin;
> insert into values xxx
> ...
> ...
> commit;
> ```
> 
> 当这个`insert into values`所插入的数据过多的时候, 也会遇到`panic too large fixed slice `的问题, 需要讨论一下怎么解决

理论上，最后一次要超过配置锁的数量的那个insert，如果统计信息是准确的，应该也是会转成表锁的。所以感觉当前逻辑应该已经覆盖了。

2024-04-18 08:44 UTC, jensenojs commented
> > 本地ci已经过了
> > 
> > * `allter`相关的测试 : [[User Bug]: 通过`alter table add index`或`create index`的方式给一个6000万行的表创建索引会报错：`ERROR 20101 (HY000): internal error: panic too large fixed slice 33554432, max is 16777216` MO-Cloud#3039 (comment)](https://github.com/matrixorigin/MO-Cloud/issues/3039#issuecomment-2060834585)
> > * `insert into select`相关的测试 : [[MO BUG]: insert into select from table which 5900W rows reported internal error: panic too large fixed slice 33554432 MO-Cloud#3006 (comment)](https://github.com/matrixorigin/MO-Cloud/issues/3006#issuecomment-2060722664)
> > 
> > `alter table add column`相关的测试还没有跑完.
> > 目前还有一个场景会遇到这个pr所希望fix的bug
> > ```
> > begin;
> > insert into values xxx
> > ...
> > ...
> > commit;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 当这个`insert into values`所插入的数据过多的时候, 也会遇到`panic too large fixed slice `的问题, 需要讨论一下怎么解决
> 
> 理论上，最后一次要超过配置锁的数量的那个insert，如果统计信息是准确的，应该也是会转成表锁的。所以感觉当前逻辑应该已经覆盖了。

调试了一下, 发现目前这种情况下, insert values xxx走到`ifNeedLockWholeTable`的时候, `lastNode.Stats.OutCnt`的结果是0, 这个现象在执行了相当个数的`insert values`之后仍然存在

2024-04-18 08:53 UTC, ouyuanning commented
> > > 本地ci已经过了
> > > 
> > > * `allter`相关的测试 : [[User Bug]: 通过`alter table add index`或`create index`的方式给一个6000万行的表创建索引会报错：`ERROR 20101 (HY000): internal error: panic too large fixed slice 33554432, max is 16777216` MO-Cloud#3039 (comment)](https://github.com/matrixorigin/MO-Cloud/issues/3039#issuecomment-2060834585)
> > > * `insert into select`相关的测试 : [[MO BUG]: insert into select from table which 5900W rows reported internal error: panic too large fixed slice 33554432 MO-Cloud#3006 (comment)](https://github.com/matrixorigin/MO-Cloud/issues/3006#issuecomment-2060722664)
> > > 
> > > `alter table add column`相关的测试还没有跑完.
> > > 目前还有一个场景会遇到这个pr所希望fix的bug
> > > ```
> > > begin;
> > > insert into values xxx
> > > ...
> > > ...
> > > commit;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 当这个`insert into values`所插入的数据过多的时候, 也会遇到`panic too large fixed slice `的问题, 需要讨论一下怎么解决
> > 
> > 
> > 理论上，最后一次要超过配置锁的数量的那个insert，如果统计信息是准确的，应该也是会转成表锁的。所以感觉当前逻辑应该已经覆盖了。
> 
> 调试了一下, 发现目前这种情况下, insert values xxx走到`ifNeedLockWholeTable`的时候, `lastNode.Stats.OutCnt`的结果是0, 这个现象在执行了相当个数的`insert values`之后仍然存在

提个issue给倪涛帮忙看看吧

2024-04-18 09:14 UTC, daviszhen approved these changes

2024-04-18 11:56 UTC, zhangxu19830126 approved these changes

2024-04-18 14:10 UTC, merged