[postfix] proxy: fix transfer connections
matrixorigin/matrixone pull request #15682
Opened 2024-04-24 01:43 UTC by volgariver6

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue https://github.com/matrixorigin/MO-Cloud/issues/3052

## What this PR does / why we need it:
1. select all cn servers includes the draining ones
2. should transfer to a different cn server, otherwise, prepare stmt cannot be found.
3. change select sql to set as the method can only execute simple query.
4. fix txn leak when migration
5. fix a sequence issue that the server have to transfer the tunnal after the wait group add one.
6. if connection transfer failed, retry the transfer util there is no cn available.

2024-04-24 01:49 UTC, matrix-meow commented
@volgariver6 Thanks for your contributions!

**Here are review comments for file pkg/clusterservice/cluster.go:**
### Pull Request Review:

#### Title: [postfix] proxy: fix transfer connections

#### Problem 1:
The title of the pull request is misleading. It mentions "postfix" and "proxy" which do not seem relevant to the actual changes made in the code. It would be better to have a title that accurately reflects the changes being made, such as "Fix transfer connections in cluster service".

#### Problem 2:
The body of the pull request lacks detailed information about the specific changes being made. It would be beneficial to provide a more comprehensive explanation of why these changes are necessary and how they address the issue mentioned in the linked GitHub issue.

#### Problem 3:
The changes made in the `cluster.go` file are not optimized. The addition of the `DebugUpdateCNWorkState` function seems to be addressing a specific issue, but the context and usage of this function are not clear from the provided diff snippet. It would be helpful to include comments or documentation explaining the purpose and usage of this new function.

#### Problem 4:
The use of a hardcoded timeout value (`time.Second*3`) in the `DebugUpdateCNWorkState` function could be problematic. Hardcoding timeouts may lead to unexpected behavior in different environments or under varying network conditions. It would be better to consider making this timeout value configurable or at least provide a rationale for why this specific value was chosen.

#### Problem 5:
The error handling in the `DebugUpdateCNWorkState` function is basic and could be improved. Instead of just returning the error, it would be more informative to log or handle the error in a way that provides context or helps in diagnosing the issue.

#### Problem 6:
The lack of unit tests for the newly added `DebugUpdateCNWorkState` function is a concern. It is essential to have proper test coverage for new functionality to ensure its correctness and prevent regressions.

#### Security Issue:
The code changes do not seem to introduce any direct security vulnerabilities based on the provided diff. However, it is crucial to ensure that any input validation, error handling, and access control mechanisms are robust to prevent security breaches.

#### Suggestions for Improvement:
1. Update the title of the pull request to accurately reflect the changes being made.
2. Provide a more detailed explanation in the body of the pull request to clarify the purpose of each change.
3. Add comments or documentation to explain the new `DebugUpdateCNWorkState` function and its usage.
4. Consider making the timeout value in `DebugUpdateCNWorkState` configurable or provide reasoning for the hardcoded value.
5. Enhance error handling in the `DebugUpdateCNWorkState` function to provide more context on failures.
6. Implement unit tests for the `DebugUpdateCNWorkState` function to ensure its correctness and reliability.

By addressing these issues and suggestions, the quality and maintainability of the codebase can be significantly improved.

**Here are review comments for file pkg/clusterservice/cluster_test.go:**
### Pull Request Review:

#### Title: [postfix] proxy: fix transfer connections

#### Problem 1:
The title of the pull request does not seem to match the actual changes made in the code. The title mentions "postfix proxy" while the changes provided are related to `pkg/clusterservice/cluster_test.go`. This discrepancy can cause confusion for other team members reviewing the pull request.

#### Suggestion 1:
Consider updating the title to accurately reflect the changes made in the code. For example, "Fix transfer connections in cluster_test.go".

---

#### Problem 2:
The body of the pull request lacks detailed information about the specific changes made in the code. It briefly mentions fixing transfer connections and provides a list of changes without explaining the rationale behind each change. This lack of context can make it difficult for reviewers to understand the purpose of the modifications.

#### Suggestion 2:
Provide a more detailed description in the pull request body explaining the reasons behind each change. This will help reviewers understand the necessity of the modifications and ensure transparency in the development process.

---

#### Problem 3:
The changes in the `cluster_test.go` file include adding a new method `UpdateCNWorkState` to the `testHAKeeperClient` struct. While the method implementation seems correct, there is a potential issue with the lack of input validation or error handling in the method.

#### Suggestion 3:
1. Add input validation to ensure that `state.UUID` is not empty or invalid before proceeding with the update.
2. Implement error handling to return an error if the UUID provided in the `state` parameter does not match any existing CN UUID in `c.value.CNStores`.

---

#### Problem 4:
The use of `defer c.Unlock()` in the `UpdateCNWorkState` method can lead to potential deadlocks if the method panics before reaching the `defer` statement. This can cause the lock to remain held indefinitely, leading to a deadlock situation.

#### Suggestion 4:
Consider moving the `defer c.Unlock()` statement to the beginning of the method to ensure that the lock is always released, even in case of panics or early returns.

---

#### Problem 5:
The changes made in the `cluster_test.go` file do not include any unit tests for the newly added `UpdateCNWorkState` method. Lack of test coverage can make it challenging to ensure the correctness and reliability of the new functionality.

#### Suggestion 5:
1. Add unit tests to cover different scenarios of updating the CN work state using the `UpdateCNWorkState` method.
2. Include test cases to validate the behavior when providing valid and invalid UUIDs in the `state` parameter.

---

#### Overall Suggestions for Optimization:
1. Provide more descriptive commit messages for each change made in the code to improve readability and understanding.
2. Ensure consistency between the title, body, and actual changes in the pull request to avoid confusion.
3. Consider breaking down the changes into smaller, focused commits to make the review process more manageable and facilitate easier tracking of modifications.

By addressing the identified problems and implementing the suggested optimizations, the quality and maintainability of the codebase can be significantly improved.

**Here are review comments for file pkg/clusterservice/types.go:**
### Pull Request Review:

#### Title: [postfix] proxy: fix transfer connections

#### Issue(s) Fixed:
- This PR addresses issue https://github.com/matrixorigin/MO-Cloud/issues/3052.

#### Description:
1. The PR aims to fix transfer connections in the postfix proxy module.
2. It includes several changes to address issues related to server transfers, SQL queries, transaction leaks during migration, and connection retries.

#### Changes in `pkg/clusterservice/types.go`:
1. Added a new method `DebugUpdateCNWorkState` to the `MOCluster` interface.
2. Added a new method `UpdateCNWorkState` to the `labelSupportedClient` interface.

#### Feedback and Suggestions:
1. **Method Naming**: 
   - The new method `DebugUpdateCNWorkState` added to the `MOCluster` interface seems to be related to debugging or internal purposes. Consider providing a more descriptive name that clearly indicates its purpose.
   - Similarly, for the `UpdateCNWorkState` method in the `labelSupportedClient` interface, ensure the name reflects its functionality accurately.

2. **Documentation**:
   - It's essential to provide clear and concise documentation for the newly added methods. Include comments that explain the purpose of the methods, expected parameters, and return values.

3. **Consistency**:
   - Ensure consistency in method naming and usage across the interfaces to maintain clarity and coherence in the codebase.

4. **Error Handling**:
   - Make sure to handle errors appro [...]

2024-04-24 01:54 UTC, XuPeng-SH approved these changes

2024-04-24 01:54 UTC, zhangxu19830126 approved these changes

2024-04-24 02:02 UTC, reusee approved these changes

2024-04-24 03:19 UTC, triump2020 approved these changes

2024-04-24 03:50 UTC, daviszhen requested changes

2024-04-24 03:50 UTC, daviszhen commented on pkg/frontend/result_row_stmt.go
> +		err2 := execCtx.proto.sendEOFOrOkPacket(0, extendStatus(ses.GetTxnHandler().GetServerStatus()))
从maybeUnsetTxnStatus()的用法和内部实现看。能否新建一个函数，将maybeUnsetTxnStatus()和GetServerStatus包装在一起。避免遗漏maybeUnsetTxnStatus。

2024-04-24 03:50 UTC, daviszhen commented on pkg/frontend/session.go
> +	err = doUse(ses.requestCtx, ses, d.db)
这个地方能否用doComQuery(...,UserInput{sql: "use d.db")来代替。doComQuery 内部会管理事务和并且会落日志到statementifo。避免泄露。

2024-04-24 03:50 UTC, daviszhen commented on pkg/frontend/session.go
>  	if _, err = doPrepareStmt(ses.requestCtx, ses, stmts[0].(*tree.PrepareStmt), p.sql, p.paramTypes); err != nil {
这个地方能否用doComQuery(...,UserInput{sql: "prepare xxxx")来代替。doComQuery 内部会管理事务和并且会落日志到statementifo。避免泄露。

2024-04-24 08:00 UTC, volgariver6 commented on pkg/frontend/result_row_stmt.go
> +		err2 := execCtx.proto.sendEOFOrOkPacket(0, extendStatus(ses.GetTxnHandler().GetServerStatus()))
fixed

2024-04-24 08:01 UTC, volgariver6 commented on pkg/frontend/session.go
>  	if _, err = doPrepareStmt(ses.requestCtx, ses, stmts[0].(*tree.PrepareStmt), p.sql, p.paramTypes); err != nil {
这里不能使用 doComQuery,因为不需要response

2024-04-24 08:01 UTC, volgariver6 commented on pkg/frontend/session.go
> +	err = doUse(ses.requestCtx, ses, d.db)
这里不能使用 doComQuery,因为不需要response

2024-04-24 08:12 UTC, daviszhen commented on pkg/frontend/result_row_stmt.go
> +		err2 := execCtx.proto.sendEOFOrOkPacket(0, extendStatus(ses.GetTxnHandler().GetServerStatus()))
> fixed

maybeUnsetTxnStatus放到了sendEOFOrOkPacket里面。这种改法太绕了。不好维护。

建议在session新增一个函数xxx。

```go

func (ses *Session) xxxx() uint32{

maybeUnsetTxnStatus()
return ses.GetTxnHandler().GetServerStatus()
}


```

2024-04-24 11:14 UTC, daviszhen approved these changes

2024-04-25 02:37 UTC, m-schen approved these changes

2024-04-25 14:17 UTC, aressu1985 approved these changes

2024-04-25 16:18 UTC, merged