Predefine system table as global var
matrixorigin/matrixone pull request #15925
Opened 2024-05-09 01:30 UTC by qingxinhome

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #15756

## What this PR does / why we need it:
把mo系统表和系统视图声明为全局变量，都引用自一处

2024-05-09 01:52 UTC, daviszhen requested changes

2024-05-09 01:52 UTC, daviszhen commented on pkg/bootstrap/predefined.go
> +//MoCatalogMoIndexes = fmt.Sprintf(`create table %s.%s(
不要的直接删除了吧。

2024-05-09 02:40 UTC, qingxinhome commented on pkg/bootstrap/predefined.go
> +//MoCatalogMoIndexes = fmt.Sprintf(`create table %s.%s(
OK

2024-05-10 02:21 UTC, daviszhen approved these changes

2024-05-10 03:43 UTC, zhangxu19830126 approved these changes

2024-05-10 06:32 UTC, qingxinhome commented on pkg/bootstrap/predefined.go
> +//MoCatalogMoIndexes = fmt.Sprintf(`create table %s.%s(
> 不要的直接删除了吧。

 OK

2024-05-10 09:08 UTC, merged