bytejson: replace std json with segmentio/json
matrixorigin/matrixone pull request #16428
Opened 2024-05-27 17:30 UTC by forsaken628

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #16216
follow #16217

## What this PR does / why we need it:
std json Decode.Token too slow

2024-05-27 17:30 UTC, forsaken628 commented
goos: linux
goarch: amd64
pkg: github.com/matrixorigin/matrixone/pkg/container/bytejson
cpu: Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz
BenchmarkParseNode/segmentio-json-4               365667              3090 ns/op             496 B/op         19 allocs/op
BenchmarkParseNode/goccy-json-4                   422893              2789 ns/op            1043 B/op         28 allocs/op
BenchmarkParseNode/std-json-4                     102032             11415 ns/op            3857 B/op        172 allocs/op
PASS
ok      github.com/matrixorigin/matrixone/pkg/container/bytejson        4.751s

2024-06-25 02:47 UTC, zhangxu19830126 approved these changes

2024-06-27 05:49 UTC, fengttt requested changes
What is the reason to choose segmentio/json?   

From the code, segmentio claim to be std json "compatible", but from the code, seems it is at a much lower level parser.    Are we using the right API?   Or at least, is there a reason for this?

2024-06-27 08:48 UTC, forsaken628 commented
long story.

#15726
https://docs.qq.com/doc/DSlpkb1VzS0xKak5Q
#16216

2024-06-29 01:58 UTC, fengttt approved these changes

2024-07-23 00:55 UTC, XuPeng-SH approved these changes

2024-07-23 00:55 UTC, merged