Add cost of GC Check
matrixorigin/matrixone pull request #16470
Opened 2024-05-29 04:10 UTC by LeftHandCold

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue https://github.com/matrixorigin/matrixone/issues/16101

## What this PR does / why we need it:
To avoid List() operations on oss, tke or s3, you need to add the Cost interface.

2024-05-29 06:21 UTC, reusee requested changes

2024-05-29 06:21 UTC, reusee commented on pkg/fileservice/file_service.go
> +	CostHugh
typo

2024-05-29 06:43 UTC, reusee requested changes

2024-05-29 06:43 UTC, reusee commented on pkg/fileservice/file_services.go
> +func (f *FileServices) Cost() *CostAttr {
should range f.mappings, call Cost on each item, get the highest value of each field

2024-05-30 03:23 UTC, reusee approved these changes

2024-05-30 03:31 UTC, XuPeng-SH approved these changes

2024-06-03 05:32 UTC, merged