[opt] : build fuzzy filter on smaller child and clean up code
matrixorigin/matrixone pull request #16522
Opened 2024-05-30 09:44 UTC by jensenojs

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #16455

## What this PR does / why we need it:

prev : 
   build on sink scan : 
      `test and add`
   probe on table scan : 
      `test`

This method will occupy a lot of memory when the sink scan data is much larger than the table scan data.

now : 
if Stats(Table Scan) > Stats(Sink Scan)
	Build on Sink scan
		Test and Add
	Probe on Table scan
		Test
else
	Build on Table scan
		Add
	Probe on Sink scan
		Test and Add

2024-05-30 09:48 UTC, jensenojs commented
```
if  Stats(Table Scan) < Stats(Sink Scan)
	Build on Table scan
		Add
	Probe on Sink scan
		Test and Add
```

这种方式有一个问题是, Sink scan是不支持runtime filter的下推的, 如果要用的话, 得把sink scan也改成table scan.

不过目前sink scan的数据远大于table scan的情况只考虑有 : 通过`insert into select`的方式复制一张大表的情况. 这种情况下下推`runtime filter`的意义好像不是特别大, 目前就先把这种情况的runtime filter给禁用掉了

2024-06-03 04:00 UTC, aunjgr approved these changes

2024-06-03 04:02 UTC, aunjgr requested changes

2024-06-03 04:02 UTC, aunjgr commented on pkg/pb/plan/plan.pb.go
> -	//
为什么会修改无关的pb文件？先检查一下protoc是否是最新版本

2024-06-03 09:33 UTC, jensenojs commented on pkg/pb/plan/plan.pb.go
> -	//
用3.21.1生成的代码仍然会修改plan.pb.go等不相干的文件, 现在手动地只保留pipeline.pb.go的修改了

2024-06-04 06:55 UTC, ouyuanning approved these changes

2024-06-04 07:08 UTC, aunjgr approved these changes

2024-06-04 07:46 UTC, zhangxu19830126 approved these changes

2024-06-04 14:36 UTC, merged