short circuit in if function
matrixorigin/matrixone pull request #16521
Opened 2024-05-30 09:16 UTC by zengyan1

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #14989

## What this PR does / why we need it:
short circuit in if function

2024-06-04 07:41 UTC, XuPeng-SH approved these changes

2024-06-04 07:42 UTC, qingxinhome approved these changes

2024-06-04 07:45 UTC, badboynt1 approved these changes

2024-06-04 08:21 UTC, m-schen commented on pkg/sql/colexec/evalExpression.go
> +		selectList1 := make([]bool, batches[0].RowCount())
这个可以存在 FunctionExpressionExecutor里复用起来。这样多次计算期间不需要重新开辟。

2024-06-04 08:22 UTC, m-schen commented on pkg/sql/colexec/evalExpression.go
> +	Eval(proc *process.Process, batches []*batch.Batch, selectList []bool) (*vector.Vector, error)
下面那个EvalWithoutResultReusing也顺便改掉吧，两个接口保持一致。

2024-06-04 08:26 UTC, m-schen commented on pkg/sql/colexec/evalExpression.go
> +	if expr.fid == function.IFF {
这块代码最好单独拉出去作为一个独立的方法。
if isIFF := fid == function.IFF; isIFF {
    if err := f(); err != nil { return err}
}
提高代码的可读性。

2024-06-04 10:10 UTC, m-schen commented on pkg/sql/colexec/evalExpression.go
> +		selectList = make([]bool, batches[0].RowCount())
这样比没复用性能更差了，还多开辟了一个selectList.

2024-06-04 10:16 UTC, m-schen commented on pkg/sql/plan/function/func_builtin.go
> +		if null1 || null2 || len(v1) == 0 || len(enumStr) == 0 || result.GetResultVector().GetNulls().Contains(i) {
我觉得可以给 result 这个结构体新增一个方法，
func IgnoreCompute(idx) bool, 
或者 func AlreadySet(idx) bool之类的方法，
它的作用就是判断是否为其nsp是否contain().
这样代码更容易理解，也可以免去这边的3层函数调用。

同时可以做进一步优化，就是在生成result的MustFunctionResult方法里直接让他变成两种结构体，
一种是每次都去检查nsp是否contains的，
一种是始终返回false的，这样可以避免每次调用都去判断nsp != nil这件事。

其他函数以及baseTemplate同理。

2024-06-04 10:33 UTC, m-schen requested changes
我觉得可以再多思考一下。现在主要问题是：

1. 执行框架中 selectList 的复用问题。
2. 函数具体实现里，突然对result的vector判断nsp在该pr中可以明白目的，但后续会难以理解。
3. 函数具体实现（包括模板）可以做一些性能上的优化。

然后最好再跑跑各种性能测试。

2024-06-04 10:33 UTC, m-schen commented on pkg/sql/plan/function/baseTemplate.go
> +				if rsVec.GetNulls().Contains(i) {
与普通函数相同，这里要尽量减少关于nsp的判断，
可以通过提前筛选出nsp == nil的情况或者类似其他评论说的给result提供IgnoreCompute()等方法。

可以多思考一下，或者直接改变整个模板的实现。

我感觉把函数的传参变成
parameters, result, length, ignore 似乎也是可以的。其中ignore是一个结构体的指针（直接从function expression里存的selectList1, selectList2组成），对外提供 shouldIgnore方法，
这样模板里可以通过判断这个是否为空来省很多操作，普通函数也会好改一些。
并且可以省去执行框架里每次把selectList变成nsp的步骤，当然这个步骤的成本被转移到了函数实现里的append null，但是目前的代码改动其实也会做这步冗余操作。

作为对函数开发者提供的模板，可以多做一些优化。
（这里可以考虑把baseTemplate变成由MakeFile生成，可以减轻一些修改压力和误改，不过这个是另一件事情了）。

2024-06-04 10:35 UTC, m-schen commented on pkg/sql/plan/function/func_builtin.go
> +		if null1 || null2 || len(v1) == 0 || len(enumStr) == 0 || result.GetResultVector().GetNulls().Contains(i) {
只是提议，直接判断result的nsp去决定是否跳过该行的计算会让后续开发者难以理解。

2024-06-12 09:25 UTC, m-schen commented on pkg/sql/plan/function/func_builtin_test.go
> +		tcc := testutil.NewFunctionTestCase(proc, tc.inputs, tc.expect, TbuiltInLog10)
testutil.NewFunctionTestCase 相关的代码都挪到function目录下的单测文件里吧

2024-06-12 09:26 UTC, m-schen commented on pkg/sql/plan/function/function.go
> +func (selectList *FunctionSelectList) HasAnyNull() bool {
HasAnyNull 和 IsAllNull 需要修改一个名字。
需要体现出 当返回true和false时，是所有的行都应该跳过，还是都不应该跳过。

2024-06-12 09:37 UTC, m-schen approved these changes
加了个not-merge的标签，这两个问题解决后把标签去掉就好。

2024-06-12 10:18 UTC, heni02 approved these changes

2024-06-13 10:51 UTC, merged