add SERVER_MORE_RESULTS_EXISTS judgment
matrixorigin/matrixone pull request #16712
Opened 2024-06-06 06:07 UTC by CJKkkk-315

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #3107

## What this PR does / why we need it:

补全响应client时的SERVER_MORE_RESULTS_EXISTS 设置

2024-06-06 06:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/matrixorigin/matrixone?pullRequest=16712) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/matrixorigin/matrixone?pullRequest=16712) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/matrixorigin/matrixone?pullRequest=16712) it.</sub>

2024-06-06 11:24 UTC, daviszhen requested changes

2024-06-06 11:24 UTC, daviszhen commented on pkg/frontend/result_row_stmt.go
> +	status := ses.getStatusAfterTxnIsEnded(execCtx.reqCtx)
建议这段逻辑封装成单独的函数xxx。然后调用这个函数xxx。

2024-06-06 11:24 UTC, daviszhen commented on pkg/frontend/result_row_stmt.go
> +	status := ses.getStatusAfterTxnIsEnded(execCtx.reqCtx)
将修改也提交到1.2-dev上。

2024-06-07 03:53 UTC, CJKkkk-315 commented on pkg/frontend/result_row_stmt.go
> +	status := ses.getStatusAfterTxnIsEnded(execCtx.reqCtx)
isLastStmt判断直接添加到getStatusAfterTxnIsEnded函数中了

2024-06-07 12:01 UTC, CJKkkk-315 commented on pkg/frontend/session.go
> +		return extendStatus(ses.GetTxnHandler().GetServerStatus()) | SERVER_MORE_RESULTS_EXISTS
修改完毕。

2024-06-11 02:22 UTC, daviszhen approved these changes

2024-06-11 03:13 UTC, merged