Refactor send row result
matrixorigin/matrixone pull request #16780
Opened 2024-06-11 04:21 UTC by CJKkkk-315

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

清理了返回查询结构相关代码的无用逻辑和参数传递
修改了部分函数名，提高可读性
binary传输中，将写入NullBitMap的逻辑单独独立成函数
修正了TIME类数据在二进制传输中，负值无法正确显示的问题

2024-06-11 06:37 UTC, daviszhen requested changes

2024-06-11 06:37 UTC, daviszhen commented on pkg/frontend/mysql_protocol.go
> +			return
这个err 不能吞掉吧。

2024-06-11 06:37 UTC, daviszhen commented on pkg/frontend/mysql_protocol.go
> +//func beginWriteIndex(outbuf *goetty_buf.ByteBuf, offset int) int {
删除

2024-06-11 06:37 UTC, daviszhen commented on pkg/frontend/mysql_protocol.go
> +		return
err 不能吞

2024-06-11 06:37 UTC, daviszhen commented on pkg/frontend/mysql_protocol.go
> +// the server send every row of the result set as an independent packetjjiji
？？？

2024-06-11 06:37 UTC, daviszhen commented on pkg/frontend/mysql_protocol.go
> +	mp.closePacket(true)
检查下error

2024-06-11 10:36 UTC, CJKkkk-315 commented
还原了部分不可删除的err。 修改了test文件中的一些对应代码

2024-06-12 06:05 UTC, daviszhen approved these changes

2024-06-12 08:21 UTC, merged