add log
matrixorigin/matrixone pull request #16831
Opened 2024-06-12 09:21 UTC by triump2020

## What type of PR is this?

- [ ] API-change
- [ x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #16273 

## What this PR does / why we need it:
1.Add log

2024-06-12 09:47 UTC, daviszhen requested changes

2024-06-12 09:47 UTC, daviszhen commented on pkg/frontend/txn.go
> +				//TODO::
注释掉的都去掉吧。下同

2024-06-12 09:47 UTC, daviszhen commented on pkg/frontend/util.go
> +		ses.Debug(ctx, "query trace status", logutil.StatementField(str), logutil.StatusField(status.String()), logutil.TxnIdField(txnInfo))
默认是Info级别。Debug接口不回打印任何日志的。

改为info后，打印会非常多。

要判断确定sql才能改为info。

2024-06-12 10:46 UTC, jensenojs commented on pkg/frontend/util.go
> +		ses.Debug(ctx, "query trace status", logutil.StatementField(str), logutil.StatusField(status.String()), logutil.TxnIdField(txnInfo))
加了

2024-06-13 04:57 UTC, daviszhen approved these changes

2024-06-13 04:57 UTC, daviszhen commented on pkg/frontend/txn.go
> +		//commitTs := th.txnOp.Txn().CommitTS
这些不要了，都删除掉吧

2024-06-13 04:57 UTC, daviszhen commented on pkg/frontend/types.go
> +	//SetStaticTxnId(id []byte)
不要了，都删掉吧。

2024-06-13 04:59 UTC, daviszhen requested changes

2024-06-13 04:59 UTC, daviszhen commented on pkg/frontend/types.go
> +	//SetStaticTxnId(id []byte)
不要都删掉吧。

2024-06-13 04:59 UTC, daviszhen commented on pkg/frontend/txn.go
> +		//commitTs := th.txnOp.Txn().CommitTS
不要了，都删掉吧。

2024-07-08 08:06 UTC, closed without merging