Export data to csv file
matrixorigin/matrixone pull request #1693
Opened 2022-02-10 02:01 UTC by jianwan0214

**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

2022-02-10 02:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/matrixorigin/matrixone?pullRequest=1693) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/matrixorigin/matrixone?pullRequest=1693) before we can accept your contribution.<br/><hr/>**王剑** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/matrixorigin/matrixone?pullRequest=1693) it.</sub>

2022-02-10 02:30 UTC, daviszhen requested changes

2022-02-10 02:30 UTC, daviszhen commented on pkg/frontend/mysql_cmd_executor.go
> +		defer oq.file.Close()
The "oq.file" may be closed.

2022-02-10 02:30 UTC, daviszhen commented on pkg/frontend/mysql_cmd_executor.go
> +	defaultBufSize = 4*1024*1024
The "defaultBufSize" can be put into the configuration.

2022-02-10 02:30 UTC, daviszhen commented on pkg/frontend/mysql_cmd_executor.go
> +			var header string
string or byte[] can be reused in concating strings.

2022-02-10 02:30 UTC, daviszhen commented on pkg/frontend/mysql_cmd_executor.go
> +				header += bat.Attrs[i] + ses.ep.Fields.Terminated
Concating strings can be put into the independent interface.

2022-02-10 02:30 UTC, daviszhen commented on pkg/frontend/mysql_cmd_executor.go
> +func writeDataToCSVFile(o *outputQueue, output string) error {
Put the function into export.go.

2022-02-10 02:30 UTC, daviszhen commented on pkg/frontend/mysql_cmd_executor.go
> +	var output string
reuse string space

2022-02-10 02:30 UTC, daviszhen commented on pkg/frontend/mysql_cmd_executor.go
> +	var output string
concating the string can be put into the independent function.

2022-02-10 02:30 UTC, daviszhen commented on pkg/frontend/mysql_cmd_executor.go
> +	o.ep.CurFileSize += uint64(len(output))
The file limit should be checked first.

2022-02-10 02:30 UTC, daviszhen commented on pkg/frontend/mysql_cmd_executor.go
> +		_ = o.writer.Flush()
reserve the error

2022-02-10 02:30 UTC, daviszhen commented on pkg/frontend/mysql_cmd_executor.go
> +		o.ep.Flag++
flag -> filecount

2022-02-10 02:30 UTC, daviszhen commented on pkg/frontend/mysql_cmd_executor.go
> +		o.file, err = os.OpenFile(filePath, os.O_WRONLY | os.O_EXCL | os.O_CREATE, 0666)
reuse the code for creating file and file header

2022-02-10 02:30 UTC, daviszhen commented on pkg/frontend/mysql_cmd_executor.go
> +	_, err := o.writer.WriteString(output)
write bytes

2022-02-14 03:12 UTC, daviszhen requested changes

2022-02-14 03:12 UTC, daviszhen commented on pkg/frontend/export.go
> +		o.ep.CurFileSize = uint64(len(output))
how to handle the situation when the len(output) > maxfilesize

2022-02-14 03:12 UTC, daviszhen commented on pkg/frontend/export.go
> +	o.ep.CurFileSize += uint64(len(output))
CurFileSize updated after writing data.

2022-02-16 02:35 UTC, iamlinjunhong commented on pkg/sql/parsers/dialect/mysql/mysql_sql.y
> -    strs []string
delete?

2022-02-16 02:39 UTC, iamlinjunhong commented on pkg/sql/parsers/dialect/mysql/mysql_sql.y
> +|   MAX_FILE_SIZE STRING
You can add an integer instead of adding a string to convert it to an integer after MAX_FILE_SIZE

2022-02-16 02:43 UTC, iamlinjunhong commented on pkg/sql/parsers/dialect/mysql/mysql_sql.y
> +    select_no_parens export_data_param
The construction of the whole grammar should be in simple_select, refer to tidb or MySQL for details

2022-02-16 02:49 UTC, iamlinjunhong commented on pkg/sql/parsers/dialect/mysql/mysql_sql.y
> +|   OUTFILE
reserved_keyword should refer to https://dev.mysql.com/doc/refman/8.0/en/keywords.html

2022-02-17 07:54 UTC, iamlinjunhong commented on pkg/frontend/mysql_cmd_executor.go
> +			fmt.Println("wangjian sqlBBB is", mce.exportDataClose)
log

2022-02-17 07:57 UTC, iamlinjunhong commented on pkg/sql/parsers/dialect/mysql/mysql_sql.y
> +export_data_param:
if it can be nil, should be rename export_data_param_opt

2022-02-17 08:03 UTC, iamlinjunhong commented on pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
> +			fmt.Println("wangjian sql2 is", out, "AAAA", tcase.input)
log

2022-02-17 08:06 UTC, iamlinjunhong commented on pkg/sql/parsers/dialect/mysql/mysql_sql.y
> +    select_no_parens export_data_param
export_data_param should be added after <simple_select order_by_opt limit_opt>

2022-02-17 11:17 UTC, daviszhen requested changes

2022-02-17 11:17 UTC, daviszhen commented on pkg/frontend/mysql_cmd_executor.go
> +					return nil
Will it close the opened file?

2022-02-17 11:17 UTC, daviszhen commented on pkg/frontend/export.go
> +	if _, err := Write(oq, output); err != nil {
"for loop " handling unfinished buffer.

2022-02-17 11:17 UTC, daviszhen commented on pkg/frontend/export.go
> +	return oq.file.Read(oq.ep.OutputStr)
"for loop" handling unfinished buffer.

2022-02-17 11:17 UTC, daviszhen commented on pkg/frontend/load.go
> +type CloseExportData struct {
move to export.go

2022-02-18 07:49 UTC, closed without merging