fix ranges bug of more than 2 augments in or expression.
matrixorigin/matrixone pull request #16992
Opened 2024-06-19 04:15 UTC by gouhongshen

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #https://github.com/matrixorigin/matrixone/issues/16976

## What this PR does / why we need it:
fix ranges bug of more than 2 augments in or expression.

2024-06-19 11:21 UTC, XuPeng-SH approved these changes

2024-06-20 03:15 UTC, heni02 approved these changes

2024-06-20 04:24 UTC, aunjgr requested changes

2024-06-20 04:24 UTC, aunjgr commented on pkg/container/vector/vector.go
> +			AppendFixed[T](ret, short[i], false, mp)
对一个空的vector循环做AppendFixed，会有太多的overhead。最好是先把内存分配好，然后直接在slice上面做循环。

2024-06-20 11:23 UTC, merged