When DDL statement has been executed within a transaction, force the use of a single CN
matrixorigin/matrixone pull request #17206
Opened 2024-06-28 04:49 UTC by ouyuanning

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #14453 https://github.com/matrixorigin/MO-Cloud/issues/3649 https://github.com/matrixorigin/MO-Cloud/issues/3648

## What this PR does / why we need it:
When a DDL statement has been executed within a transaction, force the use of a single CN

2024-06-28 06:00 UTC, daviszhen approved these changes

2024-06-28 07:22 UTC, zhangxu19830126 approved these changes

2024-06-28 11:54 UTC, aressu1985 approved these changes

2024-06-28 11:55 UTC, m-schen approved these changes

2024-06-28 14:15 UTC, badboynt1 approved these changes

2024-06-29 05:54 UTC, triump2020 requested changes

2024-06-29 06:58 UTC, ouyuanning commented on pkg/vm/engine/disttae/txn.go
> +func (txn *Transaction) SetHaveDDL(flag bool) {
good point. done

2024-06-29 06:58 UTC, ouyuanning commented on pkg/vm/engine/disttae/txn.go
> +func (txn *Transaction) SetHaveDDL(flag bool) {
good point. done

2024-06-29 07:06 UTC, triump2020 approved these changes

2024-06-30 14:39 UTC, merged