adding UTs for partition state.
matrixorigin/matrixone pull request #17389
Opened 2024-07-09 02:49 UTC by gouhongshen

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #https://github.com/matrixorigin/matrixone/issues/14908

## What this PR does / why we need it:
1. tool functions to help code UT for partition state

2024-07-09 03:23 UTC, zhangxu19830126 approved these changes

2024-07-11 09:39 UTC, XuPeng-SH approved these changes

2024-07-11 10:46 UTC, triump2020 requested changes

2024-07-11 10:46 UTC, triump2020 commented on pkg/vm/engine/disttae/logtail_consumer.go
> +		case SubRspReceived:
"TryToSubcribeTable" is abandoned,  use toSubscribe instead.

2024-07-11 12:27 UTC, gouhongshen commented on pkg/vm/engine/disttae/logtail_consumer.go
> +		case SubRspReceived:
单测需要将消费 logtail 和 ckp 分开，`toSubscribeTable` 不能做到这一点

2024-07-11 13:06 UTC, triump2020 approved these changes

2024-07-12 04:31 UTC, merged