Clean network code
matrixorigin/matrixone pull request #17459
Opened 2024-07-10 09:25 UTC by CJKkkk-315

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #12390

## What this PR does / why we need it:
清理网络代码

###### 1. 将handshake逻辑解耦。
###### 2. 改进读数据方法
- 优化内存分配次数
- 将读协议数据和处理逻辑解耦。
###### 3. 改进写数据方法
- 输出缓冲区改用定长buffer+变长buffer
- 减少写操作的次数。
- 修复了当字段大小等于16MB时会引发的Bug。
- Write方法改为只写状态包(OK,ERR,EOF)，执行时先Flush Buffer内数据。
- 改进Load Local
###### 4. 改进UT
- 适配新代码。修改UT及Proxy部分代码

https://github.com/matrixorigin/ci-test/actions/runs/9854565566

2024-07-10 12:48 UTC, daviszhen requested changes

2024-07-10 12:48 UTC, daviszhen commented on etc/launch/cn.toml
> +
删掉这个修改。

2024-07-10 12:48 UTC, daviszhen commented on pkg/frontend/iopackage_test.go
> +//func echoHandler(session goetty.IOSession, msg interface{}, received uint64) error {
不需要了，删掉吧。

2024-07-10 12:48 UTC, daviszhen commented on pkg/frontend/mysql_cmd_executor.go
> +	readThenWrite := func() error {
剥离成单个函数。

2024-07-10 12:48 UTC, daviszhen commented on pkg/frontend/mysql_protocol.go
> +	mp.tcpConn.ses = ses
！！！在Close的时候，要主动mp.tcpConn.ses = nil。短链接会内存leak

2024-07-10 12:48 UTC, daviszhen commented on pkg/frontend/protocol.go
> +	return mp.tcpConn.Flush()
这个flush和 上面的AutoFlush相关的接口和字段都删了。

2024-07-10 12:48 UTC, daviszhen commented
整体上在预期内。Thank you

2024-07-10 12:50 UTC, daviszhen requested changes

2024-07-10 12:50 UTC, daviszhen commented on pkg/sql/parsers/dialect/mysql/mysql_sql.go
> +				{
这个文件都是自动生成的。不需要修改呀。

2024-07-10 12:50 UTC, daviszhen commented on pkg/sql/parsers/dialect/mysql/mysql_sql.go
> +				{
在这个pr里面，应该涉及不到parser的修改！！！

2024-07-11 02:35 UTC, CJKkkk-315 commented on pkg/frontend/routine_manager_test.go
> +//func create_test_server() *MOServer {
已恢复

2024-07-11 02:36 UTC, CJKkkk-315 commented on pkg/frontend/mysql_cmd_executor.go
> +	readThenWrite := func() error {
不使用闭包的话 会有太多参数传递 感觉不太好

2024-07-11 06:08 UTC, daviszhen requested changes

2024-07-11 06:08 UTC, daviszhen commented on pkg/frontend/codec.go
> +	"io"
这个文件的代码还有需要的吗？不要就把这个文件删了。

2024-07-11 06:09 UTC, daviszhen commented on pkg/frontend/mysql_cmd_executor.go
> +	readThenWrite := func() error {
> 不使用闭包的话 会有太多参数传递 感觉不太好

改掉吧

2024-07-11 07:23 UTC, CJKkkk-315 commented on pkg/frontend/codec.go
> +	"io"
proxy需要通过codec

2024-07-11 07:23 UTC, CJKkkk-315 commented on pkg/frontend/mysql_cmd_executor.go
> +	readThenWrite := func() error {
> > 不使用闭包的话 会有太多参数传递 感觉不太好
> 
> 改掉吧

已修改

2024-07-11 08:52 UTC, daviszhen approved these changes

2024-07-11 08:57 UTC, closed without merging