persisted storage transfer page hashmap
matrixorigin/matrixone pull request #17490
Opened 2024-07-12 05:39 UTC by Wenbin1002

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #16953

## What this PR does / why we need it:

减少transfer page hashmap的内存消耗

在 zbulk.sh 测试场景下，transfer page内存消耗从40g降低至4g
![企业微信截图_17206645205114](https://github.com/user-attachments/assets/36c376e1-ecb3-4707-8c4c-9b4c7213882c)
![企业微信截图_1720666501392](https://github.com/user-attachments/assets/32a7d236-3d23-4cfd-b4f9-b36ecc45e21c)

grafana
![企业微信截图_17206079436907](https://github.com/user-attachments/assets/077aac53-7009-4734-8f94-0a3a9e143949)

2024-07-12 05:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/matrixorigin/matrixone?pullRequest=17490) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/matrixorigin/matrixone?pullRequest=17490) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: aptend<br/>:x: Wenbin1002<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/matrixorigin/matrixone?pullRequest=17490) it.</sub>

2024-07-12 05:59 UTC, aptend approved these changes

2024-07-12 06:49 UTC, XuPeng-SH requested changes
please modify as commented

2024-07-12 06:49 UTC, XuPeng-SH commented on pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
> +func WriteTransferPage(pages []*model.TransferHashPage, ioVector fileservice.IOVector) error {
use `ctx context.Context` as the first input parameter

2024-07-12 06:49 UTC, XuPeng-SH commented on pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
>  func (entry *mergeObjectsEntry) prepareTransferPage() {
add `ctx context.Context`. we need to pass the `ctx` from outside to the inner.

2024-07-12 06:49 UTC, XuPeng-SH commented on pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
>  		panic(fmt.Sprintf("k %v, mapping %v", k, len(entry.transMappings.Mappings)))
if it is unexpected, we can fatal this message and crash. For the background task, we never panic but crash the process.

2024-07-12 06:49 UTC, XuPeng-SH commented on pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
>  func (entry *mergeObjectsEntry) prepareTransferPage() {
I think it should return `err error` now and the caller need to handle error scenario

2024-07-12 06:49 UTC, XuPeng-SH commented on pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
> +			return
Any error, return ok? i think we need to inject some error to see whether we handle error as expected. (memory or storage leak, panic, or something horrible)

2024-07-12 06:49 UTC, XuPeng-SH commented on pkg/vm/engine/tae/db/open.go
> +	model.SetFileService(opts.LocalFs)
don't introduce any global variable any more

2024-07-15 08:33 UTC, XuPeng-SH approved these changes

2024-07-15 08:37 UTC, zhangxu19830126 approved these changes

2024-07-15 09:29 UTC, merged