add mo_snapshots ts compatible with main branch
matrixorigin/matrixone pull request #17503
Opened 2024-07-12 09:11 UTC by YANGGMM

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #17497

## What this PR does / why we need it:
add mo_snapshots ts compatible with main branch

2024-07-12 09:45 UTC, daviszhen approved these changes

2024-07-12 10:18 UTC, qingxinhome requested changes

2024-07-12 10:18 UTC, qingxinhome commented on pkg/bootstrap/versions/v1_2_2/upgrade.go
> +var upg_mo_snapshots_to_varchar = versions.UpgradeEntry{
建议将升级项，另起一个文件进行编写

2024-07-15 01:59 UTC, YANGGMM commented on pkg/bootstrap/versions/v1_2_2/upgrade.go
> +var upg_mo_snapshots_to_varchar = versions.UpgradeEntry{
ok

2024-07-15 02:55 UTC, qingxinhome approved these changes

2024-07-15 03:44 UTC, zhangxu19830126 approved these changes

2024-07-16 07:43 UTC, sukki37 approved these changes

2024-07-31 11:58 UTC, merged