reduce mp.Grow2 in external operator
matrixorigin/matrixone pull request #17575
Opened 2024-07-17 05:20 UTC by huby2358

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:
reduce mp.Grow2 in external operator

2024-07-17 06:24 UTC, fengttt requested changes
This is almost surely WRONG.   Look into the PreExtendArea, there is a bad hack that only extend area for float32/64 vector type.   It is just wrong.

2024-07-22 10:49 UTC, aunjgr requested changes
Don't do PreExtendArea inside vector.Union* methods.

PreExtendArea takes 2 parameters as now. It's enough for fixed-width types, like f32Vec.

To handle varchar-like types, it should take one more parameter: the incremental length of Area. For the join operators, the caller of PreExtendArea is responsible for accumulating the total length of a varchar vector.

2024-07-25 07:20 UTC, aunjgr approved these changes

2024-07-29 04:29 UTC, fengttt approved these changes

2024-08-17 01:36 UTC, closed without merging