[BugFix]: Add Area Parameter to the PreExtendArea
matrixorigin/matrixone pull request #17587
Opened 2024-07-17 22:36 UTC by arjunsk

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue # https://github.com/matrixorigin/matrixone/issues/16124

## What this PR does / why we need it:

Modify `PreExtendArea` signature to support area size as an argument.

2024-07-18 03:56 UTC, fengttt requested changes
Just don't give people -1 option.   If you give that, they will abuse.

Why don't we just compute the area size outside of the function and pass the value in?   Esp, in your base, you can get this number from the 2 vectors you need to union (areaSize of vec1 + areaSize of vec2).    Or if you know better, the 8192 dim vector size, then you do multiple.

2024-07-19 00:08 UTC, fengttt approved these changes

2024-07-19 01:19 UTC, XuPeng-SH approved these changes

2024-07-19 07:18 UTC, badboynt1 approved these changes

2024-07-19 09:36 UTC, aunjgr approved these changes

2024-07-21 09:45 UTC, merged