interface of dynamic reader block filter for order by.
matrixorigin/matrixone pull request #17624
Opened 2024-07-20 04:50 UTC by gouhongshen

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2024-07-20 16:05 UTC, fengttt commented on pkg/sql/colexec/table_scan/table_scan.go
> +	//tableScan.ctr.orderBy = tableScan.Reader.GetOrderBy()
Why?

2024-07-20 16:06 UTC, fengttt commented on pkg/sql/colexec/table_scan/table_scan.go
> +			for _ = range msgs {
Here too.   Why do you comment it out?   Either add enough doc/comment on why, or if the code is dead, just remove.

2024-07-20 16:06 UTC, fengttt commented on pkg/sql/compile/scope.go
> +		//s.DataSource.R.SetOrderBy(s.DataSource.OrderBy)
Here tool.

2024-07-20 16:07 UTC, fengttt requested changes
Please fix commented code.

2024-07-21 13:19 UTC, daviszhen approved these changes

2024-07-22 10:30 UTC, closed without merging