Add cdc parse
matrixorigin/matrixone pull request #17726
Opened 2024-07-25 08:19 UTC by CJKkkk-315

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue # https://github.com/matrixorigin/MO-Cloud/issues/2227

## What this PR does / why we need it:
Add CDC SQL parse

2024-07-25 09:10 UTC, daviszhen requested changes

2024-07-25 09:10 UTC, daviszhen commented on pkg/sql/plan/build.go
> +	case *tree.ShowCDC:
这块先不加吧。

2024-07-25 09:10 UTC, daviszhen commented on pkg/sql/plan/build_show.go
> +func buildShowCDC(stmt *tree.ShowCDC, ctx CompilerContext) (*Plan, error) {
先不加。sql 是个样例sql。怪怪的。

2024-07-25 11:06 UTC, daviszhen approved these changes

2024-07-26 02:14 UTC, iamlinjunhong approved these changes

2024-07-26 03:08 UTC, merged