Fix: get system variable `autocommit` in backSession
matrixorigin/matrixone pull request #17730
Opened 2024-07-25 11:35 UTC by ck89119

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #17665 

## What this PR does / why we need it:
Fix: get system variable `autocommit` in backSession

2024-07-25 11:55 UTC, daviszhen approved these changes

2024-07-25 12:05 UTC, daviszhen requested changes

2024-07-25 12:05 UTC, daviszhen commented on pkg/frontend/authenticate.go
> +							if json.Unmarshal([]byte(bodyStr), u) == nil && u.Imppkg/frontend/mysql_cmd_executor.goort {
为啥我看到的是
![image](https://github.com/user-attachments/assets/5094c11d-cccf-481d-a01c-bcc8834017ad)

2024-07-25 12:05 UTC, daviszhen commented on pkg/frontend/variables.go
> +	if _, ok := ses.(*backSession); ok {
这个改不好。

还是将“GetSessionSysVar” 在backsession上单独拎出来。
因为原先的逻辑是，backsession不支持前他的变量的，除了autocommit 之外。

2024-07-25 12:05 UTC, daviszhen commented on pkg/frontend/variables.go
> +	if _, ok := ses.(*backSession); ok {
这么改相当于backsession支持了所有变量。

2024-07-25 13:11 UTC, daviszhen approved these changes

2024-07-26 10:43 UTC, sukki37 approved these changes

2024-07-26 10:44 UTC, merged