Make sels int64
matrixorigin/matrixone pull request #17755
Opened 2024-07-27 12:13 UTC by fengttt

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [x] Code Refactoring

## Which issue(s) this PR fixes:

issue #17754

## What this PR does / why we need it:

Unfuck our code.

2024-07-27 13:00 UTC, LeftHandCold approved these changes

2024-07-28 09:30 UTC, m-schen approved these changes

2024-07-29 00:20 UTC, ouyuanning approved these changes

2024-07-31 05:22 UTC, XuPeng-SH approved these changes

2024-07-31 07:25 UTC, badboynt1 requested changes
i think sels in shuffle.go should not change to int64, which will cause more memory allocation

2024-07-31 22:53 UTC, fengttt commented
> i think sels in shuffle.go should not change to int64, which will cause more memory allocation

this sels size should not depends on the amount of data pass through.   for shuffle, it is not a significant overhead.   This is a non issue.

2024-08-01 02:29 UTC, badboynt1 approved these changes

2024-08-01 08:46 UTC, aunjgr approved these changes

2024-08-02 01:47 UTC, triump2020 approved these changes

2024-08-02 05:40 UTC, merged