Feat: publish-subscribe enhancement phase 2
matrixorigin/matrixone pull request #17766
Opened 2024-07-29 03:04 UTC by ck89119

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #16188 

## What this PR does / why we need it:
Feat: publish-subscribe enhancement phase 2
PRD: https://doc.weixin.qq.com/doc/w3_AZUAugYIAOcKTNjDuYAT1is3i8prQ?scode=AJsA6gc3AA8k71X7lGAZUAugYIAOc

2024-07-31 06:24 UTC, ck89119 commented on etc/launch/cn.toml
> +pub-all-accounts = "acc1"
是的，测试的时候忘删了，本地已经删了还没推上来

2024-08-05 07:04 UTC, iamlinjunhong approved these changes

2024-08-05 09:06 UTC, aunjgr approved these changes

2024-08-05 11:01 UTC, zhangxu19830126 approved these changes

2024-08-05 11:40 UTC, daviszhen requested changes

2024-08-05 11:40 UTC, daviszhen commented on etc/launch/cn.toml
> +enable-metrics = true
这个地方不要动

2024-08-06 03:05 UTC, heni02 approved these changes

2024-08-06 08:21 UTC, daviszhen approved these changes

2024-08-06 09:47 UTC, m-schen commented on pkg/sql/compile/compile.go
> +	}
不允许直接修改proc.Ctx，尤其是为他赋予用户id, 这个动作很危险。
如果外面调用者有并发的话，这会导致另一个地方得到本不该得到的权限。

这个地方的逻辑你可以写成
ctx := c.proc.Ctx
if accountId >= 0 {
// 修改ctx = defines.AttachAccountId(c.proc.Ctx, uint32(accountId))
}
return exec.Exec(ctx, sql, opts)

不要改动到c.proc.Ctx.

2024-08-06 09:48 UTC, m-schen commented on pkg/sql/compile/compile.go
> +	res, err := c.runSqlWithResult(sql, -1)
我感觉 -1 定义成 UseOriginalAccount 之类的可能会更好一些

2024-08-06 10:07 UTC, m-schen approved these changes

2024-08-06 16:25 UTC, merged