Add ProjectList in some operators
matrixorigin/matrixone pull request #17761
Opened 2024-07-29 00:41 UTC by zengyan1

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #16403 

## What this PR does / why we need it:
Add ProjectList in some operators

2024-07-29 00:42 UTC, zengyan1 commented
Testing

2024-07-29 04:09 UTC, fengttt commented on pkg/sql/compile/remoterun_test.go
> +		{Op: int32(vm.Projection), ProjectList: []*plan2.Expr{}},
Are you sure about this change?   Why say, the next operator, Filter, takes plan.Expr?    Something wrong.

2024-07-29 04:17 UTC, fengttt requested changes
How each of the operator acquire the project list?   Not clear to me how the compile code works.

2024-07-30 01:46 UTC, ouyuanning commented on pkg/sql/colexec/table_scan/types.go
> +		anal.Alloc(tableScan.Projection.MaxAllocSize)
因为这个时候table_scan和projection在一个Node里了。这个时候的 anal.Alloc应该是  ctr.MaxAllocSize + projeciton.MaxAllocSize

2024-07-30 01:46 UTC, ouyuanning commented on pkg/sql/colexec/projection.go
> +	result.SetRowCount(bat.RowCount())
Projection节点可能是last node，这里应该需要加入output的统计信息处理

2024-07-30 01:46 UTC, ouyuanning commented on pkg/sql/colexec/projection.go
> +		reuse.Free[Projection](projection, nil)
这个PR的projection的生命周期处理方式有点奇怪。它类似一个prepare开始，free或者reset结束。
而operator的生命周期是等scope release的时候才会放回reuse的。
也就是这个projection比普通算子的生命周期要短

2024-07-30 02:33 UTC, zengyan1 commented on pkg/sql/colexec/projection.go
> +	result.SetRowCount(bat.RowCount())
output在调用projection的operator中统计，colexec.projection不会单独存在，保留了colexec/projection.projection

2024-07-30 02:36 UTC, zengyan1 commented on pkg/sql/colexec/projection.go
> +		reuse.Free[Projection](projection, nil)
是的，比普通算子短。普通算子是在compile的时候从reuse拿出，projection是执行时prepare从reuse拿出。放回reuse都是free，project的free只会在普通算子的free中被调用，是同时的。
我不知道这样做是否有问题？

2024-07-30 03:01 UTC, ouyuanning commented on pkg/sql/colexec/projection.go
> +	result.SetRowCount(bat.RowCount())
如果projection被并入其他算子，那么这个时候的last也可能会变成被并入的那个算子的
比如：  select a+1 from t1;
以前可能是 projection是last，现在table_scan会既是first也是last了。这个时候就需要table_scan算子也统计output了

2024-07-30 03:03 UTC, ouyuanning commented on pkg/sql/colexec/projection.go
> +		reuse.Free[Projection](projection, nil)
只是感觉没必要再创造一个新的生命周期出来

2024-08-02 07:45 UTC, ouyuanning approved these changes

2024-08-02 07:51 UTC, zengyan1 commented
生命周期的问题暂不修改，后续会考虑去掉projection算子，其中的内容直接加入到其它算子中。

2024-08-02 09:01 UTC, iamlinjunhong approved these changes

2024-08-02 09:55 UTC, badboynt1 approved these changes

2024-08-02 17:26 UTC, fengttt approved these changes

2024-08-02 17:28 UTC, fengttt commented on pkg/sql/colexec/projection.go
> +		reuse.Free[Projection](projection, nil)
> 是的，比普通算子短。普通算子是在compile的时候从reuse拿出，projection是执行时prepare从reuse拿出。放回reuse都是free，project的free只会在普通算子的free中被调用，是同时的。 我不知道这样做是否有问题？

This is totally wrong.

2024-08-05 09:06 UTC, aunjgr approved these changes

2024-08-06 08:41 UTC, m-schen approved these changes

2024-08-06 13:50 UTC, merged