Refactor SubOperator Call
matrixorigin/matrixone pull request #17849
Opened 2024-08-01 10:10 UTC by qingxinhome

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue https://github.com/matrixorigin/matrixone/issues/17536

## What this PR does / why we need it:
Change the chain call method of the operator to:
vm.ChildrenCall(op.Children[0], proc, anal)

2024-08-02 01:54 UTC, badboynt1 approved these changes

2024-08-02 01:55 UTC, ouyuanning approved these changes

2024-08-02 05:44 UTC, m-schen approved these changes

2024-08-02 08:27 UTC, aunjgr requested changes

2024-08-02 08:27 UTC, aunjgr commented on pkg/sql/compile/types.go
> +func newAnaylzeModule() *anaylzeModule {
please fix the typo

2024-08-02 08:38 UTC, qingxinhome commented on pkg/sql/compile/types.go
> +func newAnaylzeModule() *anaylzeModule {
Okay, sorry, I was careless, haha

2024-08-02 14:16 UTC, XuPeng-SH approved these changes

2024-08-03 10:39 UTC, aunjgr approved these changes

2024-08-03 11:20 UTC, merged