Improve16 mb read
matrixorigin/matrixone pull request #17846
Opened 2024-08-01 09:09 UTC by CJKkkk-315

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [x] Code Refactoring

## Which issue(s) this PR fixes:

issue #12390  
https://github.com/matrixorigin/MO-Cloud/issues/3733
## What this PR does / why we need it:
在读取packet时加入了max_allow_packet判断
复用load local的read 内存
读取短query时不再使用alloc

2024-08-03 02:03 UTC, daviszhen requested changes

2024-08-03 02:03 UTC, daviszhen commented on pkg/frontend/mysql_buffer.go
> +	if c.allowedPacketSize == 0 {
如果allowedPacketSize 不可能等于0. 这个判断要去掉。

2024-08-03 02:03 UTC, daviszhen commented on pkg/frontend/mysql_buffer.go
>  func (c *Conn) Disconnect() error {
mysql_buffer.go 中的接口没有ut覆盖。需要增加ut.

2024-08-06 05:18 UTC, CJKkkk-315 commented on pkg/frontend/mysql_buffer.go
> +	if c.allowedPacketSize == 0 {
已去除

2024-08-06 05:19 UTC, CJKkkk-315 commented on pkg/frontend/mysql_buffer.go
>  func (c *Conn) Disconnect() error {
已增加mysql_buffer_test.go中的ut

2024-08-06 07:28 UTC, daviszhen approved these changes

2024-08-09 03:41 UTC, merged