remove MysqlResultSet.Name2Index
matrixorigin/matrixone pull request #17891
Opened 2024-08-05 09:06 UTC by CJKkkk-315

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [x] Code Refactoring

## Which issue(s) this PR fixes:

issue #12390 

## What this PR does / why we need it:

Removed Name2Idex from MysqlResultSet
Now, every operation related to Add or Remove Columns in MysqlResultSet requires corresponding map operation in Name2Idex. 
Additionally, creating MysqlResultSet and copying both require additional memory overhead to make (map).
But there are almost no scenarios where Name2Idex is necessary, removing it can optimize mem and CPU overhead.

2024-08-05 11:38 UTC, daviszhen requested changes

2024-08-05 11:38 UTC, daviszhen commented on pkg/stream/connector/converter.go
> +			val, err = obj.Value(ctx, uint64(i), uint64(j))
这地方用GetString把

2024-08-05 11:38 UTC, daviszhen commented on pkg/util/metric/mometric/cron_task.go
> +			if accountIdx, ok := name2idx[ColumnAccountName]; !ok {
如果show accounts 的结果列是固定的。accound，size,snapshotSize的位置是固定的。不用再建立map，每次查询了。直接定义成常量就可以了吧。

2024-08-05 11:38 UTC, daviszhen commented on pkg/util/metric/mometric/cron_task.go
> +			name2idx = make(map[string]uint64)
原因与上面类似。

2024-08-06 02:32 UTC, xzxiong commented on pkg/util/metric/mometric/cron_task.go
> +			if accountIdx, ok := name2idx[ColumnAccountName]; !ok {
代码逻辑需要调整。
1. 需要在 L209 行，完成对 accountIdx 和 sizeIdx 和 snapshotIdx 的计算，且只需要计算一次。
2. L221 行，直接取值，不判断是否存在，不允许默认值。（除了 snapshot_size字段）
3. 目前只有 snapshotSizeIdx 允许为 -1, 其他都必须存在。否则err return

前提条件：
1. account，size，snapshot_size 都是必须有的。
4. 可选的snapshot_size 只是版本过渡，便于mocloud 测试。

2024-08-06 02:32 UTC, xzxiong commented on pkg/util/metric/mometric/cron_task.go
>  		metric.StorageUsageFactory.Reset()
这一行需要挪到 name2idx 下边。

2024-08-06 02:33 UTC, xzxiong commented on pkg/util/metric/mometric/cron_task.go
> +		if name2idx == nil {
同上，accountIdx, sizeIdx, snapshotSizeIdx 仅需计算一次。

2024-08-06 03:42 UTC, xzxiong commented on pkg/util/metric/mometric/cron_task.go
>  		metric.StorageUsageFactory.Reset()
ref: https://github.com/CJKkkk-315/matrixone/pull/3

2024-08-06 03:42 UTC, xzxiong commented on pkg/util/metric/mometric/cron_task.go
> +		if name2idx == nil {
fixed by https://github.com/CJKkkk-315/matrixone/pull/3

2024-08-06 03:42 UTC, xzxiong commented on pkg/util/metric/mometric/cron_task.go
> +			if accountIdx, ok := name2idx[ColumnAccountName]; !ok {
fixed by https://github.com/CJKkkk-315/matrixone/pull/3

2024-08-06 07:27 UTC, daviszhen approved these changes

2024-08-06 10:03 UTC, xzxiong approved these changes

2024-08-06 10:16 UTC, aptend approved these changes

2024-08-07 03:55 UTC, fengttt requested changes
I don't have any clue what is this, why we need it, and what benefit we will see from this.

Need a better commit message.   Explaining.    If any "real" benefit, there should be test to show off it.

2024-08-07 04:33 UTC, CJKkkk-315 commented
> I don't have any clue what is this, why we need it, and what benefit we will see from this.
> 
> Need a better commit message. Explaining. If any "real" benefit, there should be test to show off it.

A more detailed explanation has been provided in "What this PR does / why we need it"

2024-08-12 16:33 UTC, fengttt approved these changes

2024-08-12 17:19 UTC, merged