refactor: preinsertunique
matrixorigin/matrixone pull request #17929
Opened 2024-08-07 07:39 UTC by huby2358

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [x] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2024-08-07 10:06 UTC, ouyuanning approved these changes

2024-08-07 10:37 UTC, badboynt1 approved these changes

2024-08-08 01:16 UTC, fengttt commented on pkg/sql/colexec/preinsertsecondaryindex/preinsertsecondaryindex.go
> +		vec := proc.GetVector(*inputBat.Vecs[pos].GetType())
You cannot use this

2024-08-08 01:18 UTC, fengttt commented on pkg/sql/colexec/preinsertsecondaryindex/preinsertsecondaryindex.go
> +	vec = proc.GetVector(*inputBat.Vecs[pkPos].GetType())
This too.    If you really need a vector, not a batch, put the vector in your ctr.   Do not lose it.   Make a comment in types.go Use it, reuse it, and free it at the right time.

2024-08-08 01:20 UTC, fengttt requested changes
get rid of the pointer of ctr.   Useless pointer.

You still have PutBatch, which is completely wrong.

2024-08-08 08:06 UTC, ouyuanning commented
> get rid of the pointer of ctr. Useless pointer.
> 
> You still have PutBatch, which is completely wrong.

seems done

2024-08-08 08:06 UTC, merged