refactor Innerjoin
matrixorigin/matrixone pull request #17927
Opened 2024-08-07 05:52 UTC by zengyan1

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2024-08-07 06:13 UTC, fengttt commented on pkg/sql/colexec/join/types.go
> +		proc.PutBatch(ctr.bat)
Said, nobody can use PutBatch/GetBatch anymore.

2024-08-07 06:15 UTC, badboynt1 requested changes

2024-08-07 06:15 UTC, badboynt1 commented on pkg/sql/colexec/join/types.go
>  		proc.PutBatch(ctr.rbat)
所有的putbatch都要删掉

2024-08-07 06:15 UTC, badboynt1 commented on pkg/sql/colexec/join/types.go
> +	ctr.cleanBatch(proc)
reset函数里应该不用cleanbatch  因为下次重新执行是可以复用的

2024-08-07 06:15 UTC, fengttt requested changes
So you missed the point of this change.

1. You are NOT allowed to use PutBatch and GetBatch,
2. Hold the batch in your ctr, as member.
3. Make sure you understand life span of batches.   
4.

2024-08-07 06:21 UTC, ouyuanning commented on pkg/sql/colexec/join/types.go
> +	}
innerJoin.ctr.maxAllocSize reset的时候要充值为0

2024-08-07 06:21 UTC, ouyuanning commented on pkg/sql/colexec/join/types.go
> +	ctr.cleanBatch(proc)
那3个batch的生命周期我不太了解，如果是一直存在的，看prepare甚至new算子的时候是否可以先new出来？

2024-08-07 10:13 UTC, ouyuanning approved these changes

2024-08-07 10:13 UTC, ouyuanning commented
UT补一下

2024-08-08 00:36 UTC, fengttt commented on pkg/sql/colexec/join/join.go
> +			result.Batch, err = innerJoin.EvalProjection(result.Batch, proc)
Can you do this?   You destroyed result.Batch,

2024-08-08 00:37 UTC, fengttt commented on pkg/sql/colexec/join/join.go
> +				return result, err
Let's not reuse result.   Create more confusion than necessary.   Why don't you name the result from child's call `input` and use `result` for output of the operator?

2024-08-08 00:38 UTC, fengttt commented on pkg/sql/colexec/join/join.go
> +				ctr.rbat.Vecs[i] = proc.GetVector(*ap.ctr.bat.Vecs[rp.Pos].GetType())
You will not use GetVector either.   Remove that crap.

2024-08-08 00:40 UTC, fengttt commented on pkg/sql/colexec/join/types.go
> +	ctr.batches = nil  // reset/free in hashmap
About this one.   Too.

2024-08-08 00:41 UTC, fengttt commented on pkg/sql/colexec/join/types.go
> +	ctr.bat = nil      // children[0] clean
Bad idea -- why you want to release ctr.bat?   Is ctr.bat created in join?

2024-08-08 03:03 UTC, zengyan1 commented on pkg/sql/colexec/join/join.go
> +			result.Batch, err = innerJoin.EvalProjection(result.Batch, proc)
result.Batch只是一个指针，其内容在ctr.rbat中

2024-08-08 03:03 UTC, zengyan1 commented on pkg/sql/colexec/join/join.go
> +				return result, err
已修改

2024-08-08 03:03 UTC, zengyan1 commented on pkg/sql/colexec/join/join.go
> +				ctr.rbat.Vecs[i] = proc.GetVector(*ap.ctr.bat.Vecs[rp.Pos].GetType())
已修改

2024-08-08 03:06 UTC, zengyan1 commented on pkg/sql/colexec/join/types.go
> +	ctr.bat = nil      // children[0] clean
这里没有release，只是为下次execute给一个nil的初值，ctr.bat和ctr.batches不在join中创建

2024-08-08 03:10 UTC, zengyan1 commented
以下是对ctr中几个bat的解释，已添加在join/types.go中 
```
1. batches means the data of right table. It's created by HashBuild operator and cleaned by cleanHashMap() in InnerJoin.Reset().
2. inbat means the data of left table. It's created by InnerJoin.Children[0] and cleaned by InnerJoin.Children[0].
3. rbat means the result of InnerJoin. InnerJoin.Probe() create rbat once when it's called first time and use CleanOnlyData() after that.
   InnerJoin.Reset() doesn't need to reset or clean rbat, because the result always has same types. InnerJoin.Free() will clean rbat.
4. joinBat1 means some data from left table used to evaluate join conditions. InnerJoin.Probe() create joinBat1 once.
   joinBat1 will always be overwritten by colexec.SetJoinBatchValues().
   InnerJoin.Reset() doesn't need to reset or clean joinBat1. InnerJoin.Free() will clean joinBat1.
5. joinBat2 means some data from right table, same as joinBat1.
```

2024-08-08 04:40 UTC, fengttt commented on pkg/sql/colexec/join/types.go
> +1. batches means the data of right table. It's created by HashBuild operator and cleaned by cleanHashMap() in InnerJoin.Reset().
If it is created by HashBuild, why do we need to clean in InnerJoin.Reset()?   Should HashBuild clean it?

2024-08-08 05:43 UTC, badboynt1 commented on pkg/sql/colexec/join/types.go
> +1. batches means the data of right table. It's created by HashBuild operator and cleaned by cleanHashMap() in InnerJoin.Reset().
hashbuild不能clean这部分数据，因为probe的时候还要访问。 这部分数据和hash表一起封装到joinmapMsg里面，通过引用计数来管理，引用计数为0时才能释放。

2024-08-08 06:32 UTC, zengyan1 commented on pkg/sql/colexec/join/types.go
> +		proc.PutBatch(ctr.bat)
已删除

2024-08-08 06:32 UTC, zengyan1 commented on pkg/sql/colexec/join/types.go
>  		proc.PutBatch(ctr.rbat)
已删除

2024-08-08 06:32 UTC, zengyan1 commented on pkg/sql/colexec/join/types.go
> +	ctr.cleanBatch(proc)
已修改

2024-08-08 06:33 UTC, zengyan1 commented on pkg/sql/colexec/join/types.go
> +	ctr.batches = nil  // reset/free in hashmap
同下

2024-08-08 06:45 UTC, zengyan1 commented
已删除ctr.batches，改为从joinmap直接访问

2024-08-08 06:49 UTC, badboynt1 approved these changes

2024-08-08 15:40 UTC, ouyuanning commented on pkg/vm/message/joinMapMsg.go
> +	return jm.Batches
已经有GetBatches() 方法了，没必要修改这里的batches成public的啊

2024-08-09 02:21 UTC, zengyan1 commented on pkg/vm/message/joinMapMsg.go
> +	return jm.Batches
已修改

2024-08-09 03:39 UTC, merged