T6
matrixorigin/matrixone pull request #18025
Opened 2024-08-09 06:41 UTC by huby2358

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [x] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2024-08-09 06:56 UTC, m-schen commented on pkg/container/vector/vector.go
> +		v.class = CONSTANT
啊？ 这是笔误动到了吗

不能在这里修改v的类型和长度。

2024-08-09 08:24 UTC, ouyuanning approved these changes

2024-08-09 13:49 UTC, ouyuanning requested changes

2024-08-09 13:49 UTC, ouyuanning commented on pkg/sql/colexec/preinsert/preinsert.go
> +		preInsert.ctr.buf.SetRowCount(0)
这里为什么没有把bat的值放入buf啊？是不是漏了。
应该有个地方，把bat的值放入buf，并且当时自增的话，做一次拷贝

2024-08-12 07:39 UTC, ouyuanning commented on pkg/sql/colexec/preinsert/preinsert.go
> +				preInsert.ctr.buf.Vecs[i].Free(proc.Mp())
在第一次执行的时候。这个地方应该 Vecs[i] 是nil 的，应该会panic。所以感觉
1、可能要加一下对应UT确认下
2、可能在这里要加一下注释，估计别人会看不懂

2024-08-13 08:18 UTC, daviszhen approved these changes

2024-08-13 09:53 UTC, ouyuanning commented on pkg/sql/colexec/preinsert/preinsert.go
> +		preInsert.ctr.buf.SetRowCount(0)
这里确认下，要不要重设一下preInsert.ctr.buf.Vecs的长度为len(preInsert.Attrs)

2024-08-13 12:22 UTC, ouyuanning approved these changes

2024-08-13 12:22 UTC, merged