Ensure websocket is closed
matrixorigin/matrixone pull request #18276
Opened 2024-08-22 03:55 UTC by CJKkkk-315

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #17668 

## What this PR does / why we need it:
1.Fix bug where frontend socket is not closed
2.Change the Close function of *Conn to sync.Once to prevent errors caused by concurrency

2024-08-22 07:01 UTC, zhangxu19830126 requested changes

2024-08-22 07:01 UTC, zhangxu19830126 commented on pkg/frontend/server.go
> +	setMoServerStarted(false)
cannot use global var.  Because of the possibility of concurrently stopping and starting multiple cn

2024-08-22 07:09 UTC, CJKkkk-315 commented on pkg/frontend/server.go
> +	setMoServerStarted(false)
好的，我先将这行代码删除与原先逻辑保持一致。
Frontend端没有用到这个全局变量，唯一用到的地方是initTraceMetric，相关代码我不是很熟悉

2024-08-23 06:24 UTC, zhangxu19830126 approved these changes

2024-08-24 03:55 UTC, merged