[fix] : remove meaningless panic of mpool.Alloc
matrixorigin/matrixone pull request #18329
Opened 2024-08-26 03:20 UTC by jensenojs

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #18240 https://github.com/matrixorigin/MO-Cloud/issues/3928

## What this PR does / why we need it:

At present, the problems of the mpool framework itself can lead to meaningless oom situations.

2024-08-26 03:29 UTC, m-schen approved these changes

2024-08-26 03:38 UTC, reusee approved these changes

2024-08-26 03:40 UTC, jensenojs commented
再先起一个Regression看一下

 https://github.com/matrixorigin/ci-test/actions/runs/10553141991

2024-08-26 21:02 UTC, fengttt requested changes
please close this pr.

2024-08-27 03:44 UTC, fengttt approved these changes

2024-08-27 06:19 UTC, sukki37 approved these changes

2024-08-27 08:21 UTC, merged