Fix Floor/Ceil/Round Decimal
matrixorigin/matrixone pull request #18404
Opened 2024-08-29 11:54 UTC by zengyan1

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue https://github.com/matrixorigin/MO-Cloud/issues/3955

## What this PR does / why we need it:
Fix Floor/Ceil/Round Decimal

2024-08-29 16:52 UTC, fengttt requested changes
no test?

2024-08-30 02:13 UTC, m-schen approved these changes

2024-08-30 02:14 UTC, aunjgr approved these changes

2024-08-30 05:29 UTC, fengttt approved these changes

2024-08-30 09:55 UTC, heni02 approved these changes

2024-08-30 09:55 UTC, badboynt1 approved these changes

2024-08-31 02:47 UTC, XuPeng-SH approved these changes

2024-08-31 03:41 UTC, merged