refactoring dispatch scopes
matrixorigin/matrixone pull request #18462
Opened 2024-08-31 09:56 UTC by badboynt1

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [x] Code Refactoring

## Which issue(s) this PR fixes:

issue #16542 

## What this PR does / why we need it:
refactoring dispatch scopes

2024-08-31 09:58 UTC, badboynt1 commented
https://github.com/matrixorigin/ci-test/actions/runs/10644016017

2024-08-31 10:18 UTC, ouyuanning approved these changes

2024-08-31 17:06 UTC, fengttt requested changes
You need to have a better PR/commit message.

Refactor, how, what is the result?   What is it different from old code?

2024-09-01 09:40 UTC, aunjgr approved these changes

2024-09-01 22:41 UTC, fengttt approved these changes

2024-09-02 12:50 UTC, badboynt1 commented
https://github.com/matrixorigin/ci-test/actions/runs/10667480578

2024-09-02 12:57 UTC, sukki37 approved these changes

2024-09-03 02:51 UTC, heni02 approved these changes

2024-09-03 23:41 UTC, merged