adding flag to block info and object info
matrixorigin/matrixone pull request #18527
Opened 2024-09-04 10:15 UTC by gouhongshen

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #https://github.com/matrixorigin/matrixone/issues/11471

## What this PR does / why we need it:
flag:
1. dependable
2. sorted
3. by cn created.

2024-09-05 01:28 UTC, daviszhen requested changes
确定要这2个文件吗？ 如果是临时生成的，就去掉吧

2024-09-05 01:53 UTC, gouhongshen commented
> 确定要这2个文件吗？ 如果是临时生成的，就去掉吧
> 
> pkg/frontend/test/.tmp.389153650

删了

2024-09-05 06:28 UTC, ouyuanning approved these changes

2024-09-05 06:39 UTC, daviszhen approved these changes

2024-09-05 07:13 UTC, aunjgr approved these changes

2024-09-07 06:23 UTC, m-schen approved these changes

2024-09-07 09:44 UTC, XuPeng-SH approved these changes

2024-09-07 09:48 UTC, LeftHandCold approved these changes

2024-09-07 09:53 UTC, triump2020 approved these changes

2024-09-08 06:05 UTC, merged