Support Explain Cross Apply
matrixorigin/matrixone pull request #18679
Opened 2024-09-10 06:32 UTC by zengyan1

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #10060

## What this PR does / why we need it:
Support Explain Cross Apply

2024-09-10 07:49 UTC, aunjgr requested changes

2024-09-10 09:01 UTC, badboynt1 commented on pkg/sql/compile/operator.go
> +		t := sourceOp.(*apply.Apply)
also need to implement convertToVMInstruction and convertToPipelineInstruction

2024-09-10 11:36 UTC, m-schen approved these changes

2024-09-10 12:25 UTC, zengyan1 commented on pkg/sql/plan/query_builder.go
> +		TblFuncExprList: builder.qry.Nodes[rightChildID].TblFuncExprList,
已删除，直接从child节点取

2024-09-11 02:26 UTC, aunjgr approved these changes

2024-09-11 03:13 UTC, iamlinjunhong approved these changes

2024-09-11 12:37 UTC, badboynt1 approved these changes

2024-09-12 07:38 UTC, XuPeng-SH approved these changes

2024-09-12 08:47 UTC, merged