Fix cdc bugs
matrixorigin/matrixone pull request #19058
Opened 2024-09-27 04:26 UTC by ck89119

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #19002 #19006 #19009 

## What this PR does / why we need it:
Fix cdc bugs

2024-09-27 06:52 UTC, daviszhen approved these changes

2024-09-27 06:53 UTC, daviszhen requested changes

2024-09-27 06:53 UTC, daviszhen commented on pkg/cdc/sinker.go
> +		select {
select 里面 ctx.Done 也加。

2024-09-27 06:56 UTC, ck89119 commented on pkg/cdc/sinker.go
> +		select {
OK

2024-09-28 12:08 UTC, daviszhen approved these changes

2024-09-30 03:16 UTC, zhangxu19830126 approved these changes

2024-09-30 03:16 UTC, aptend approved these changes

2024-09-30 16:28 UTC, merged