fix group concat without data
matrixorigin/matrixone pull request #19777
Opened 2024-11-04 09:37 UTC by iamlinjunhong

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #19743

## What this PR does / why we need it:

fix group concat without data

2024-11-04 13:37 UTC, sukki37 requested changes
please add bvt cases

2024-11-05 02:41 UTC, m-schen approved these changes

2024-11-05 06:59 UTC, heni02 approved these changes

2024-11-05 07:39 UTC, sukki37 approved these changes

2024-11-05 09:40 UTC, merged