refactor: compileProjection
matrixorigin/matrixone pull request #19799
Opened 2024-11-05 07:44 UTC by huby2358

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [x] Code Refactoring

## Which issue(s) this PR fixes:

issue # https://github.com/matrixorigin/matrixone/issues/19769

## What this PR does / why we need it:
1.把曾言之前对Projection的支持放开

2024-11-21 07:08 UTC, ouyuanning approved these changes

2024-11-21 13:03 UTC, qingxinhome requested changes
table_scan 算子的：
analyzer.Start()
analyzer.Stop()
analyzer.Output(retBatch)都要移到外部

2024-11-22 01:24 UTC, qingxinhome requested changes
order 算子的analyzer.Output(result.Batch)需要移除

2024-11-22 01:25 UTC, qingxinhome requested changes
lockOp算子的analyzer.Start()
	defer analyzer.Stop()
      也需要移到Exec中

2024-11-22 06:23 UTC, qingxinhome approved these changes

2024-11-22 06:27 UTC, heni02 approved these changes

2024-11-22 06:30 UTC, XuPeng-SH approved these changes

2024-11-22 06:34 UTC, m-schen approved these changes

2024-11-22 06:39 UTC, badboynt1 approved these changes

2024-11-23 16:16 UTC, merged