restore statement CU resource statistics
matrixorigin/matrixone pull request #20010
Opened 2024-11-12 12:07 UTC by qingxinhome

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue https://github.com/matrixorigin/MO-Cloud/issues/3761

## What this PR does / why we need it:
The restore snapshot and restore pitr statements support CU resource statistics

2024-11-13 09:54 UTC, daviszhen requested changes

2024-11-13 09:54 UTC, daviszhen commented on pkg/frontend/back_exec.go
> +	statsArray *statistic.StatsArray
在backExec.Close时，要及时清理掉。

2024-11-13 09:55 UTC, daviszhen commented on pkg/frontend/back_exec.go
> +	statsArray *statistic.StatsArray
跑下短链接测试 ，看会不会oom：https://github.com/daviszhen/morunner/blob/main/README.md#%E6%B5%8B%E8%AF%95oom

2024-11-14 02:43 UTC, qingxinhome commented on pkg/frontend/back_exec.go
> +	statsArray *statistic.StatsArray
进行10分钟的短连接测试， 内存使用没有超过1.8G, @daviszhen

2024-11-14 02:49 UTC, daviszhen approved these changes

2024-11-14 07:20 UTC, reusee approved these changes

2024-11-14 07:21 UTC, m-schen approved these changes

2024-11-14 07:39 UTC, heni02 approved these changes

2024-11-14 08:00 UTC, badboynt1 approved these changes

2024-11-14 10:07 UTC, aunjgr approved these changes

2024-11-14 12:15 UTC, merged