fileservice: refactor http trace
matrixorigin/matrixone pull request #20177
Opened 2024-11-19 07:04 UTC by reusee

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #20129 

## What this PR does / why we need it:
refactor HTTP trace to reduce cost.

2024-11-20 06:42 UTC, aptend approved these changes

2024-11-20 07:08 UTC, zhangxu19830126 approved these changes

2024-11-20 08:19 UTC, fengttt requested changes
What exactly is the change?   
Do we have a number of how much/big is the improvement?

2024-11-20 21:10 UTC, fengttt approved these changes

2024-11-21 02:00 UTC, sukki37 approved these changes

2024-11-21 03:59 UTC, merged