[MatrixCamp] add function cos()
matrixorigin/matrixone pull request #2022
Opened 2022-03-26 12:40 UTC by yclchuxue

**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #1967

**What this PR does / why we need it:**

implement Cos builtin function

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

2022-03-26 12:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/matrixorigin/matrixone?pullRequest=2022) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/matrixorigin/matrixone?pullRequest=2022) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/matrixorigin/matrixone?pullRequest=2022) it.</sub>

2022-03-28 06:08 UTC, broccoliSpicy commented on pkg/builtin/unary/cos.go
> +package unary
please add the license header

2022-03-29 02:56 UTC, broccoliSpicy requested changes

2022-03-30 04:09 UTC, yingfeng commented
Pls resolve the confliction before it's merged

2022-03-31 12:35 UTC, yingfeng requested changes
Pls fix confliction caused by other merged PRs and make sure it could work with latest main

2022-03-31 13:58 UTC, merged