Builtin ltrim rtrim
matrixorigin/matrixone pull request #2027
Opened 2022-03-27 11:09 UTC by jiajunhuang

**What type of PR is this?**

- [x] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #https://github.com/matrixorigin/matrixone/issues/1985
issue #https://github.com/matrixorigin/matrixone/issues/1987

**What this PR does / why we need it:**

Implement `ltrim` and `rtrim`

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

2022-03-27 11:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/matrixorigin/matrixone?pullRequest=2027) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/matrixorigin/matrixone?pullRequest=2027) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/matrixorigin/matrixone?pullRequest=2027) it.</sub>

2022-03-28 05:36 UTC, broccoliSpicy approved these changes
spectacular code...

2022-03-28 07:40 UTC, broccoliSpicy requested changes

2022-03-28 07:40 UTC, broccoliSpicy commented on pkg/builtin/unary/ltrim.go
> +				totalCount := int32(len(origVecCol.Data))
perhaps we could reuse the original vector when possible

2022-03-28 07:49 UTC, broccoliSpicy commented on pkg/builtin/unary/ltrim.go
> +				totalCount := int32(len(origVecCol.Data))
huh, if we reuse the original vector, it kind of like using double points to change a []types.bytes in place, then I guess we need a different implementation for this trim function, perhaps we could skip this "vector reuse procedure" to make our implementation easier

2022-03-28 07:50 UTC, broccoliSpicy approved these changes

2022-03-29 11:27 UTC, domingozhang reviewed
bvt passwd

2022-03-29 13:05 UTC, merged