refactoring shuffle plan[step 1]
matrixorigin/matrixone pull request #20561
Opened 2024-12-04 09:40 UTC by badboynt1

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [x] Code Refactoring

## Which issue(s) this PR fixes:

issue #20560 

## What this PR does / why we need it:
refactoring shuffle plan, support shuffle group on single cn

2024-12-05 03:20 UTC, m-schen approved these changes

2024-12-05 03:36 UTC, ouyuanning approved these changes

2024-12-05 06:49 UTC, XuPeng-SH approved these changes

2024-12-05 18:34 UTC, fengttt requested changes

2024-12-05 18:34 UTC, fengttt commented on pkg/sql/colexec/shuffleV2/shuffle.go
> +func getShuffledSelsByHashWithNull(ap *ShuffleV2, bat *batch.Batch) [][]int32 {
What is the difference between WithNull and WithoutNull?

And it is much better to have a hashable generics based on types.T

2024-12-05 18:35 UTC, fengttt commented on pkg/sql/colexec/shuffleV2/shuffle.go
> +func getShuffledSelsByHashWithNull(ap *ShuffleV2, bat *batch.Batch) [][]int32 {
So should be later by range, I think what you need is a comparable generics.

2024-12-06 02:59 UTC, qingxinhome approved these changes

2024-12-06 03:56 UTC, fengttt approved these changes

2024-12-06 07:56 UTC, merged