Checking TCP connection status
matrixorigin/matrixone pull request #20996
Opened 2024-12-27 10:14 UTC by QCSnAn

Added the ability to check the status of TCP connections and abort tasks based on the status.

2024-12-27 10:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/matrixorigin/matrixone?pullRequest=20996) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/matrixorigin/matrixone?pullRequest=20996) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/matrixorigin/matrixone?pullRequest=20996) it.</sub>

2025-01-06 09:28 UTC, daviszhen requested changes

2025-01-06 09:28 UTC, daviszhen commented on pkg/frontend/server.go
> +const checkInterval = 1
看下FronendParameters

2025-01-08 05:03 UTC, daviszhen approved these changes

2025-01-09 06:38 UTC, volgariver6 approved these changes

2025-01-09 06:42 UTC, volgariver6 requested changes

2025-01-09 06:42 UTC, volgariver6 commented on pkg/frontend/server.go
> +func GetsockoptTCPInfo(tcpConn *net.TCPConn, tcpInfo *syscall.TCPInfo) (uint8, error) {
syscall.TCPInfo 在 MacOS 系统中没有，请使用可以跨平台的方式获取信息

2025-01-15 02:19 UTC, QCSnAn reviewed
将与syscall.TCPInfo相关的内容移到tcpconn.go文件中并在开头加入构建约束只有linux系统才能对其进行编译以此让MacOS绕开syscall.TCPInfo

2025-01-15 03:04 UTC, volgariver6 commented on pkg/frontend/linuxonly/tcpconn.go
linuxonly 这个包名字不好，改掉，比如改成 tcpconn，然后里面的文件名字为 linux.go 和 macos.go

2025-01-15 06:28 UTC, volgariver6 approved these changes

2025-01-17 08:22 UTC, fengttt approved these changes

2025-02-10 06:52 UTC, merged