[MatrixCamp] Add built-in function lengthUTF8
matrixorigin/matrixone pull request #2280
Opened 2022-04-24 08:58 UTC by coderzc

**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #2116 

**What this PR does / why we need it:**

Add string lengthUTF8(str) built-in function

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

2022-04-24 08:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/matrixorigin/matrixone?pullRequest=2280) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/matrixorigin/matrixone?pullRequest=2280) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/matrixorigin/matrixone?pullRequest=2280) it.</sub>

2022-04-25 06:50 UTC, broccoliSpicy approved these changes
LGTM

2022-04-26 02:30 UTC, domingozhang commented
BVT passed

2022-04-26 02:57 UTC, yingfeng requested changes
This implementation is too naive and not efficient. From now on, any string relevant built-in functions should be able to provide algorithms to guarantee the necessary performance. 
Some references:
[ref1](https://github.com/StarRocks/starrocks/blob/main/be/src/util/utf8.h)
[ref2](https://github.com/satanson/cpp_etudes/blob/master/include/string_functions.hh)
you may not provide the simd acceleration, but even the naive version should not just be a simple call on the golang system functions.

2022-04-27 01:07 UTC, coderzc commented
> efficient

Thank you for your advice. I have provided the optimized algorithm implementation, please review it again.

2022-04-27 01:08 UTC, coderzc commented
> This implementation is too naive and not efficient. From now on, any string relevant built-in functions should be able to provide algorithms to guarantee the necessary performance. Some references: [ref1](https://github.com/StarRocks/starrocks/blob/main/be/src/util/utf8.h) [ref2](https://github.com/satanson/cpp_etudes/blob/master/include/string_functions.hh) [ref3](https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/UTF8Helpers.h) you may not provide the simd acceleration, but even the naive version should not just be a simple call on the golang system functions.

Thank you for your advice. I have provided the optimized algorithm implementation, please review it again.

2022-04-27 07:17 UTC, broccoliSpicy commented on pkg/vectorize/lengthutf8/length_utf8.go
> +// this countUTF8CodePoints implement bases on https://bjoern.hoehrmann.de/utf-8/decoder/dfa/
// this countUTF8CodePoints implementation, should be a noun

2022-04-27 07:18 UTC, broccoliSpicy approved these changes
cool

2022-04-29 06:26 UTC, yingfeng approved these changes

2022-04-29 06:31 UTC, broccoliSpicy approved these changes
neat

2022-04-29 06:31 UTC, aunjgr approved these changes
The code looks great to me.

2022-04-29 06:34 UTC, merged