restructure the compare operation function to improve the execute speed
matrixorigin/matrixone pull request #3222
Opened 2022-06-22 08:41 UTC by jianwan0214

**What type of PR is this?**

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #3164 

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

2022-06-22 12:12 UTC, yingfeng requested changes
Remove log.txt from PR

2022-06-23 05:35 UTC, nnsgmsone commented on pkg/sql/plan2/function/operator/and.go
> +	for i := range vcols {
this cycle is a bit inefficient

2022-06-23 07:23 UTC, nnsgmsone approved these changes

2022-06-23 07:23 UTC, nnsgmsone commented
and and or could ideally be rewritten, and this should be documented. The current implementation is not very efficient.

2022-06-23 07:27 UTC, merged