support text type
matrixorigin/matrixone pull request #4168
Opened 2022-07-22 05:12 UTC by bbbearxyz

**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #3602

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

2022-07-22 07:53 UTC, bbbearxyz commented on pkg/sql/plan/build_util.go
> +			//if len(v) > math.MaxUint16 {
ok, i will look mysql and confirm it.

2022-07-26 07:34 UTC, bbbearxyz commented on pkg/sql/plan/build_util.go
> +			//if len(v) > math.MaxUint16 {
now I check: in the mysql, text and blob difference are blob_type, but text have charset for example utf8 and blob type only have binary charset. If we want to add blob type in the future, we only set the charset is binary and return to the mysql-client

2022-07-26 08:50 UTC, daviszhen requested changes
In this big pr, many files have been updated. But there are neither ut nor bvt cases to verify the rightness. 
the ut and bvt cases are indispensible.

2022-07-28 11:10 UTC, daviszhen approved these changes

2022-07-29 08:49 UTC, merged