support load data from s3
matrixorigin/matrixone pull request #4173
Opened 2022-07-22 08:08 UTC by jianwan0214

**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #3421 

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

2022-07-22 08:13 UTC, daviszhen approved these changes

2022-07-22 10:04 UTC, reusee approved these changes

2022-07-23 06:49 UTC, fengttt requested changes
You are missing two important things,
1. A design doc on the load option and url syntax.
2. A bvt test

While you marked this PR is WIP, the two things should come before coding.

2022-07-25 02:50 UTC, jianwan0214 commented
> You are missing two important things,
> 
> 1. A design doc on the load option and url syntax.
> 2. A bvt test
> 
> While you marked this PR is WIP, the two things should come before coding.

sure

2022-08-08 11:11 UTC, closed without merging