A tricky way to modify the engine interface
matrixorigin/matrixone pull request #4196
Opened 2022-07-25 06:35 UTC by nnsgmsone

**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #3591

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

2022-07-25 08:21 UTC, fengttt reviewed
My eyes!    So all it does, is to add a ctx parameter, is this true?

2022-07-25 08:29 UTC, nnsgmsone commented
> My eyes! So all it does, is to add a ctx parameter, is this true?

replace engine.Snapshot with client.TxnOperator

2022-07-25 08:32 UTC, yingfeng requested changes

2022-07-25 08:32 UTC, yingfeng commented on pkg/vm/engine/types.go
> +	IsHide bool
IsHide => IsHidden

2022-07-25 08:34 UTC, nnsgmsone commented on pkg/vm/engine/types.go
> +	IsHide bool
ok

2022-07-25 08:46 UTC, yingfeng approved these changes

2022-07-25 15:49 UTC, fengttt commented
> 
> > My eyes! So all it does, is to add a ctx parameter, is this true?
> 
> replace engine.Snapshot with client.TxnOperator

I approved this PR.   However, this kind of change/reason etc, really should be in your commit message as well as PR decription.

2022-07-25 15:49 UTC, fengttt approved these changes

2022-07-26 01:04 UTC, nnsgmsone commented
> I approved this PR. However, this kind of change/reason etc, really should be in your commit message as well as PR decription.

ok

2022-07-26 01:19 UTC, yingfeng commented
Fix sca

2022-07-26 01:56 UTC, nnsgmsone commented
> Fix sca

fixed

2022-07-26 02:11 UTC, merged