add Minus operator
matrixorigin/matrixone pull request #4256
Opened 2022-07-28 09:38 UTC by m-schen

**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #4094 

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

2022-07-29 01:38 UTC, fengttt commented on pkg/sql/colexec/minus/minus.go
> +		// aligning the decimal precision
Decimal does not need to be aligned any more.

2022-07-29 01:40 UTC, fengttt requested changes
Can please you comment in minus.go, describe what you do.   How do you do bookkeeping in the hashtable, etc.

This kind a change should have a bvt test case.

2022-07-29 02:53 UTC, m-schen commented
> Can please you comment in minus.go, describe what you do. How do you do bookkeeping in the hashtable, etc.
> 
> This kind a change should have a bvt test case.

I have described how I did it in the comments of the call function.  
i will make a doc to describe how to use the hashtable next week.
this pr can not have bvt test because it is just an operator implement but without plan build. it is hard to do test end to end.

2022-07-29 03:30 UTC, nnsgmsone commented on pkg/sql/colexec/minus/minus.go
> +			vs, _ := itr.Insert(i, n, bat.Vecs, ctr.scales[index])
The likelihood of doing so would be very low and I would advise against it.

2022-08-02 03:39 UTC, m-schen commented
I've added comments to the minus.go file to describe how I do the minus work and removed the useless scalar related work. And bvt test can't be done at now because it is just an operator implement but without plan built.

I will push a hash table related doc today but not this pull request.

2022-08-02 07:55 UTC, m-schen commented
I will make another pull request first, to reduce the cost of learning to use hash tables.
and change related codes about the use of hash table at this pr.

2022-08-02 10:10 UTC, m-schen commented
> I want to make another pull request first, to reduce the cost of learning to use hash tables.
> and change related codes about the use of hash table at this pr.

2022-08-03 02:22 UTC, closed without merging