refactor insert values and default expr
matrixorigin/matrixone pull request #4346
Opened 2022-08-03 06:31 UTC by iamlinjunhong

**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

issue #3202 

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

2022-08-03 08:14 UTC, daviszhen requested changes

2022-08-03 08:16 UTC, iamlinjunhong commented on pkg/sql/compile/compile.go
> +	case *plan.Plan_Ins:
plan_query will build pipeline, i don't want to add this logic.

2022-08-03 08:16 UTC, iamlinjunhong commented on pkg/frontend/mysql_cmd_executor.go
> +		if _, ok := s.Rows.Select.(*tree.ValuesClause); ok {
it will optimized when insert select

2022-08-03 08:17 UTC, iamlinjunhong commented on pkg/sql/plan/default_binder.go
> +func (b *DefaultBinder) BindExpr(astExpr tree.Expr, depth int32, isRoot bool) (*plan.Expr, error) {
it need, like TableBinder

2022-08-03 08:25 UTC, LeftHandCold approved these changes
lgtm

2022-08-03 09:50 UTC, aressu1985 approved these changes

2022-08-03 11:04 UTC, daviszhen commented on pkg/sql/compile/compile.go
> +	case *plan.Plan_Ins:
Does the `insert into select from` have the pipeline ?

2022-08-03 13:17 UTC, daviszhen commented on pkg/sql/compile/compile.go
> +	case *plan.Plan_Ins:
Does the 'insert values' share the logic with the 'insert select'?

2022-08-03 13:59 UTC, iamlinjunhong commented on pkg/sql/compile/compile.go
> +	case *plan.Plan_Ins:
doesn't share. They build plan with different way. They are different logic to generate batch data that insert.

2022-08-04 01:32 UTC, ouyuanning approved these changes

2022-08-04 01:36 UTC, daviszhen approved these changes

2022-08-04 01:36 UTC, nnsgmsone approved these changes

2022-08-04 03:57 UTC, merged