add_0.5.1_releasenote and update_what'new/timeline and add new doc_up…
matrixorigin/matrixone pull request #4413
Opened 2022-08-08 03:57 UTC by lacrimosaprinz

…date_mo

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [x] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2022-08-19 02:59 UTC, dengn requested changes

2022-08-19 02:59 UTC, dengn commented on docs/cn/MatrixOne/Get-Started/update-standalone-matrixone.md
> +MatrixOne 可以通过以下三种方法进行升级：
Add description about this is only about in-0.5 version update. Not for 0.4/0.3/0.2/0.1 -> 0.5 version update.

2022-08-19 03:20 UTC, dengn requested changes

2022-08-19 03:20 UTC, dengn commented on docs/en/MatrixOne/Get-Started/update-standalone-matrixone.md
> +
same for english version

2022-08-19 03:28 UTC, dengn approved these changes

2022-08-20 00:43 UTC, guguducken commented
@mergifyio refresh

2022-08-20 00:49 UTC, fengttt commented
> @guguducken is not allowed to run commands

@mergifyio refresh

2022-08-20 00:53 UTC, fengttt commented
@mergifyio refresh

2022-08-20 01:22 UTC, fengttt commented
@mergifyio refresh

2022-08-20 01:41 UTC, merged