Add blob support in MO
matrixorigin/matrixone pull request #4472
Opened 2022-08-12 03:08 UTC by yjw1268

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #3418

## What this PR does / why we need it:
Add blob support in MO

2022-08-12 03:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/matrixorigin/matrixone?pullRequest=4472) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/matrixorigin/matrixone?pullRequest=4472) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/matrixorigin/matrixone?pullRequest=4472) it.</sub>

2022-08-12 12:47 UTC, nnsgmsone approved these changes

2022-08-17 04:15 UTC, fengttt requested changes
TAE types is gone.   You have to move types related stuff using container/types.

2022-08-18 02:11 UTC, zhangxu19830126 approved these changes

2022-08-18 09:17 UTC, XuPeng-SH approved these changes
lgtm

2022-08-19 09:22 UTC, fengttt approved these changes

2022-08-20 00:57 UTC, fengttt commented
@mergifyio refresh

2022-08-20 01:20 UTC, merged