implement general mark join
matrixorigin/matrixone pull request #4554
Opened 2022-08-17 09:21 UTC by JackTan25

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2022-08-17 13:39 UTC, JackTan25 commented
I don't know whose pr result in a conflict. Before I fix the conflict, this pr can pass all tests. But when I 'git pull upstream main' and fix the conflicts. It's failed. I don't know why.

2022-08-17 15:26 UTC, fengttt requested changes
Can you please add a bvt test, a few tests, join on a few different types int, decimal, string, etc that trigger this mark join?

2022-08-18 01:10 UTC, nnsgmsone requested changes

2022-08-18 01:10 UTC, nnsgmsone commented on pkg/sql/compile/compile.go
>  			if isEq && len(conds) == 1 {
Please change it to:
```
if isEq {

2022-08-18 01:10 UTC, nnsgmsone commented on pkg/sql/compile/compile.go
>  			if isEq && len(conds) == 1 {
mark join not anti join

2022-08-18 01:15 UTC, nnsgmsone commented
> Can you please add a bvt test, a few tests, join on a few different types int, decimal, string, etc that trigger this mark join?

bvt may not be necessary, as some of the subqueries in the original bvt I had handled with nested loop anti. These should now be handled with a hash mark join

2022-08-18 01:24 UTC, JackTan25 commented
> > Can you please add a bvt test, a few tests, join on a few different types int, decimal, string, etc that trigger this mark join?
> 
> bvt may not be necessary, as some of the subqueries in the original bvt I had handled with nested loop anti. These should now be handled with a hash mark join

ok

2022-08-18 03:35 UTC, fengttt commented
> > Can you please add a bvt test, a few tests, join on a few different types int, decimal, string, etc that trigger this mark join?
> 
> bvt may not be necessary, as some of the subqueries in the original bvt I had handled with nested loop anti. These should now be handled with a hash mark join

Best if you have a bvt test case, call it markjoin.sql/test, and have some queries that explicitly, surely trigger that code.   You may want to run explain of the query and check the output that it is indeed a mark join.

2022-08-18 06:57 UTC, nnsgmsone commented
> Best if you have a bvt test case, call it markjoin.sql/test, and have some queries that explicitly, surely trigger that code. You may want to run explain of the query and check the output that it is indeed a mark join.

Makes sense

2022-08-18 09:12 UTC, JackTan25 commented
wait，I need Jensen to modify the join_test, so please ignore the result of the CI

2022-08-18 09:13 UTC, closed without merging