Implement general Mark Join
matrixorigin/matrixone pull request #4581
Opened 2022-08-19 00:50 UTC by JackTan25

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2022-08-19 01:28 UTC, nnsgmsone requested changes

2022-08-19 01:28 UTC, nnsgmsone commented on pkg/sql/compile/compile.go
>  			if isEq && len(conds) == 1 {
Only mark join if len(conds)>1

2022-08-19 02:01 UTC, nnsgmsone commented
Realization of the existence of some problems.... Needs to be modified.

2022-08-19 02:58 UTC, nnsgmsone commented
Please handle multiple columns

2022-08-19 08:09 UTC, fengttt reviewed
Test, test test.

All new operators, should have a bvt test that triggers this operator.    explain and confirm this operator is activated.

2022-08-19 08:24 UTC, JackTan25 commented
> Test, test test.
> 
> All new operators, should have a bvt test that triggers this operator. explain and confirm this operator is activated.

ok, I got it

2022-08-20 08:42 UTC, JackTan25 commented
> Test, test test.
> 
> All new operators, should have a bvt test that triggers this operator. explain and confirm this operator is activated.

I have add mark join, please wait Jensen to add multi col feature.

2022-08-20 11:16 UTC, JackTan25 commented
> Test, test test.
> 
> All new operators, should have a bvt test that triggers this operator. explain and confirm this operator is activated.

I‘ve added the mark-join bvt test. Now please wait jensen to finish the multiple columns feature.

2022-08-24 04:17 UTC, fengttt reviewed
Can you add a explain call on bvt test case and grep the result to see if it is really a mark join ...

2022-08-24 05:32 UTC, JackTan25 commented
> Can you add a explain call on bvt test case and grep the result to see if it is really a mark join ...

For now plan, if join result is marked as null, we don't output.

2022-08-24 06:22 UTC, nnsgmsone commented on pkg/sql/colexec/mark/join.go
> +				for sel := 0; sel < ctr.bat.Length(); sel++ {
Please use the batch process.

2022-08-25 01:39 UTC, nnsgmsone commented on pkg/sql/colexec/mark/join.go
> +		ctr.nullWithBatch = DumpBatch(bat, proc, ctr.nullSels)
These two copies don't seem to make any sense, please delete them

2022-08-25 01:39 UTC, nnsgmsone commented on pkg/sql/compile/compile.go
> +			if isEq {
if len(conds) == 1, use anti join, only if len(conds) > 1, use mark join

2022-08-25 02:29 UTC, nnsgmsone approved these changes

2022-08-25 02:45 UTC, aressu1985 approved these changes

2022-08-25 02:58 UTC, merged