Support jq function
matrixorigin/matrixone pull request #4645
Opened 2022-08-23 13:11 UTC by mooleetzi

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [X] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #4644 

## What this PR does / why we need it:
Support query function for json type

2022-08-23 14:43 UTC, mooleetzi commented
I transferred json_extract to jq, but CI told me I need to add json_extract  😿

2022-08-23 15:18 UTC, yingfeng commented
> I transferred json_extract to jq, but CI told me I need to add json_extract  😿

@guguducken what does this mean?  since `github.com/matrixorigin/matrixone/pkg/vectorize/json_extract` is deleted in this PR
```
  cd $GITHUB_WORKSPACE/matrixone
  echo "-----------------------ut start-----------------------"
  CGO_CFLAGS="-I${GITHUB_WORKSPACE}/matrixone/cgo"
  CGO_LDFLAGS="-L${GITHUB_WORKSPACE}/matrixone/cgo -lmo -lm"
  go test -v -cover -tags matrixone_test -p 1 -covermode=count --count=1 github.com/matrixorigin/matrixone/pkg/container/bytejson github.com/matrixorigin/matrixone/pkg/container/types github.com/matrixorigin/matrixone/pkg/errno github.com/matrixorigin/matrixone/pkg/sql/parsers/dialect/mysql github.com/matrixorigin/matrixone/pkg/sql/plan/function/builtin/binary github.com/matrixorigin/matrixone/pkg/sql/plan/function github.com/matrixorigin/matrixone/pkg/vectorize/jq github.com/matrixorigin/matrixone/pkg/vectorize/json_extract | tee 'UT-Report.out'
  cat 'UT-Report.out' | grep -a -P "(?m)(?<=ok|\?).*(?=%|])" > 'ut_coverage.raw'
  echo "-----------------------ut finish-----------------------"
  shell: /usr/bin/bash -e {0}
  env:
    raw_ut_coverage: 'ut_coverage.raw'
    ut_report: 'UT-Report.out'
-----------------------ut start-----------------------
no required module provides package github.com/matrixorigin/matrixone/pkg/vectorize/json_extract; to add it:
	go get github.com/matrixorigin/matrixone/pkg/vectorize/json_extract
Error: Process completed with exit code 1.

```

2022-08-24 00:58 UTC, guguducken commented
> > I transferred json_extract to jq, but CI told me I need to add json_extract  😿
> 
> @guguducken what does this mean? since `github.com/matrixorigin/matrixone/pkg/vectorize/json_extract` is deleted in this PR
> 
> ```
>   cd $GITHUB_WORKSPACE/matrixone
>   echo "-----------------------ut start-----------------------"
>   CGO_CFLAGS="-I${GITHUB_WORKSPACE}/matrixone/cgo"
>   CGO_LDFLAGS="-L${GITHUB_WORKSPACE}/matrixone/cgo -lmo -lm"
>   go test -v -cover -tags matrixone_test -p 1 -covermode=count --count=1 github.com/matrixorigin/matrixone/pkg/container/bytejson github.com/matrixorigin/matrixone/pkg/container/types github.com/matrixorigin/matrixone/pkg/errno github.com/matrixorigin/matrixone/pkg/sql/parsers/dialect/mysql github.com/matrixorigin/matrixone/pkg/sql/plan/function/builtin/binary github.com/matrixorigin/matrixone/pkg/sql/plan/function github.com/matrixorigin/matrixone/pkg/vectorize/jq github.com/matrixorigin/matrixone/pkg/vectorize/json_extract | tee 'UT-Report.out'
>   cat 'UT-Report.out' | grep -a -P "(?m)(?<=ok|\?).*(?=%|])" > 'ut_coverage.raw'
>   echo "-----------------------ut finish-----------------------"
>   shell: /usr/bin/bash -e {0}
>   env:
>     raw_ut_coverage: 'ut_coverage.raw'
>     ut_report: 'UT-Report.out'
> -----------------------ut start-----------------------
> no required module provides package github.com/matrixorigin/matrixone/pkg/vectorize/json_extract; to add it:
> 	go get github.com/matrixorigin/matrixone/pkg/vectorize/json_extract
> Error: Process completed with exit code 1.
> ```

This is because this unit test with modified file path did not think of the folder deleted scenario, I will fix it

2022-08-24 13:52 UTC, guguducken commented
@matrix-meow rerun failed

2022-08-24 20:24 UTC, fengttt requested changes
Is there a document on the jq syntax we will support?

2022-08-25 04:20 UTC, mooleetzi commented
> Is there a document on the jq syntax we will support?

I'll add them later, Thx.

2022-08-25 12:40 UTC, guguducken commented
> > > @matrix-meow rerun failed
> > 
> > 
> > All failed jobs are rerun ----- @matrix-meow
> 
> Hello, CI still let me add `github.com/matrixorigin/matrixone/pkg/vectorize/json_extract`.

Hello, I will fix this tomorrow, This CI does not affect the merge at this time.

2022-08-25 12:44 UTC, mooleetzi commented
> > > > @matrix-meow rerun failed
> > > 
> > > 
> > > All failed jobs are rerun ----- @matrix-meow
> > 
> > 
> > Hello, CI still let me add `github.com/matrixorigin/matrixone/pkg/vectorize/json_extract`.
> 
> Hello, I will fix this tomorrow, This CI does not affect the merge at this time.

🫡

2022-08-28 17:59 UTC, fengttt commented
> > Is there a document on the jq syntax we will support?
> 
> I'll add them later, Thx.

This change won't be approved until we see the doc.

2022-09-01 02:41 UTC, ouyuanning approved these changes

2022-09-01 02:54 UTC, iamlinjunhong commented on pkg/sql/parsers/dialect/mysql/mysql_sql.y
> +	JQ '(' STRING ',' STRING ')'
add unit test in mysql_sql_test.go

2022-09-01 14:36 UTC, fengttt approved these changes
Rename jq to extract, this is good to go.

Thank you very much,

2022-09-02 02:54 UTC, mooleetzi commented on pkg/sql/parsers/dialect/mysql/mysql_sql.y
> +	JQ '(' STRING ',' STRING ')'
OK，I will do it right away

2022-09-02 02:57 UTC, mooleetzi commented
> Rename jq to extract, this is good to go.
> 
> Thank you very much,

Ok. Thank you too.

2022-09-05 22:22 UTC, merged