add export data docs and fix step format in import data docs
matrixorigin/matrixone pull request #4765
Opened 2022-08-29 09:38 UTC by lacrimosaprinz

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [x] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2022-08-29 14:25 UTC, dengn requested changes

2022-08-29 14:25 UTC, dengn commented on docs/cn/MatrixOne/Develop/export-data/use-source-export-data.md
> +# 通用方式导出数据
Filename is wrong. There is no such thing as source export.

2022-08-30 06:56 UTC, dengn approved these changes

2022-08-30 21:06 UTC, fengttt reviewed
@dengn can you please check out with WangJie/PengZheng, to verify that select into file ...
The file can be an URL, that points to either local, or somewhere in S3.    From now on we want ALL files to/from database, using an URL.

2022-08-31 02:43 UTC, dengn commented
> @dengn can you please check out with WangJie/PengZheng, to verify that select into file ... The file can be an URL, that points to either local, or somewhere in S3. From now on we want ALL files to/from database, using an URL.

ok. will check on that for 0.6. this PR is still about 0.5.1.

2022-08-31 02:57 UTC, merged