Adapter the dragonboat logger to MO Logger
matrixorigin/matrixone pull request #4817
Opened 2022-08-31 14:44 UTC by xzxiong

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #4802

## What this PR does / why we need it:
Adapter the dragonboat logger to MO Logger, example as following.
- original
```
2022-08-31 22:32:58.220802 I | rsm: [00001:62145] applied ADD ccid 0 (1), n62145 (9c4dccb4-4d3c-41f8-b482-5251dc7a41bf)
2022-08-31 22:32:59.103665 I | LogService: isHAKeeper: true, err: <nil>
2022-08-31 22:32:59.111411 W | raft: [f:1,l:34391,t:10,c:34391,a:34391] [00000:31072] t10 dropped ReadIndex, no leader
```
- new format ( as Property `time`, `level`, `name`, `msg`)
```
{"level":"INFO","time":"2022/08/31 22:32:23.229678 +0800","name":"rsm","caller":"rsm/membership.go:301","msg":"[00001:62145] applied ADD ccid 0 (1), n62145 (9c4dccb4-4d3c-41f8-b482-5251dc7a41bf)"}
{"level":"INFO","time":"2022/08/31 22:32:25.118217 +0800","name":"LogService","caller":"logservice/hakeeper_client.go:313","msg":"isHAKeeper: true, err: <nil>"}
{"level":"WARN","time":"2022/08/31 22:32:25.729346 +0800","name":"raft","caller":"raft/raft.go:2139","msg":"[f:1,l:34386,t:9,c:34386,a:34386] [00000:31072] t9 dropped ReadIndex, no leader"}
```

2022-08-31 17:34 UTC, fengttt approved these changes

2022-09-01 00:54 UTC, zhangxu19830126 requested changes
Dragonboat's logger Adapter uses SugaredLogger, but the rest of the system uses zap's structured log output, which we need to align

2022-09-01 02:42 UTC, zhangxu19830126 approved these changes

2022-09-01 03:10 UTC, daviszhen approved these changes

2022-09-01 04:37 UTC, lni approved these changes

2022-09-01 07:30 UTC, merged