Sql case issue
matrixorigin/matrixone pull request #4914
Opened 2022-09-07 07:10 UTC by lacrimosaprinz

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2022-09-07 07:16 UTC, dengn requested changes
To fully add a bvt case, you need to add also the expected result. In this case, add the mysql result. wrap up the wrong SQL line with the @bvt label.

2022-09-07 21:31 UTC, fengttt reviewed
Where is the expected result file?   I think this will break bvt.

2022-09-07 21:31 UTC, fengttt commented on test/cases/subquery/comparisons-using-subqueries.sql
> +INSERT INTO t1 VALUES ('1','1'),('2','2'),('3','3');Query OK, 0 rows affected (0.02 sec)
Query OK?

2022-09-20 17:46 UTC, fengttt commented
Reject this issue, as comment has not been addressed for a while and I assume it is abandoned.

2022-09-20 17:46 UTC, closed without merging