engine: add context and error to Rows and Size
matrixorigin/matrixone pull request #4956
Opened 2022-09-09 04:22 UTC by reusee

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:
engine: add context and error to Rows and Size

2022-09-09 13:15 UTC, XuPeng-SH approved these changes
lgtm

2022-09-13 05:14 UTC, nnsgmsone approved these changes

2022-09-13 08:08 UTC, daviszhen requested changes

2022-09-13 08:08 UTC, daviszhen commented on pkg/frontend/session.go
> +		return nil
return an empty plan2.Cost{} instead of nil that may lead to the planner's error

2022-09-13 08:08 UTC, daviszhen commented on pkg/frontend/session.go
> +	rows, err := table.Rows(context.TODO())
Get the context from the tcc.ses instead of TODO

2022-09-14 01:42 UTC, daviszhen approved these changes

2022-09-14 02:50 UTC, merged