fix bug:orderBy&limit clause lost in parenSelect clause
matrixorigin/matrixone pull request #4960
Opened 2022-09-09 08:59 UTC by ouyuanning

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #4939 #4934 #4945 

## What this PR does / why we need it:
fix bug:orderBy&limit clause lost in parenSelect clause

2022-09-09 09:31 UTC, aunjgr requested changes

2022-09-09 09:31 UTC, aunjgr commented on pkg/sql/plan/query_builder.go
> +		return builder.buildUnion(selectClause, astOrderBy, astLimit, ctx, isRoot)
This should work, but two `switch...case` are redundant.

First strip off any `*tree.ParenSelect`, then `switch...case` other types. This way it should be more readable.

2022-09-10 02:10 UTC, fengttt reviewed
Is there a similiar bug in union all?

limit after union/union all are very interesting optimizer rules.   totally different.   Can you write down the output plan from query_builder?   Something like the explain output,

2022-09-13 01:29 UTC, ouyuanning commented
> Is there a similiar bug in union all?
> 
> limit after union/union all are very interesting optimizer rules. totally different. Can you write down the output plan from query_builder? Something like the explain output,

1、yes. similar bug in union all.  this bug appear in buildSelect for parenSelect clause.

2. I add some comment before the code

2022-09-13 02:25 UTC, aressu1985 approved these changes

2022-09-13 07:18 UTC, aunjgr approved these changes

2022-09-13 08:37 UTC, merged