support more text and blob type
matrixorigin/matrixone pull request #5036
Opened 2022-09-15 09:23 UTC by bbbearxyz

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #4668

## What this PR does / why we need it:

2022-09-15 09:36 UTC, iamlinjunhong requested changes

2022-09-15 09:36 UTC, iamlinjunhong commented on pkg/sql/parsers/dialect/mysql/mysql_sql.y
> -		        Oid:    uint32(defines.MYSQL_TYPE_TINY_BLOB),
modify in plan, because parser need to format type

2022-09-16 07:34 UTC, fengttt commented on pkg/sql/plan/build_util.go
> +		case defines.MYSQL_TYPE_TINY_BLOB:
Try to use types.VarlenaSize instead of 24

2022-09-16 07:35 UTC, fengttt commented on pkg/sql/plan/build_util.go
> +		case defines.MYSQL_TYPE_TINY_BLOB:
Even better, just do types.T_blob.ToType()

2022-09-16 07:36 UTC, ouyuanning approved these changes

2022-09-16 08:02 UTC, fengttt approved these changes

2022-09-16 09:10 UTC, iamlinjunhong approved these changes

2022-09-17 03:43 UTC, merged