Add prepare ts
matrixorigin/matrixone pull request #5037
Opened 2022-09-15 09:39 UTC by jiangxinmeng1

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [x] Code Refactoring

## Which issue(s) this PR fixes:

issue #4828 

## What this PR does / why we need it:
Add prepare TS
1. Add prepare TS in TxnMVCCNode
2. Replay 1pc txn cmd
3. Add prepare TS in NeedWaitCommit

2022-09-15 11:23 UTC, XuPeng-SH requested changes

2022-09-15 11:23 UTC, XuPeng-SH commented on pkg/vm/engine/tae/catalog/replay.go
> +		replayer.catalog.ReplayCmd(cmd, replayer.dataFactory, nil, nil, replayer.cache, txnif.CmdSnapshot, types.TS{})
The definition of ReplayCmd and other replay APIs is very hard to understand.

2022-09-15 11:23 UTC, XuPeng-SH commented on pkg/vm/engine/tae/catalog/tablemvccnode.go
> +	} else {
Same problem. It should not set the node as deleted.

2022-09-15 11:23 UTC, XuPeng-SH commented on pkg/vm/engine/tae/db/replay.go
> +func (replayer *Replayer) OnReplayCmd(txncmd txnif.TxnCmd, idxCtx *wal.Index, cmdType txnif.CmdType, commitTS types.TS) {
Revisit this API

2022-09-16 12:13 UTC, XuPeng-SH requested changes

2022-09-16 12:13 UTC, XuPeng-SH commented on pkg/vm/engine/tae/catalog/basemvccnode.go
> +	NodeOp               []NodeOp
Don't add NodeOp

2022-09-19 03:46 UTC, XuPeng-SH approved these changes
lgtm

2022-09-19 04:44 UTC, jiangxinmeng1 commented
@mergifyio refresh

2022-09-19 04:45 UTC, merged