CN: Integrate TaskService into CN.
matrixorigin/matrixone pull request #5358
Opened 2022-09-29 10:36 UTC by w-zr

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [x] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

Integrate `TaskService` into CN.
Add integrated test for taskRunner.

2022-09-29 11:30 UTC, zhangxu19830126 requested changes

2022-09-29 11:30 UTC, zhangxu19830126 commented on pkg/cnservice/types.go
> +	TaskRunner struct {
add toml tag. And set default value in config.validate

2022-09-30 03:12 UTC, reusee approved these changes

2022-09-30 03:30 UTC, zhangxu19830126 approved these changes

2022-09-30 06:08 UTC, merged