fix bug: pushdown filter is incorrect in UNION/MINUS/INTERSECT node
matrixorigin/matrixone pull request #5440
Opened 2022-10-08 03:22 UTC by ouyuanning

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #5370

## What this PR does / why we need it:
1、UNION/MINUS/INTERSECT node only pushdown left child
2、PredicatePushdown rule of optimizer is incorrect.  this rule use relPos as absolute position，but it's not.  
      and compared with pushdownfilter  this rule was duplicate.   so i comment it

2022-10-08 04:11 UTC, aunjgr requested changes

2022-10-08 04:11 UTC, aunjgr commented on pkg/sql/plan/query_builder.go
> +		cantPushdown = filters
Filter conditions should be pushed down through set operators

2022-10-08 05:53 UTC, aressu1985 approved these changes

2022-10-09 04:17 UTC, aunjgr approved these changes

2022-10-09 04:24 UTC, aunjgr approved these changes

2022-10-09 04:30 UTC, merged