move init schema logic to task service
matrixorigin/matrixone pull request #5516
Opened 2022-10-10 12:07 UTC by w-zr

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [x] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:
This PR moves initial schema logic to task service. HAKeeper is responsible for create init schema task and taskRunners(CNs) will run these tasks automatically.

Since task service is currently not fully functioning, this PR may have some problems.

2022-10-11 02:36 UTC, zhangxu19830126 requested changes

2022-10-11 02:36 UTC, zhangxu19830126 commented on pkg/cnservice/server.go
> +		func(ctx context.Context, _ func() ie.InternalExecutor) error {
all task execute code must defined in the task.proto

2022-10-11 02:36 UTC, zhangxu19830126 commented on pkg/logservice/service_bootstrap.go
> +func (s *Service) createInitTasks(ctx context.Context) error {
init task need retry. Panic if still failed after retry.

2022-10-11 07:35 UTC, yingfeng approved these changes

2022-10-15 02:18 UTC, daviszhen approved these changes

2022-10-15 07:52 UTC, fengttt approved these changes

2022-10-18 04:45 UTC, closed without merging