CN starts after HAKeeper is running
matrixorigin/matrixone pull request #5617
Opened 2022-10-13 14:24 UTC by w-zr

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:
CN should start after HAKeeper is running.

2022-10-14 02:09 UTC, zhangxu19830126 requested changes
wait DNShard reported after hakeeper state changed to running

2022-10-14 02:33 UTC, cnutshell approved these changes

2022-10-14 03:01 UTC, zhangxu19830126 approved these changes

2022-10-14 10:47 UTC, XuPeng-SH approved these changes
lgtm

2022-10-15 02:14 UTC, daviszhen approved these changes

2022-10-15 02:33 UTC, merged