Add const expression support for unnest.
matrixorigin/matrixone pull request #5625
Opened 2022-10-14 04:13 UTC by mooleetzi

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [X] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

1. extend json_extract.

2. add builtin-function support for unnest args. 
now support:
```
 select `key`,path,value from unnest(substring('{"a":1}...',1,7), '$') u;
```
but if substring has a col as input, such as
 ```
select `key`,path,value from unnest(substring(t1.a,1,7), '$') u;
```
 it will fail now, but can be successful if rewrite it to
```
with tmpt as (select substring(a,1,7) as a from t2) select * from tmpt, unnest(tmpt.a, '$') u;
```

I need to think about how to make col work later.

2022-10-14 08:02 UTC, fengttt requested changes

2022-10-14 08:02 UTC, fengttt commented on pkg/sql/colexec/unnest/unnest.go
> +	case "str":
This has a very bad taste -- I wonder WHY should you care about param type?   It is an expression and get evaluated, shouldn't this be the same?

Yuanning, Long ran or Ming Song/Mo Chen, one of them must have a strong opinion on this.

2022-10-31 09:24 UTC, aressu1985 approved these changes

2022-11-01 00:50 UTC, fengttt approved these changes
Please try to break PR into smaller, separate pieces.   Thank you.l

2022-11-01 02:51 UTC, mooleetzi commented
> Please try to break PR into smaller, separate pieces. Thank you.l

ok

2022-11-01 07:13 UTC, nnsgmsone approved these changes

2022-11-01 07:24 UTC, iamlinjunhong approved these changes

2022-11-02 03:42 UTC, ouyuanning approved these changes

2022-11-02 03:45 UTC, mooleetzi commented on pkg/sql/colexec/expr_eval.go
>  			vec = vector.NewConstFixed(constTimeType, length, t.C.GetTimeval(), proc.Mp())
Ok,I will check.

2022-11-02 04:39 UTC, aunjgr approved these changes

2022-11-02 17:39 UTC, merged