Remove segment
matrixorigin/matrixone pull request #5665
Opened 2022-10-16 13:09 UTC by LeftHandCold

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2022-10-16 15:01 UTC, XuPeng-SH approved these changes
lgtm

2022-10-16 15:03 UTC, fengttt requested changes
What is the purpose of this refactor?    I don't see any useful info in PR message.

2022-10-17 01:34 UTC, reusee approved these changes

2022-10-17 02:15 UTC, nnsgmsone approved these changes
no idea

2022-10-17 02:42 UTC, fengttt approved these changes

2022-10-17 02:46 UTC, merged