add and implement interface of TableColumns
matrixorigin/matrixone pull request #5674
Opened 2022-10-17 06:10 UTC by iamlinjunhong

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #5590

## What this PR does / why we need it:

2022-10-17 06:42 UTC, XuPeng-SH approved these changes
lgtm

2022-10-17 06:46 UTC, daviszhen approved these changes

2022-10-17 06:52 UTC, reusee requested changes

2022-10-17 06:52 UTC, reusee commented on pkg/vm/engine/memoryengine/table.go
> +		OpGetPrimaryKeys,
OpGetTableColumns

2022-10-17 06:55 UTC, iamlinjunhong commented on pkg/vm/engine/memoryengine/table.go
> +		OpGetPrimaryKeys,
Done

2022-10-17 17:18 UTC, fengttt approved these changes

2022-10-18 01:41 UTC, reusee approved these changes

2022-10-18 05:33 UTC, fengttt commented
@mergifyio refresh

2022-10-18 06:01 UTC, merged