support secondary index
matrixorigin/matrixone pull request #5694
Opened 2022-10-17 15:05 UTC by bbbearxyz

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #3609

## What this PR does / why we need it:

2022-10-17 17:28 UTC, fengttt requested changes
Can you add a PR message?

What is the design/strategy, what have you done, is it a full implementation or just grammar?    Etc, etc.

2022-10-18 03:12 UTC, bbbearxyz commented
> Can you add a PR message?
> 
> What is the design/strategy, what have you done, is it a full implementation or just grammar? Etc, etc.

ok, I already add PR message

2022-10-19 01:39 UTC, fengttt approved these changes

2022-10-19 02:04 UTC, ouyuanning approved these changes

2022-10-19 03:47 UTC, aunjgr approved these changes

2022-10-20 02:33 UTC, bbbearxyz commented
@matrix-meow rerun failed

2022-11-03 14:35 UTC, closed without merging