Add cron merge task
matrixorigin/matrixone pull request #6029
Opened 2022-10-27 09:56 UTC by xzxiong

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #5768

## What this PR does / why we need it:

1. init Merge Cron Task while db init.
2. config `MergeCycle` help to define merge cron task run cycle. (see `InitCronExpor`)
     - if < 300 sec, use cronExpr as `@every {secs}s`
     - if < 1 hour, 对 MergeCycle 按 5min 向上取整,  cronExpr as `@every {minutes}m`
     - if <= 12 hours, 对 Merge Cycle 按 小时后取整，cronExpr as `@every {hours}h`
     - else, not supprt

default rule of `MergeCronTask` in `mo_task.sys_cron_task` like:
```
mysql> select * from mo_task.sys_cron_task;
+--------------+------------------------------------------------+------------------------+------------------------------------------------------------------+----------------------+------------------------+---------------+---------------+---------------+---------------+
| cron_task_id | task_metadata_id                               | task_metadata_executor | task_metadata_context                                            | task_metadata_option | cron_expr              | next_time     | trigger_times | create_at     | update_at     |
+--------------+------------------------------------------------+------------------------+------------------------------------------------------------------+----------------------+------------------------+---------------+---------------+---------------+---------------+
|            1 | ETL_merge_task/system.rawlog                   |                      2 | 0x73797374656D2E7261776C6F67                                     | {}                   | 0 0 4,8,12,16,20 * * * | 1666872000000 |             0 | 1666864293155 | 1666864293155 |
|            2 | ETL_merge_task/system.rawlog/yesterday         |                      2 | 0x73797374656D2E7261776C6F6720796573746572646179                 | {}                   | 0 5 0 * * *            | 1666886700000 |             0 | 1666864293223 | 1666864293223 |
|            3 | ETL_merge_task/system_metrics.metric           |                      2 | 0x73797374656D5F6D6574726963732E6D6574726963                     | {}                   | 0 0 4,8,12,16,20 * * * | 1666872000000 |             0 | 1666864293300 | 1666864293300 |
|            4 | ETL_merge_task/system_metrics.metric/yesterday |                      2 | 0x73797374656D5F6D6574726963732E6D657472696320796573746572646179 | {}                   | 0 5 0 * * *            | 1666886700000 |             0 | 1666864293340 | 1666864293340 |
|            5 | ETL_merge_task/system.statement_info           |                      2 | 0x73797374656D2E73746174656D656E745F696E666F                     | {}                   | 0 0 4,8,12,16,20 * * * | 1666872000000 |             0 | 1666864293418 | 1666864293418 |
|            6 | ETL_merge_task/system.statement_info/yesterday |                      2 | 0x73797374656D2E73746174656D656E745F696E666F20796573746572646179 | {}                   | 0 5 0 * * *            | 1666886700000 |             0 | 1666864293472 | 1666864293472 |
+--------------+------------------------------------------------+------------------------+------------------------------------------------------------------+----------------------+------------------------+---------------+---------------+---------------+---------------+
```

2022-10-27 10:00 UTC, yingfeng approved these changes

2022-10-27 10:27 UTC, zhangxu19830126 requested changes

2022-10-27 10:27 UTC, zhangxu19830126 commented on pkg/cnservice/server_task.go
> +			s.task.runner.RegisterExecutor(uint32(task.TaskCode_MetricLogMerge),
move register to outer. Only create cron tasks in system_init task executor

2022-10-27 10:27 UTC, zhangxu19830126 commented on pkg/config/configuration.go
> +	// MergeCycle default: 14400 sec (4 hours).
use util/toml's Duration. and can config with "mergeCycle = "1s"".

2022-10-27 10:51 UTC, daviszhen approved these changes

2022-10-27 13:45 UTC, reusee approved these changes

2022-10-28 11:12 UTC, zhangxu19830126 approved these changes

2022-10-29 08:06 UTC, merged