Objectio Supports context read and write
matrixorigin/matrixone pull request #6032
Opened 2022-10-27 11:20 UTC by LeftHandCold

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:
The objectio read-write interface supports passing in the ctx parameter

2022-10-27 20:47 UTC, fengttt approved these changes

2022-10-28 03:17 UTC, nnsgmsone requested changes

2022-10-28 03:17 UTC, nnsgmsone commented on pkg/vm/engine/disttae/txn.go
> +	return writer.WriteEnd(context.Background())
Please do not use backgroup, please use real context to operate.

2022-10-28 06:51 UTC, nnsgmsone approved these changes

2022-10-28 06:56 UTC, XuPeng-SH approved these changes
lgtm

2022-10-28 12:41 UTC, merged