feat: add launch-tae-CN-tae-DN with docker-compose
matrixorigin/matrixone pull request #6371
Opened 2022-11-07 17:44 UTC by wanglei4687

Signed-off-by: wanglei4687 <wanglei4687@gmail.com>

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [x] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

docker compose start launch-tae-CN-tae-DN  and launch-tae-multi-CN-tae-DN  with minio

**start with different profile**
 launch-tae-CN-tae-DN:
```
docker-compose -f etc/launch-tae-compose/compose.yaml --profile launch-tae-CN-tae-DN up -d --build
```

launch-tae-multi-CN-tae-DN
```
docker-compose -f etc/launch-tae-compose/compose.yaml --profile launch-tae-multi-CN-tae-DN up -d --build
```

2022-11-08 02:53 UTC, yingfeng approved these changes

2022-11-08 12:12 UTC, zhangxu19830126 requested changes

2022-11-08 12:12 UTC, zhangxu19830126 commented on etc/launch-tae-compose/compose.yaml
> +      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
we have the s3 env , but no s3 service in docker-compose?

2022-11-09 06:23 UTC, sukki37 reviewed
How about make cluster configurable, at least support `launch-tae-cn-tae-dn` and `launch-tae-multi-CN-tae-DN`

2022-11-09 06:28 UTC, zhangxu19830126 approved these changes

2022-11-09 09:57 UTC, sukki37 commented on etc/launch-tae-compose/README.md
> +- docker compose version >= v2.12.1
maybe add an install document link here, for others' convenience

2022-11-09 16:57 UTC, sukki37 approved these changes

2022-11-09 17:18 UTC, merged