fix merge_top and top operator bug for T_any Type
matrixorigin/matrixone pull request #6521
Opened 2022-11-12 05:43 UTC by JackTan25

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2022-11-12 07:35 UTC, fengttt requested changes
This does not seems right.   When we will create a T_any type?   Actually should we EVER have a t_any type?

2022-11-12 14:13 UTC, JackTan25 commented
> This does not seems right. When we will create a T_any type? Actually should we EVER have a t_any type?

Yes, please see  #6483 and my tests. These give the examples.

2022-11-12 14:57 UTC, JackTan25 commented
@matrix-meow rerun all failed

2022-11-12 15:51 UTC, JackTan25 commented
@matrix-meow rerun failed

2022-11-12 16:09 UTC, JackTan25 commented
@matrix-meow rerun failed

2022-11-13 02:18 UTC, JackTan25 commented
@matrix-meow rerun failed

2022-11-14 04:08 UTC, nnsgmsone commented on pkg/sql/colexec/top/types.go
> +		if ctr.cmps[pos] == nil {
If set to nil. Does it not participate in the sorting?

2022-11-14 10:47 UTC, closed without merging