fix : correct error when load_file can't found
matrixorigin/matrixone pull request #6558
Opened 2022-11-14 04:13 UTC by jensenojs

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #6313

## What this PR does / why we need it:

2022-11-14 04:19 UTC, jensenojs commented
make it more like this
![image](https://user-images.githubusercontent.com/56761542/201574191-0fa20fa6-1af0-4932-bbbc-5d0d8be932ce.png)

Instead of this 
![image](https://user-images.githubusercontent.com/56761542/201574402-b130e645-0616-42f0-97ff-44569b313da2.png)

2022-11-14 05:16 UTC, fengttt commented on pkg/sql/plan/build_insert.go
> +	moer := err.(*moerr.Error)
Use moerr.IsMoErrCode

2022-11-14 05:16 UTC, jensenojs commented on pkg/sql/plan/build_insert.go
> +	moer := err.(*moerr.Error)
ok

2022-11-14 05:16 UTC, fengttt requested changes
Please fix error code checking code.

2022-11-15 06:07 UTC, aunjgr approved these changes

2022-11-15 06:09 UTC, ouyuanning approved these changes

2022-11-17 03:44 UTC, fengttt approved these changes

2022-12-01 03:41 UTC, merged