fix filepath
matrixorigin/matrixone pull request #6920
Opened 2022-11-24 09:13 UTC by daviszhen

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #6865

## What this PR does / why we need it:
1, use the go package filepath handling the complicate file path.

2022-11-24 09:31 UTC, reusee requested changes

2022-11-24 09:31 UTC, reusee commented on pkg/sql/colexec/external/external.go
> +	filePath = filepath.Clean(filePath)
Should use `path.Clean` since file service uses `/` as the path separator

2022-11-24 09:31 UTC, reusee commented on pkg/sql/colexec/external/external.go
> +	pathDir := strings.Split(filePath, sep)
Should split by `/`

2022-11-24 09:31 UTC, reusee commented on pkg/sql/colexec/external/external.go
> +				matched, err := filepath.Match(pathDir[i], entry.Name)
Should use `path.Match`

2022-11-24 16:35 UTC, reusee approved these changes

2022-11-25 03:43 UTC, nnsgmsone approved these changes

2022-11-25 14:36 UTC, merged