Support  for appending and committing a block whose data is already on  S3/FS.
matrixorigin/matrixone pull request #6925
Opened 2022-11-24 18:19 UTC by triump2020

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2022-11-25 01:24 UTC, nnsgmsone commented on pkg/catalog/types.go
> +	MoBlockMetaOnFSTypes = []types.Type{
What exactly does this schema represent?

2022-11-25 02:26 UTC, ouyuanning approved these changes

2022-11-25 02:43 UTC, XuPeng-SH requested changes
The design needs to be modified and then implemented after the design is completed. We'll discuss it offline

2022-11-27 08:57 UTC, fengttt reviewed
where is the conflict detection on primary keys for those records in the s3 block?

I assume this change handles transactions that write both s3 and records, plus delete, correctly

finally how do you test?

2022-11-28 09:09 UTC, triump2020 commented
> 

  The design needs to modify, close this PR now,  would  recreate a new PR !

2022-11-28 09:09 UTC, closed without merging