Delay applying constantFold on non-volatile fn.
matrixorigin/matrixone pull request #7064
Opened 2022-12-06 05:12 UTC by mooleetzi

## What type of PR is this?

- [ ] API-change
- [X] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #6977 

## What this PR does / why we need it:
1. apply constantFold on function `now/current_timestamp` in normal query.
2. no applying constantFold on `now/current_timestamp` in prepared stmt until prepared stmt are executed, execute one time, fold one time, just like paramReset.

2022-12-06 05:30 UTC, reusee approved these changes

2022-12-06 05:58 UTC, fengttt approved these changes

2022-12-06 09:23 UTC, ouyuanning commented
1、i test these sql in current main branch.
```
create table t1(a timestamp,b int auto_increment);
prepare s1 from 'insert into t1(a,b) values(now(),?)';
set @b=1;
execute s1 using @b;
set @b=2;
execute s1 using @b;
select t1.a=t2.a from t1,(select a from t1  where b=2)as t2 where b=1;
```
we will get the right result now.  not need to change any code.

2、we decide  if one function can be fold in constantFold by Function.Volatile
if we have some bug in this logic. just fix it.
I don't think it's about prepare clause.  it about function's attribute

2022-12-06 09:25 UTC, ouyuanning requested changes
need discuss.

2022-12-06 09:39 UTC, mooleetzi commented
> 1、i test these sql in current main branch.
> 
> ```
> create table t1(a timestamp,b int auto_increment);
> prepare s1 from 'insert into t1(a,b) values(now(),?)';
> set @b=1;
> execute s1 using @b;
> set @b=2;
> execute s1 using @b;
> select t1.a=t2.a from t1,(select a from t1  where b=2)as t2 where b=1;
> ```
> 
> we will get the right result now. not need to change any code.
> 
> 2、we decide if one function can be fold in constantFold by Function.Volatile if we have some bug in this logic. just fix it. I don't think it's about prepare clause. it about function's attribute

1. main branch dose not fold `now` correctly, so function now will be called in execute stage, it's why the  case you test is ok.
2. if only depends on `Volatile`, constFold will replace `now()` with constant, while `execute` a `prepared stmt`, `now()` slot will be the value that the plan first generated.

2022-12-13 01:48 UTC, ouyuanning approved these changes

2022-12-13 01:58 UTC, daviszhen approved these changes

2022-12-13 13:20 UTC, aressu1985 approved these changes

2022-12-14 06:06 UTC, aunjgr approved these changes

2022-12-15 02:49 UTC, merged