Exteranl zonemap
matrixorigin/matrixone pull request #7355
Opened 2022-12-28 08:03 UTC by jianwan0214

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #7264 #6947 #6798 #6680 #6678

## What this PR does / why we need it:

2022-12-28 08:09 UTC, daviszhen approved these changes

2022-12-28 08:11 UTC, nnsgmsone requested changes

2022-12-28 08:11 UTC, nnsgmsone commented on pkg/vm/engine/disttae/util.go
> +func GetColumnsByExpr(expr *plan.Expr, tableDef *plan.TableDef) (map[int]int, []int, int) {
Do not expose these functions. If you really need to expose. Find a special directory for it.

2022-12-28 09:20 UTC, reusee requested changes

2022-12-28 09:20 UTC, reusee commented on pkg/sql/colexec/external/external.go
> +func getFileService(param *ExternalParam, dir string) (fileservice.FileService, error) {
file service instance should always come from proc.FS

2022-12-28 09:20 UTC, reusee commented on pkg/sql/colexec/external/external.go
> +		c.Backend = "S3"
This is wrong. The backend of 'S3' should be configured in the config file. The initialization of proc.FS already handles these details. Do use proc.FS instead.

2022-12-28 09:20 UTC, reusee commented on pkg/sql/colexec/external/external.go
> +		service, err := getFileService(param, dir)
Should call fileservice.GetForETL to obtain a file service instance.

2022-12-29 15:58 UTC, reusee requested changes

2022-12-29 15:58 UTC, reusee commented on pkg/fileservice/local_fs.go
> +func (l *LocalFS) SetRootpath(path string) {
I don't understand why this is required.
After initialization, a LocalFS should never change its root path.

2022-12-29 15:58 UTC, reusee commented on pkg/sql/colexec/external/external.go
> +	case "LOCAL":
The LOCAL file service is global and its root path is configured in the config file. You should never change it.
Just use GetForETL. If GetForETL does not return what you want, fix it.

2022-12-30 01:48 UTC, ouyuanning approved these changes

2022-12-30 04:19 UTC, reusee approved these changes

2022-12-30 09:36 UTC, nnsgmsone approved these changes

2022-12-30 10:04 UTC, merged