[Feature Request]: Support a non-primary-key table with sorting key #6959
matrixorigin/matrixone pull request #7474
Opened 2023-01-05 23:56 UTC by badboynt1

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #6959

## What this PR does / why we need it:
support cluster by multi column

2023-01-06 04:03 UTC, daviszhen approved these changes

2023-01-06 04:13 UTC, heni02 approved these changes

2023-01-06 04:35 UTC, aunjgr approved these changes

2023-01-06 08:24 UTC, fengttt approved these changes

2023-01-09 01:28 UTC, nnsgmsone requested changes

2023-01-09 01:28 UTC, nnsgmsone commented on pkg/sql/compile/operator.go
> +		ClusterByDef:         n.TableDef.ClusterBy,
This modification needs to modify the proto file at the same time, and insert is going to be transferred remotely, so you need to consider this situation.

2023-01-09 09:46 UTC, merged