[Bug] Fix format func when the format string is null
matrixorigin/matrixone pull request #7658
Opened 2023-01-16 08:58 UTC by YANGGMM

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #7106  #7109 

## What this PR does / why we need it:

2023-01-16 09:02 UTC, heni02 approved these changes

2023-01-18 08:11 UTC, aunjgr requested changes

2023-01-18 08:11 UTC, aunjgr commented on pkg/vectorize/format/format.go
> +	if number == "" {
better use `len(number) == 0` to determine an empty string

2023-01-18 09:27 UTC, aunjgr approved these changes

2023-01-18 09:49 UTC, merged