Support auto_incr per CN cache.
matrixorigin/matrixone pull request #7659
Opened 2023-01-16 09:49 UTC by iceTTTT

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #6956 

## What this PR does / why we need it:

2023-01-17 02:30 UTC, ouyuanning reviewed
maybe you can make a meeting to share the design

2023-01-17 02:30 UTC, ouyuanning commented on pkg/frontend/types.go
> +	cacheSize = 1000
1000 is too small

2023-01-17 02:30 UTC, ouyuanning commented on pkg/frontend/routine_manager.go
> +func (rm *RoutineManager) GetNextCacheId(colDefs []*plan.ColDef, ctx context.Context, param *colexec.AutoIncrParam, bat *batch.Batch, tableID uint64) ([]uint64, []uint64, error) {
maybe call   GetNextAutoIncrNum  is better

2023-01-17 02:30 UTC, ouyuanning commented on pkg/frontend/routine_manager.go
> +		name := fmt.Sprintf("%d_%s", tableID, col.Name)
i do not know if only use tableID for key is better?

2023-01-18 06:25 UTC, reusee requested changes

2023-01-18 06:25 UTC, reusee commented on pkg/vm/process/types.go
> +	Ses            any
I suggest using a full word but not an abbreviation, too hard to understand.

2023-01-18 16:26 UTC, reusee approved these changes

2023-01-19 01:57 UTC, ouyuanning approved these changes

2023-01-19 09:04 UTC, daviszhen approved these changes

2023-01-30 08:18 UTC, nnsgmsone reviewed
If one insertion acts on both cn again. This cache how to ensure the correctness of it.

2023-01-30 08:58 UTC, nnsgmsone approved these changes

2023-01-30 11:49 UTC, aptend approved these changes

2023-01-30 11:51 UTC, merged