Para load
matrixorigin/matrixone pull request #7788
Opened 2023-02-01 13:36 UTC by jianwan0214

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #7264 #7738 #7442 #5941 #7804

## What this PR does / why we need it:

2023-02-02 01:46 UTC, daviszhen approved these changes

2023-02-02 06:19 UTC, ouyuanning approved these changes

2023-02-02 06:32 UTC, iamlinjunhong approved these changes

2023-02-02 07:42 UTC, aressu1985 approved these changes

2023-02-02 13:08 UTC, nnsgmsone commented on pkg/sql/colexec/external/external.go
> +		tailSize = append(tailSize, int64(len(line)))
I think this is wrong, if it turns out to be an unfinished string, you need to move on. As with all csv libraries

2023-02-02 13:27 UTC, nnsgmsone requested changes
After the first rough cut, you need to use a tail-like strategy to precisely check the true required size of each part and the starting offset (while needing to deal with the effects of ""), otherwise this implementation I'm not sure is what mo needs.

2023-02-03 04:13 UTC, nnsgmsone commented
lgtm

2023-02-03 04:13 UTC, nnsgmsone approved these changes

2023-02-03 04:38 UTC, merged