change compostite primary key name col format
matrixorigin/matrixone pull request #7987
Opened 2023-02-13 05:15 UTC by bbbearxyz

now compostire primary key name is __mo_cpkey + uuid

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #7986 

## What this PR does / why we need it:

2023-02-13 07:53 UTC, ouyuanning approved these changes

2023-02-13 13:52 UTC, sukki37 requested changes
Please leave a better commit message in What this PR does / why we need it: part.

2023-02-14 09:35 UTC, bbbearxyz commented
> Please leave a better commit message in What this PR does / why we need it: part.

ok.

2023-02-16 03:29 UTC, heni02 approved these changes

2023-02-18 11:28 UTC, closed without merging