adjust stats and join order
matrixorigin/matrixone pull request #8047
Opened 2023-02-15 08:44 UTC by badboynt1

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2023-02-15 09:46 UTC, aunjgr approved these changes

2023-02-15 09:54 UTC, sukki37 requested changes
Please write a good commit message and proper comments in `What this PR does / why we need it:`, thank you.

2023-02-15 11:20 UTC, sukki37 approved these changes

2023-02-16 02:16 UTC, nnsgmsone approved these changes

2023-02-16 02:46 UTC, merged