Support sequence in parser
matrixorigin/matrixone pull request #8199
Opened 2023-03-01 06:05 UTC by iceTTTT

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #6590 

## What this PR does / why we need it:

2023-03-01 06:33 UTC, ouyuanning approved these changes

2023-03-09 06:13 UTC, aunjgr approved these changes

2023-03-14 10:27 UTC, zhangxu19830126 approved these changes

2023-03-15 06:28 UTC, iamlinjunhong approved these changes

2023-03-15 06:55 UTC, daviszhen requested changes
需要一个design docs 介绍下怎么实现sequence和相关函数的。

2023-03-15 06:55 UTC, daviszhen commented on pkg/frontend/authenticate.go
> +	PrivilegeTypeShowSequences
跟张潇 @domingozhang 确认下。有没有show/create/drop/alter sequence的权限。我印象中没有。

2023-03-15 08:39 UTC, iceTTTT commented
https://github.com/iceTTTT/docs/blob/sequence/design/sequence.md  design doc

2023-03-15 09:04 UTC, reusee approved these changes

2023-03-15 11:17 UTC, iceTTTT commented on pkg/frontend/authenticate.go
> +	PrivilegeTypeShowSequences
Removed  privilege related code.

2023-03-20 08:34 UTC, daviszhen approved these changes

2023-03-20 08:34 UTC, daviszhen commented on pkg/sql/plan/function/builtin/seq/seq_util.go
> +// func makeBatch(values []interface{}, proc *process.Process) (*batch.Batch, error) {
just remove these unused code

2023-03-22 05:03 UTC, nnsgmsone approved these changes

2023-03-22 11:39 UTC, merged