Decimal Refactor
matrixorigin/matrixone pull request #8244
Opened 2023-03-03 06:33 UTC by zengyan1

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #6611 

## What this PR does / why we need it:
New Decimal64 and Decimal128

2023-03-03 06:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/matrixorigin/matrixone?pullRequest=8244) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/matrixorigin/matrixone?pullRequest=8244) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/matrixorigin/matrixone?pullRequest=8244) it.</sub>

2023-03-03 06:39 UTC, reusee approved these changes

2023-03-05 03:23 UTC, sukki37 commented
The code coverage of some files is below 75%. Please add more unit tests or BVT cases.
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/77312370/222939886-ee917190-16c2-4a3a-9f1e-fc4ba8548c8a.png">

2023-03-06 02:02 UTC, ouyuanning approved these changes

2023-03-07 07:09 UTC, aressu1985 approved these changes

2023-03-09 11:16 UTC, aunjgr approved these changes

2023-03-13 12:07 UTC, heni02 approved these changes

2023-03-13 12:21 UTC, sukki37 commented
Please add some ut or bvt cases to improve code coverage, or at least try to improve the coverage of your own code files, thanks.
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/77312370/224699877-0af95421-b554-4423-976c-db4e88d2df72.png">

2023-03-13 12:22 UTC, XuPeng-SH commented on pkg/vm/engine/tae/compute/compare.go
> +		return int64(a.(types.Decimal64).Compare(b.(types.Decimal64)))
return types.CompareDecimal64(a.(types.Decimal64), b.(types.Decimal64))

2023-03-13 12:23 UTC, XuPeng-SH commented on pkg/vm/engine/tae/compute/compare.go
> +		return int64(a.(types.Decimal128).Compare(b.(types.Decimal128)))
return types.CompareDecimal128(a.(types.Decimal128), b.(types.Decimal128))

2023-03-13 12:23 UTC, XuPeng-SH commented on pkg/vm/engine/tae/containers/vecwindow.go
> +			if d != od {
return d == od

2023-03-13 12:23 UTC, XuPeng-SH commented on pkg/vm/engine/tae/containers/vecwindow.go
> +			if d != od {
return d == od

2023-03-13 12:24 UTC, XuPeng-SH approved these changes

2023-03-13 12:59 UTC, LeftHandCold approved these changes

2023-03-14 10:16 UTC, aunjgr requested changes

2023-03-14 10:16 UTC, aunjgr commented on pkg/container/types/decimal_test.go
> +func TestDecimalMulDiv(t *testing.T) {
This case fails. Please fix and recommit.

2023-03-14 11:00 UTC, m-schen approved these changes
colexec and function lgtm.

2023-03-14 11:22 UTC, aunjgr approved these changes

2023-03-15 02:18 UTC, daviszhen approved these changes

2023-03-15 02:55 UTC, nnsgmsone approved these changes

2023-03-15 03:04 UTC, iamlinjunhong approved these changes

2023-03-15 05:52 UTC, merged