fix 8298
matrixorigin/matrixone pull request #8300
Opened 2023-03-08 03:25 UTC by JackTan25

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2023-03-08 04:48 UTC, fengttt requested changes
Are you saying context cancel will trigger a type assert panic?    This seems to fix a symptom rather than cause.

2023-03-08 05:34 UTC, JackTan25 commented
> Are you saying context cancel will trigger a type assert panic? This seems to fix a symptom rather than cause.
No, when the context cancel, it will return an error ,but I don't return the error but let it go ahead, so it will result this.

2023-03-08 19:14 UTC, fengttt commented
> > Are you saying context cancel will trigger a type assert panic? This seems to fix a symptom rather than cause.
> 
> No, when the context cancel, it will return an error , I don't return the error in the pr but let it go ahead, so it will result this. That's my fault, sorry about that

Fixing the context cancel, which is good -- but the issues #8294 #8298 that you claim you fixed, they are type assert failures.   How come a context cancel to trigger a type assert failure?    Something seems wrong but not addressed.

2023-03-09 01:08 UTC, closed without merging

2023-03-09 01:08 UTC, fengttt approved these changes