reorder insert instructions
matrixorigin/matrixone pull request #8372
Opened 2023-03-10 11:39 UTC by w-zr

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [x] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

Reorder insert, preinsert and onDuplicateKey.
Create scope before insert and move preinsert and onDuplicateKey to new scope.

2023-03-12 08:48 UTC, fengttt requested changes
please as dn side to review the code.    please actively seek review feedback, adding reviewers.

2023-03-13 06:14 UTC, m-schen approved these changes

2023-03-13 07:14 UTC, nnsgmsone approved these changes

2023-03-13 08:20 UTC, w-zr reviewed
Added @triump2020.

2023-03-13 15:51 UTC, triump2020 approved these changes

2023-03-13 20:20 UTC, fengttt approved these changes

2023-03-13 20:56 UTC, merged