fix dispatch issue
matrixorigin/matrixone pull request #8451
Opened 2023-03-14 16:07 UTC by dongdongyang33

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:
fix dispatch issue

2023-03-15 00:07 UTC, fengttt requested changes
Fix which issue?   What was the problem?   Can you please write a meaningful commit message?

2023-03-15 04:12 UTC, dongdongyang33 commented
> Fix which issue? What was the problem? Can you please write a meaningful commit message?

No corresponding issue id, update the problem in describe now.

2023-03-15 05:02 UTC, m-schen approved these changes

2023-03-17 03:43 UTC, fengttt approved these changes

2023-03-17 03:55 UTC, nnsgmsone approved these changes

2023-03-17 05:57 UTC, dongdongyang33 commented
@mergifyio refresh

2023-03-17 06:28 UTC, m-schen approved these changes

2023-03-17 09:18 UTC, merged