operations support in publish side
matrixorigin/matrixone pull request #8470
Opened 2023-03-15 10:05 UTC by mooleetzi

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [X] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #6669 

## What this PR does / why we need it:

2023-03-16 02:35 UTC, sukki37 requested changes
Please add some ut or bvt cases to improve code coverage, or at least try to improve the coverage of code files with extremely low coverage rate, thanks.
<img width="997" alt="image" src="https://user-images.githubusercontent.com/77312370/225495441-752b6a2e-58f0-477d-8539-27a2783f0afc.png">

2023-03-16 02:36 UTC, iamlinjunhong approved these changes

2023-03-16 06:16 UTC, heni02 approved these changes

2023-03-16 06:19 UTC, daviszhen approved these changes

2023-03-17 06:34 UTC, mooleetzi commented
> Please add some ut or bvt cases to improve code coverage, or at least try to improve the coverage of code files with extremely low coverage rate, thanks.
> <img alt="image" width="997" src="https://user-images.githubusercontent.com/77312370/225495441-752b6a2e-58f0-477d-8539-27a2783f0afc.png">

added more ut related to my modification, pls take a look.

2023-03-17 06:42 UTC, XuPeng-SH approved these changes

2023-03-20 02:29 UTC, aressu1985 approved these changes

2023-03-20 02:43 UTC, nnsgmsone approved these changes

2023-03-20 06:47 UTC, sukki37 approved these changes

2023-03-20 12:12 UTC, merged