support parallel load with compressed file
matrixorigin/matrixone pull request #8543
Opened 2023-03-20 07:07 UTC by jianwan0214

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #8124 #8270

## What this PR does / why we need it:

2023-03-20 07:41 UTC, m-schen commented
you are cheating.
you put the real load work at pre-insert operator. and load operator just send the file position?

why not build a pipeline that:

n * external -> merge -> dispatch to -> n * insert

2023-03-20 11:11 UTC, nnsgmsone commented
The correct pipeline should be [external meta-scan -> dispatch-> multiple external scans]

2023-03-22 03:35 UTC, iamlinjunhong approved these changes

2023-03-22 03:40 UTC, XuPeng-SH approved these changes

2023-03-22 06:42 UTC, m-schen approved these changes

2023-03-22 06:42 UTC, m-schen commented on pkg/sql/compile/compile.go
> +	ds.Proc.ParallelLoad = true
remove the load related codes outside of ConstructMergeScope() or remove whole method.

2023-03-23 06:18 UTC, nnsgmsone requested changes
算子间交互的永远都是batch，然后externfill为什么不是一个普通的projection

2023-03-23 07:01 UTC, nnsgmsone commented
一个更加合理的方式可能是构建plan的时候就得到一个类似这样的plan, extern_scan(得到csv数据) -> projection(用特定函数从csv数据中提取数据） -> insert。然后设置projection和insert的并行度即可

2023-03-28 07:01 UTC, ouyuanning approved these changes

2023-03-28 10:59 UTC, aunjgr approved these changes

2023-03-28 12:01 UTC, m-schen requested changes

2023-03-29 02:29 UTC, m-schen approved these changes
lgtm.

2023-03-29 02:32 UTC, heni02 approved these changes

2023-04-03 03:44 UTC, aressu1985 approved these changes

2023-04-07 06:30 UTC, daviszhen approved these changes

2023-05-07 02:21 UTC, nnsgmsone requested changes

2023-05-07 02:21 UTC, nnsgmsone commented on pkg/sql/colexec/external/external.go
> +	bat.Cnt = 1
what is this?

2023-05-08 02:28 UTC, nnsgmsone approved these changes

2023-05-08 03:53 UTC, guguducken commented
@mergify refresh

2023-05-08 09:19 UTC, merged