fix inconsistency of decimal scale for particular queries
matrixorigin/matrixone pull request #8549
Opened 2023-03-20 10:38 UTC by zengyan1

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #8465

## What this PR does / why we need it:

2023-03-20 10:46 UTC, m-schen approved these changes

2023-03-20 11:27 UTC, aunjgr requested changes
There are other places that types.T(somePlanExpr.Typ.GetId()).ToType() or types.T(somePlanExpr.Typ.Id).ToType() is used. They also seems problematic.

Please find and investigate all of them.

2023-03-21 03:44 UTC, aunjgr approved these changes

2023-03-21 03:59 UTC, aunjgr commented
@mergify queue

2023-03-21 05:14 UTC, merged