support parallel load for multi-CN
matrixorigin/matrixone pull request #8801
Opened 2023-03-30 13:48 UTC by jianwan0214

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #7985

## What this PR does / why we need it:

2023-04-04 02:23 UTC, XuPeng-SH approved these changes

2023-04-07 06:02 UTC, m-schen approved these changes

2023-04-10 10:04 UTC, nnsgmsone commented
Please fix cicd first

2023-04-14 01:29 UTC, nnsgmsone requested changes

2023-04-14 01:29 UTC, nnsgmsone commented on pkg/sql/compile/scope.go
> +	case s.Proc.LoadTag:
Why do you need such a flag, this is not the type of pipeline?

2023-04-16 07:41 UTC, merged