Show accounts save result
matrixorigin/matrixone pull request #8855
Opened 2023-04-04 09:07 UTC by taofengliu

## What type of PR is this?

- [ ] API-change
- [X] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #8715

## What this PR does / why we need it:

2023-04-04 11:54 UTC, daviszhen requested changes

2023-04-04 11:54 UTC, daviszhen commented on pkg/frontend/session.go
> +	return ses.AppendResultBatch(dataSet)
为什么要merge？放到一个slice里面不行吗？

2023-04-07 06:39 UTC, daviszhen approved these changes

2023-04-07 06:52 UTC, nnsgmsone commented on pkg/frontend/session.go
> +	ses.resultBatches = append(ses.resultBatches, dup)
How to ensure that the results are not oom when they are too big

2023-04-07 06:56 UTC, nnsgmsone reviewed
Generate some batch yourself, then feed the data when the batch comes, making sure that all but the last batch are 8192 in length. I think this is more reasonable.

2023-04-12 04:27 UTC, merged