Remove some wrong mpool use in agg
matrixorigin/matrixone pull request #9513
Opened 2023-05-17 12:23 UTC by nnsgmsone

## What type of PR is this?

- [ ] API-change
- [X] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

1. remove an illegal free in the distinct aggregate
2.  remove two illegal alloc in the group_concat

2023-05-17 12:28 UTC, m-schen approved these changes

2023-05-17 14:18 UTC, fengttt reviewed
first of all, why do we need unmarshalbinsry at all?   when is marshal and unmarshall called?

2023-05-18 01:44 UTC, nnsgmsone commented
Since it needs to be passed to another node, I don't know what better way to do it than to serialize and then deserialize @fengttt

2023-05-18 02:32 UTC, fengttt requested changes
Need to talk

2023-05-18 04:26 UTC, fengttt commented on pkg/sql/colexec/agg/distagg.go
> +	m := mpool.MustNewZeroNoFixed() // this is a hack, will remove later
This code is so confusing.    Why do you need copyData?   The you copy data into data in line 427.
This mpool need to be deleted.   In this case, why not put it in the operator?   Finally why should we use Marshal/Unmarshal interface ...   Is a operator or operator state?

2023-05-18 04:28 UTC, fengttt commented on pkg/sql/colexec/agg/distagg.go
>  			}
Following code, why is MySQLString useful?    And finally, a.priv, what is that?

2023-05-18 04:29 UTC, fengttt commented on pkg/sql/colexec/multi_col/group_concat/group_concat.go
>  	m := mpool.MustNewZeroNoFixed()
Again, this must be deleted.

2023-05-18 04:30 UTC, fengttt commented on pkg/sql/colexec/multi_col/group_concat/group_concat.go
>  	copy(da1, eg.InsertsStrData)
Why do you need copy?

2023-05-18 04:31 UTC, fengttt reviewed
So many things wrong ...

2023-07-01 10:14 UTC, closed without merging