fileservice: add isRetryableError
matrixorigin/matrixone pull request #9569
Opened 2023-05-20 07:59 UTC by reusee

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2023-05-20 15:25 UTC, sukki37 requested changes
Please provide a clear and comprehensive commit message.

2023-05-21 06:40 UTC, zhangxu19830126 approved these changes

2023-05-21 06:42 UTC, nnsgmsone approved these changes

2023-05-21 07:02 UTC, sukki37 approved these changes

2023-05-21 12:19 UTC, merged