fix merge transfer
matrixorigin/matrixone pull request #9590
Opened 2023-05-21 06:20 UTC by aptend

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

fix delete transfer during committing merge operation

2023-05-21 06:56 UTC, XuPeng-SH approved these changes

2023-05-21 07:01 UTC, sukki37 requested changes
Please write a clear and comprehensive commit message.

2023-05-21 07:21 UTC, aptend commented
> 

updated

2023-05-22 02:06 UTC, sukki37 approved these changes

2023-05-22 02:35 UTC, merged