fix nil panic
matrixorigin/matrixone pull request #9617
Opened 2023-05-22 07:59 UTC by JackTan25

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2023-05-22 08:33 UTC, nnsgmsone approved these changes

2023-05-24 17:09 UTC, fengttt requested changes
9616 is not even an issue.

2023-05-24 17:11 UTC, fengttt requested changes
Well, it is an issue afterall.

Should add the test to bvt.

2023-05-29 10:19 UTC, m-schen commented
该issue在最新的main上已经修复。

2023-05-29 10:19 UTC, closed without merging