add err info
matrixorigin/matrixone pull request #9693
Opened 2023-05-26 08:59 UTC by YANGGMM

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #9692 

## What this PR does / why we need it:
add err info about pub_sub err

2023-05-26 16:11 UTC, fengttt requested changes
The error message should not be an internal error.    It should have its own, well formed/documented error.   If do not have an appropriate error yet, create a new one.

Internal error should never reach customer.

You cannot print out account list in error message.   This is a security bug.

2023-05-27 04:35 UTC, daviszhen approved these changes

2023-05-27 04:36 UTC, daviszhen requested changes

2023-05-27 04:36 UTC, daviszhen commented on pkg/frontend/authenticate.go
>  					return nil, err
这地方 goto handleFailed.

2023-05-27 04:36 UTC, daviszhen commented on pkg/frontend/authenticate.go
>  					return nil, err
这是在begin开始的事务中。要清理事务。

2023-05-30 02:09 UTC, closed without merging