Wuqinxuan/fix metadata scan table issue
matrixorigin/matrixone pull request #9695
Opened 2023-05-26 10:43 UTC by dongdongyang33

## What type of PR is this?

- [ ] API-change
- [x] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

fix issue #9653
fix and improve feature #8342 

## What this PR does / why we need it:

1. fix the issue that the size part use the wrong col meta
2. change the way txn_table pass metadata info to colexec

2023-05-29 04:42 UTC, reusee approved these changes

2023-05-29 05:49 UTC, nnsgmsone approved these changes

2023-05-29 06:09 UTC, aressu1985 approved these changes

2023-05-29 06:22 UTC, daviszhen approved these changes

2023-05-30 03:07 UTC, ouyuanning commented on pkg/sql/plan/metadata_scan.go
>  				NotNullable: true,
for now. we will have ColDef.Default all the time.
maybe you should fill some value to ColDef.Default too

2023-05-30 03:18 UTC, m-schen approved these changes

2023-05-30 03:20 UTC, aunjgr requested changes

2023-05-30 03:20 UTC, aunjgr commented on pkg/sql/colexec/table_function/metadata_scan.go
> +			vector.AppendAny(opBat.Vecs[i], bid, false, mp)
should use `AppendFixed` as much as possible, unless the second argument is indeed `any` type

2023-05-30 03:28 UTC, m-schen approved these changes

2023-05-30 05:12 UTC, aunjgr approved these changes

2023-05-30 05:33 UTC, merged