don't skip when error happened in agg
matrixorigin/matrixone pull request #9746
Opened 2023-05-30 10:30 UTC by zengyan1

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #9650 

## What this PR does / why we need it:

2023-05-30 10:31 UTC, matrix-meow commented
@zengyan1 Thanks for your contributions!

**Here are review comments for file pkg/sql/colexec/agg/agg.go:**
The pull request is titled "don't skip when error happened in agg" and is marked as a bug fix. The body of the pull request indicates that it fixes issue #9650. The changes made in

**Here are review comments for file pkg/sql/colexec/agg/distagg.go:**
The pull request aims to fix an issue with the agg function in the `pkg/sql/colexec/agg/distagg.go` file. The issue is that the function skips over errors that occur during execution. The changes made in the pull request remove the error check and instead set the error value in the struct. 

However, there are several problems with this pull request:

1. The title of the pull request is not descriptive enough. It only mentions that an error occurred, but does not provide any information about what the error is or how it is being fixed. A more descriptive title would help reviewers understand the purpose of the pull request.

2. The body of the pull request is incomplete. It only provides a checklist of the type of PR and the issue number that it fixes. It does not provide any additional information about the issue or the changes being made. A more detailed description of the problem and the solution would help reviewers understand the context of the changes.

3. The changes made in the pull request do not address the underlying issue. Instead of fixing the error, the changes simply set the error value in the struct. This means that the error is still being ignored and not properly handled. The changes should be updated to properly handle the error and prevent it from being skipped over.

4. The changes made in the pull request are not optimized. The removal of the error check and the addition of the error value in the struct could potentially lead to more errors being ignored or not properly handled. The changes should be reviewed to ensure that they are not introducing new issues or causing unintended consequences.

To address these issues, the pull request should be updated with a more descriptive title and a detailed description of the problem and the solution. The changes should also be updated to properly handle the error and prevent it from being skipped over. Additionally, the changes should be reviewed to ensure that they are not introducing new issues or causing unintended consequences.

2023-05-31 10:11 UTC, m-schen approved these changes

2023-06-01 00:59 UTC, sukki37 requested changes
Please write a comprehensive message for your pr, thank you.

2023-06-08 09:52 UTC, sukki37 approved these changes

2023-06-08 13:56 UTC, merged